### ISSUE TITLE
Many sheets' site fugitives do not include randomized draw for uncertainty runs

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#100]
For the VF site method, my understanding is that for each the production and processing fugitive rates, the leaks are split by fractions between specific processes. For those processes there is a "deterministic" loss rate and a "randomized" loss rate. When drawing in fugitives rates for those processes, the calculation sheets need to determine whether to pull from the deterministic (if uncertainty runs=1) or randomized (if uncertainty runs>1) rates. This is happening for wellheads and separators, but not for the remaining types of equipment. Therefore, I believe that the IF logic to determine whether to pull deterministic or randomized site method fugitives needs to be added to the following sheets:

-Glycol Dehydrator
-Acid Gas Removal
-Demethanizer
-Ryan Holmes
-Crude Oil Stabilization
-Gas Gathering

Same issue exists for some of the compressors, where the sheets only pull in the mean loss rate 'VF method - Site'!AL345, but I think should use an IF statement to sometimes pull in the uncertainty loss rate 'VF method - Site'!AL346.

-Gas Reinjection Compressor
-Gas Lifting Compressor
-Gas Flooding Compressor
-CO2 Reinjection Compressor
-Sour Gas Reinjection Compressor

**Comment by JSRuthe** [comment]
Addressed issue for all except compressors

**Comment by JSRuthe** [comment]
Addressed issue for compressors
