### ISSUE TITLE
Secondary inputs eta btu/btu unit potentially confusing

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#101]
On the Secondary Inputs sheets, some of the "eta"s are percent efficiencies and some are the in inverse (the amount of fuel needed to deliver an amount of heating). Those labeled as % are easy to understand, however those with labels such as btu/btu could be confusing for the user. OPGEE mixes cases where the btu/btu is >1 and <1, that is sometimes it means btu_fuel/btu_heat_delivered and other times it means btu_heat_delivered/btu_fuel. I'm not suggesting to standardize these, but it would be helpful if the units were clarified on the secondary inputs sheet for each "eta" with a unit of btu/btu. It could either be done in the units column itself or in a note.

**Comment by arbrandt** [comment]
Fixed, clarified and commented. See notes.
