### ISSUE TITLE
Feed losses added in wrong place in equations for crude and petcoke transport

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#102]
On the _Crude Oil Transport_ sheet, the diesel output includes Losses_feed. The unit of that variable is btu/mmbtu, but it is added to a term with the units btu/d. I think it should have been added before multiplying by M111. The same issue exists on the Petcoke Transport sheet in the outputs petcoke cell. For my knowledge, what are feed losses?

**Comment by smasnadi** [comment]
Fixed for both crude oil and petcoke transport sheets (diesel output). Could not find any issue for petcoke cell.
