### ISSUE TITLE
Possible load factor issue

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#106]
On both the _Petcoke Transport_ and _Crude Oil Transport_ sheets, the energy intensity (origin to destination AND back-haul) is calculated with a multiplicative factor for the "load factor". Based on my logic, it seems like the equation should be divided by the load factor (load factor in denominator), such that when the load factor goes down the energy intensity in btu/ton-mi goes up. The load factors seem to be the fraction of total capacity the ship is loaded with, so a ship with less load should have higher energy use per lb of load. Correct me if I'm wrong.

**Comment by qlangfitt** [comment]
I've reviewed this again and I think my original error report was incorrect. I had assumed the load factor referred to the percentage of the ship's total cargo capacity that was being used, but it seems to actually refer to the percentage of total engine power being used. If the latter is true, then no changes are needed.

**Comment by arbrandt** [comment]
You are correct in your assessment. Load factor is used in the engine efficiency calculation.
