### ISSUE TITLE
Indirect energy credits/debits referencing wrong products

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#108]
On the _Energy Summary_ sheet, Table 4, credit column, energy for crude oil supply/export, the equation references the fuel cycle of electricity, but I believe it should reference the fuel cycle of crude oil. In the same table, debit column, energy for NGL supply/export, the equation references the imports of upgrader process gas, not NGL.

**Comment by smasnadi** [comment]
Both fixed!
