### ISSUE TITLE
GHG summary venting and fugitive emissions

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#111]
Two issues on the _GHG Summary_ sheet, in the first table: 

(1) Transport and storage (row 15) should include a system boundary check to determine whether emissions from transport and storage should be included (applies to both venting and fugitives columns). This is done for transport and storage combustion emissions. 

(2) Electricity generation venting (J18) has a negative sign at the start of the equation. I believe that's a mistake, but it also won't matter since there aren't any fugitives or venting emissions from electricity in the model.

**Comment by arbrandt** [comment]
Fixed issue #1 using if logic to only include fugitives if refinery process boundary is selected.

**Comment by qlangfitt** [comment]
Looked back at this again and turns out I should have never made the error report. The report was based on my cell-by-cell comparisons of equations, not the actual behavior of the model. By implementing your fix, it actually incorrectly suppressed gas transmission fugitives. Furthermore, the oil system boundary check was never necessary, practically speaking, because there are no VFF emissions possible in the model from oil transmission. There is also no gas system boundary check necessary on the GHG summary sheet because all gas transmission processes only pass VFF emissions when their status is ON. On that note, might want to consider adding a system boundary check to the ON/OFF tag for Stream 262 (Flow Sheet FV163). At the very least, please revert the equations on GHG Summary J15:L15 to their old equations (simply remove the system boundary check):

J15: =IF(OR(Settings_Fugitives="Site",Settings_Fugitives="Component"),'Venting & Fugitives 3.0'!D80,0)

L15: =IF(OR(Settings_Fugitives="Site",Settings_Fugitives="Component"),'Venting & Fugitives 3.0'!D65,0)

**Comment by smasnadi** [comment]
Reverted back GHG Summary J15:L15 to their old equations as suggested. 
I also modified Flow Sheet FV163. qlangfitt: Please double-check.
