### ISSUE TITLE
CO2 lost from CO2 recycling references total CO2 from depreciated model

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#113]
On the _GHG Summary_ sheet, in the third table, the CO2 lost from venting and fugitives in CO2 recycling references the depreciated model. Why use depreciated? Additionally, it seems to reference the total emissions, not just CO2 recycling.

**Comment by arbrandt** [comment]
Mass accounting for fugitives now references the appropriate cell for stream 276 for fugitives from CO2 reinjection compressor.
