### ISSUE TITLE
Emissions summary VFF on Active Field sheet missing some stages

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#115]
On the _Active Field_ sheet, the summary emissions table's total VFF (AK16) is missing LNG, crude transport, and gas distribution. If added here, then VFF from crude transport and gas distribution should be removed from the Transport row.

**Comment by smasnadi** [comment]
Fixed!
Decided to keep VFF for transport row and make a * comment that VFF is included here
