### ISSUE TITLE
Default value discrepancies between model and documentation

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#116]
On the _Active Field_ sheet, the productivity index (K67) has a default value of 3. However, the documentation lists that the default should be 17 (p. 61). The Steam-to-oil ratio (K102) has a default of 3.5, but documentation says it should be 3.0 (p. 68).

**Comment by smasnadi** [comment]
PI: 17 is set for uncert. analysis 
SOR: fixed to 3
