### ISSUE TITLE
Downhole pump uncertainty misalignment

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#118]
On the _Active Field_ sheet, the downhole pump realization (M48) references the binary yes probability of water reinjection, not downhole pump. Change U49 and S49 to U48 and S48. Also, notes say that this should be 0 if gas lifting applies, but that condition isn't set out in the equation.

**Comment by smasnadi** [comment]
Fixed! 
The gas lifting condition is not needed as it is covered in cell M52.
