### ISSUE TITLE
Oil production uncertainty mismatch between high range and deterministic default

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#119]
On the _Active Field_ sheet, the high range is an order of magnitude lower than the deterministic default for oil production (row 63). I assume it's the deterministic default that is wrong.

**Comment by smasnadi** [comment]
The deterministic default is now 1500bbl/d for oilfield and 744bbl/d for gasfield. The high range is 10000, so it should be ok.
