### ISSUE TITLE
Realizations for lognormal distribution not bounded by min/max

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#120]
On the _Active Field_ sheet, the realizations that allow different distributions to be chosen all bound the possible result by the "low range" and "high range" except lognormal. Should add the bounds to the lognormal logic.

**Comment by smasnadi** [comment]
No, lognormal does not need a low/high range.

**Comment by qlangfitt** [comment]
Ah yes, that makes sense since you wouldn't want to bound out the high emitters. Thanks for taking a critical look at all of these rather than just implementing the suggested changes since I'll be the first to admit some of these error reports are probably not errors at all, but misinterpretation on my part.
