### ISSUE TITLE
Petroleum isothermal compressibility equation typo

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#121]
On the _Flow Sheet_ the petroleum isothermal compresibility (row 35) should square the absolute temperature at the end of the equation (as in Eqn 5.6). Also, the documentation and model both have the wrong order or magnitude for a4, based on what I could find online (a4 is listed as -9.23e-3, but should be -9.23e-8). Source: https://petrowiki.org/File:Vol1_Page_320_Image_0001.png

**Comment by smasnadi** [comment]
Adam: I cannot locate the original equation (eq. 5.6) that CARB is referring to.

**Comment by qlangfitt** [comment]
Perhaps the equation numbers have changed or this section has been removed, but here's a screenshot of the equation from the latest version of the documentation I have (20190329). It is (or was) in the section: II Technical Documentation->Flow sheet->Computing properties of flows->Properties of phases->Oil formation volume factor

![Equation 5-6](https://user-images.githubusercontent.com/47186327/57147384-4c995400-6d7c-11e9-9674-96fcc8d742be.png)

**Comment by smasnadi** [comment]
Thank you for the equation. 
I fixed the OPGEE equation. 
Adam: please check the sent petrowiki link above.

**Comment by qlangfitt** [comment]
The squaring has been fixed, but a4 remains as 10^-3. Not sure if that was just not addressed yet or if the petrowiki link was determined to be wrong. I was originally investigating this because the values the equation was spitting out seemed to be wrong, and with the 10^-8 magnitude seemed more reasonable.

**Comment by arbrandt** [comment]
Fixed to align with Al-Malhoun parameter in Petrowiki link, set to 10^(-8) magnitude as noted by qlangfitt.
