### ISSUE TITLE
Mine gas flaring and offgas rate forced to 0

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#124]
On the _Bitumen Mining_ sheet, the mine gas flaring and offgas rates will always be 0 because the binary on/off for integrated and non-integrated oil sands are mulitplied by one another. Should instead add those. 

=FOR* Oil_prod*(Oil_sands_mine_int_01+Oil_sands_mine_nonint_01)      
=VOR* Oil_prod*(Oil_sands_mine_int_01+Oil_sands_mine_nonint_01). The units for mine offgas rate should be scf/d, not scf/bbl.

**Comment by JSRuthe** [comment]
Fixed according to Quinn's suggestions. See commit history
