### ISSUE TITLE
Disagreements between documentation and upgrading data table

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#126]
On the _Heavy Oil Upgrading_ sheet, the Upgrading Data Table has a couple of inconsistencies with Table 7.32 in the documentation. Perhaps the numbers in the model are what we want to go with, but I think the two sources should agree. 

- Delayed coking, fraction of PG flared, 0.025->0.05. 
- Delayed coking, SCO/bitumen ratio, 0.904->0.834. 
- Hydroconversion, fraction of PG flared, 0.025->0.01. 
- Hydroconversion, SCO/bitumen ratio, 0.155->1.02. 
- Hydroconversion and fluid coking, SCO bitumen ratio, 0.99->0.865.

**Comment by smasnadi** [comment]
The documentation factors are fixed based on OPGEE excel sheet.
