### ISSUE TITLE
Heavy oil upgrading cogen NG adjustments

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#127]
On the _Heavy Oil Upgrading_ sheet, when cogen is turned on/off in the secondary inputs, the natural gas uses of the rest of the cogen model do not adjust to account for the heat captured and used from the cogen. This seems to hinge on the fact that much of the data table specifying fuel use intensities is static. I think this could be fixed by subtracting the heat supplied to the upgrader by the cogen (D124) from the heat supplied by NG (G123). That would carry back through to the sum of the NG imported.

**Comment by arbrandt** [comment]
Fixed the logic. Now the gas to heat is credited toward the direct gas consumption. If the cogenerated heat exceeds the demand for gas, the minimum gas demand in G124 (GAS TO HEAT) is now 0. This ensures that there is not negative demand for gas to heat if large amounts of cogen are used.
