### ISSUE TITLE
Heavy oil upgrading flared process gas unaccounted for

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#128]
On the _Heavy Oil Upgrading_ sheet, it appears that flared process gas never gets accounted for in the GHG summary, since the flared gas cell (K115) doesn't have any dependents. Unless this is rolled into the flaring-to-oil ratio input implicitly.

**Comment by smasnadi** [comment]
Adam: can we assume that the process gas flared from Heavy Oil Upgrading is already implicitly accounted in FOR?

**Comment by arbrandt** [comment]
Added the process gas flaring to the upgrader gas consumed term. Do not want to roll this into the default flaring logic, as this would add a lot of complexity.
