### ISSUE TITLE
Unit mismatches on steam generation

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#129]
On the Steam Generation sheet there are various spots where the units calculated in the equation don't match the units listed. 

- Horsepower to pressurize incoming water (M75): This is based on eq. 7.35, however, that equation requires the flow rate to be in bbl/d, and the flowrate here is in lbm/d. Need to convert lbm to bbl.
- Air In Flow Rate (F99): The liquid fuel (crude) portion calculates in g/d, while the gaseous fuel calculates in kg/d.
- Liquid Fuel O2 Consumption (M119): Includes kg/lb conversion, when unnecessary. The fuel composition is already in mol/kg fuel.
- OTSG available enthalpy per unit kg of fuel - liquid fuel (M125): Subtracts loss in btu/lbm fuel from enthalpy in MJ/kg fuel. Need a unit conversion to MJ/kg.
- OTSG Combustion - LHV or enthalpies (G151, K151:M151): This equation has the wrong units for calculations with liquid fuel. Need to remove $D150*1000 from the end. This problem persists across the table for liquid fuels, including all of the exhaust compositions. (only affects row 151, columns G, K,L,M, do not remove factors from the rows for gasous fuels).
- GT+HRSG - Produced Water In Pressure (P194): Needs to be converted from psi to bar ('=CONVERT(Pressure_RecycledProdH2Oinlet_steamgen,"psi","Pa")/100000)
- STSG - Produced Water In Pressure (D247): Needs to be converted from psi to bar ('=CONVERT(Pressure_RecycledProdH2Oinlet_steamgen,"psi","Pa")/100000)
- Power requirements for air blowers and Solar HTF pumping (M257:M259): 24 hr/d factor should be removed. Units already per day.
- Results - Energy Use - Crude Oil (E269): Calculates in MJ/d, but needs to be converted to mmbtu/d.

**Comment by smasnadi** [comment]
Yulia: please address

**Comment by yuliachen** [comment]
I have addressed all of the issues except the second to last one. The 24 hr/d factor is used to convert the driver term in btu/bhp-hr

**Comment by qlangfitt** [comment]
@yuliachen  I agree, the second to last bullet was already correct and I should not have reported an error.
