### ISSUE TITLE
Total steam gen NG use includes fuel in to OTSG no matter fuel type selection

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#134]
On the _Steam Generation_ sheet, in the results section, the natural gas use (B269) includes the fuel into the OTSG, even though that fuel can be crude. In the case that it is crude, that energy is double-counted. Should use an IF statement to conditionally remove G95 from the equation in the case that the OTSG fuel is liquid.

**Comment by smasnadi** [comment]
Fixed!
