### ISSUE TITLE
Effective fractional loss rate only defined on VRU compressor

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#137]
On the _VRU Compressor_ sheet, there is an "effective fractional loss rate" (M70) to cap the loss rate at 95%. Why include that for the VRU? Or the converse: why not include it for the other compressors?

**Comment by JSRuthe** [comment]
@arbrandt  can you look into this?

**Comment by arbrandt** [comment]
VRU compressors can handle small volumes of gas compared to other compressors. In some cases, pulling a realization for fugitives from the compressor resulted in more emissions than were entering the compressor. I have added this logic to all compressors now to ensure that regardless of the site-level draw of compressor loss rate, we do not emit over 95% of the gas entering the compressor.
