### ISSUE TITLE
Deterministic defaults and mean values of probability distributions

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#138]
EDIT: I think this can go on the back-burner for now as we're more concerned with getting the model working right for single runs in the short term, but let's revisit this at a later date.

I have been examining the uncertainty runs and have found that many fields have central tendencies that are much different than the results under the deterministic default. It's pretty clear why that is happening - the deterministic default and mean values on the Active Field sheet (columns N and O) are very different for some inputs. In some cases this is because the deterministic default responds to some of the other inputs where the mean does not, and in other cases the equations to calculate each differ. While I don't think that the mean and deterministic default necessarily have to be the same for every input, the difference is severe enough that for some fields the CI using deterministic defaults is not even included in the range of the CIs from a set of 10 uncertainty runs. For some inputs, the range limitations (low range, high range) can even exclude the mean (e.g., number of producing wells) when the mean is based on a user input for another variable (which is very high or low) and the low/high are based on the low/high of that other variable. I think it would be helpful to revisit the deterministic default, mean, low range, and high range to ensure they are compatible.

**Comment by arbrandt** [comment]
Fixed. There were misalignments because Mohammad re-ran many of the defaults and ranges for the Masnadi 2018 Science paper. I have gone through the documentation and aligned: (1) the deterministic defaults, (2) the mean of the uncertainty columns, (3) the default column 0. These should all now be aligned.
