### ISSUE TITLE
Exploration diesel use based only on oil production

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#140]
On the _Exploration_ sheet, the diesel use (F32) is based on only oil production. If dry gas field or even a field with a lot of associated gas, could be inaccurate. The fractional energy consumption is based on total oil+gas energy, but then only oil energy is used as a multiplier. To fix, need to convert oil produced and gas produced into energy content produced and multiply that by M20. That said, it is a tiny part of total emissions so it has little practical impact.

**Comment by arbrandt** [comment]
Fixed and closed. Exploration is now based on a cumulative production of oil and gas.
