### ISSUE TITLE
Stream 172 represents two different flows in flow diagram

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#144]
On the _Flow Sheet_, the stream number 172 is used for both the fuel gas consumed for onsite electricity generation and for the fuel gas consumed for LNG liquefaction. Stream 172 (referring to the electricity gen stream) is also included on the flow sheet for the fuel gas consumed process, but it is not on the _Fuel Gas Consumed_ sheet. Recommend to give the fuel gas for onsite electricity gen a new number and to add to the fuel gas consumed sheet. The way it is now, the GHG emissions from consuming that fuel is included in the model since the fuel gas use for electricity gen is already recorded on the _Energy Summary_ sheet (H54), however, the gas exported (stream 45) is not reduced by the fuel gas consumed for electricity gen since it is missing from _Fuel Gas Consumed_.

**Comment by smasnadi** [comment]
I numbered "Fuel gas - Onsite   electricity generation" as stream 174 and added it to _Fuel Gas _Consumed_ sheet. But Stream 174 is not wired to right cells yet and the gas export (stream 45) should be reduced by the fuel gas consumed for elec.

**Comment by arbrandt** [comment]
Stream 174 is now wired into the Fuel gas consumed sheet. This will make that amount of gas removed from the potential export stream.
