### ISSUE TITLE
Error check for steam gen technology can fail

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#147]
On the _Steam Generation_ sheet, the percentage of each type of steam generation technology is governed by the inputs Fraction_steam_cogen and the fraction_steam_solar. The fraction from OTSG is then calculated as 1-cogen-solar. If the fraction of cogen and solar add up to exceed 1, the fraction of OTSG will go negative to compensate and the error check in L61 will add up all contributions and still get 1. One option to correct this is to change Steam Generation L61 to: =IF(ABS(M59)+M60+M61=1,"OK","ERROR")

**Comment by smasnadi** [comment]
Fixed! Thank you.
