### ISSUE TITLE
OPGEE test fields

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#148]
Oil sands test fields (45 - 48) are throwing errors

Test field 32 and 87 are very different from previous versions

This is likely due to fixes made in the last few days

**Comment by qlangfitt** [comment]
I looked at field 32 and the reason for the big change was that previously there was no default FOR, so if left blank the flaring module would be turned off. That was fixed so that there is now a default and that increased emissions for field 32 substantially.
