### ISSUE TITLE
Z factor function causes OPGEE to stall / slow down

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#149]
OPGEE speed is slowed down significantly by the z factor function. 

If OPGEE is run in uncertainty mode significant time (close to 1 min) is spent filling in OPGEE defaults.

To test where in this process OPGEE is slowed down I "aborted" several times and checked the debugger to see where OPGEE had been busy running. Each time OPGEE was busy in the z factor function.

**Comment by qlangfitt** [comment]
I have experienced this as well. It seems to cause z-factors to sometimes not calculate for compressor sheets, resulting in errors. Whenever I go back and double-click in one of those cells and hit enter the function calculates fine.

**Comment by smasnadi** [comment]
If a separate cell calculates the z-factor, then there is less chance to get error.

**Comment by JSRuthe** [comment]
I am reopening this issue because I think that the z factor is still stalling OPGEE. While OPGEE is running I pause computations and 9 times out of 10 it opens to the z factor calculator

**Comment by arbrandt** [comment]
I think this was not the issue. Speed up obtained by better handling of loops. I think it is pausing on z-factor calculation because it for some reason executes a stop loop when going to the UDF.
