### ISSUE TITLE
Crude oil dewatering NG use in kWh/d

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#150]
On the _Crude Oil Dewatering_ sheet, the natural gas use in the outputs is directly copied from a calculation in kWh/d. This is causing extremely high contributions from the heater/treater on the Energy Summary. Need to change the Dehydration heater NG consumption equation on _Crude Oil Dewatering_ (M43) to: =IF(Type_heater_treater="Gas",(M42/Eta_heater_treater_gas),0)

Also need to change the unit next to it (N43) to mmbtu/d.

**Comment by arbrandt** [comment]
Fixed and also checked the electric efficiency equation below.
