### ISSUE TITLE
Gas transmission compressors unresponsive to system boundary selection

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#153]
Gas transmission compressors need logic to turn off combustion emissions when the field system boundary is selected. Probably easiest to add the logic on the Transmission Compressor sheet, in the outputs section, unless there is a different standard practice.

**Comment by smasnadi** [comment]
I modified cells B74 and I74 of Transmission Compressor sheet. 

Quinn: please double check.

**Comment by qlangfitt** [comment]
It looks good. Might be more consistent with the rest of the model if it instead referenced the ON/OFF status indicator (N1), but in practice this will perform the exact same way.
