### ISSUE TITLE
Petcoke transport energy use not brought into Energy Summary

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#154]
The output energy uses on the Petcoke Transport sheet have no dependent cells, and a secondary examination of the Energy Summary sheet and Active Field sheet confirms that the petcoke transport process is not accounted for in the CI calculation of OPGEE.

**Comment by smasnadi** [comment]
I agree. Because there is no row for Petcoke Transport in Energy Summary sheet, I added the corresponding fuel consumptions to the Crude Oil Transport row (row 48 of Energy Summary sheet). In anyways, the energy consumption amounts for petcoke transportation is negligible for most cases.
