### ISSUE TITLE
Heavy oil upgrading mass balance not conserved

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#155]
When running some of the oil sands fields (e.g., Suncor, Field 91; Jackpine/Scotford, Field 93) I was getting mass balance errors on crude oil. I traced it back to the lack of a mass balance on the Heavy Oil Upgrading sheet. The process gas exports, process gas flared, and SCO output are all set independently based on the upgrading data table. The lack of mass balance was just enough to trigger an error in a few cases. It's possible that this is not easily fixed and is just a bit of rounding error or other imperfection in the interplay between the values in each column of the data table. If that's the case, I think it's okay to keep the current approach, but perhaps the crude oil mass balance should be given a higher tolerance for oil sands on the error checking in recognition of the fact that relatively larger deviation from mass balance in that case doesn't necessarily indicate that some kind of incompatible inputs were used.

**Comment by smasnadi** [comment]
I agree. All goes back to that table in the Heavy Oil Upgrading sheet. I modified cell LM8 of Flow Sheet page to address the issue.
