### ISSUE TITLE
Claus unit incinerator fuel use high for low production fields

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#156]
On the _Acid Gas Removal_ sheet, the Claus Unit "total incinerator fuel use" (L312) is based on a fitted equation from the documentation (Figure 7.52b - see below). That equation predicts fuel use in kg/d based only on the mol fraction of H2S in the gas. It seems unlikely that the fuel use would be independent of the flow rate of gas, and indeed this causes a problem for fields with very low production. Some of the fields in the "[LCFS Inputs Spreadsheet for Crude Lookup Table](https://www.arb.ca.gov/fuels/lcfs/crude-oil/crude-oil.htm)" have very low production and the fuel use of the Claus Process dominates the overall GHG emissions from the entire field. Can the fuel use rate be revisited to see if perhaps there's a way to scale to the volume of gas being processed?

![image](https://user-images.githubusercontent.com/47186327/59637583-066d3980-910b-11e9-98a6-4a93d82345da.png)

**Comment by smasnadi** [comment]
I agree. We need to re-run AspenHYSYS to include the effect of gas volumetric flow rate, etc. This is not a major part of AGR unit, and I suggest to disable it for now until we get access to the software again and re-run it.

**Comment by qlangfitt** [comment]
I'm not even sure it anything needs to be re-run in AspenHYSYS. I assume that a set flow rate of liquid sulfur production or gas throughput was used when developing the correlation, just like the other correlations (for condensers, heaters, and waste heat exchanger). If we have any left over documentation of what either flow rate was (is the gas flowrate 100 kmole/hr as stated on the AGR sheet?) then I would think we could just scale by that. In order words, wouldn't it work to just multiply the incinerator fuel gas consumption by 'Acid Gas Removal'!L245?

**Comment by smasnadi** [comment]
Cell C360 (Total incinerator fuel use) is scaled to account for the total gas fed to the Claus unit, as suggested. See Scaled   total incinerator fuel use (cell C361).
