### ISSUE TITLE
Crude oil transport unresponsive to system boundary selection

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#159]
Crude oil transport on/off label on the Flow Sheet is simply set to "ON" (AW312). Should have logic to turn off if oil system boundary is "field." After fixing that, also need to add logic to the crude oil transport sheet to zero out the fuel use when crude oil transport is turned off. Because of logic on the GHG Summary sheet, emissions from crude oil transport are correctly not added to GHG emissions results when boundary is field, but it still shows up in the Energy Summary and the energy use on the Results sheet.

**Comment by qlangfitt** [comment]
In the process of fixing this, I think a new issue was introduced. In the Flows Out table on _Crude Oil Transport_, stream 14 ("Transported crude oil at refinery) is zeroed out if the process is turned off. That's unnecessary since the energy use in the Outputs already zeroes out if the process is turned off, and it causes a mass balance problem when the oil system boundary is set to Field. Removing the IF logic from column J should fix the problem.

**Comment by arbrandt** [comment]
Fixed. If logic removed in column J, so that mass still passes through, even if the crude oil transport energy is zeroed out. This prevents a mass balance issue from arising.
