### ISSUE TITLE
Negative fuel use for steam gen on Canadian oil sands fields (due to produced water defaults)

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#160]
On the Steam Generation sheet, I'm getting negative values for fuel use for the OTSG in some cases (the one described here is Cold Lake, field 83). The problem is the model is calculating higher enthalpy in the produced water going into the steam gen system than in the mixed steam coming out. I found that if I slightly lowered the temperature of recycled produced water at the inlet (secondary inputs: Temperature_RecycledProdH2Oinlet_steamgen) from 340 F to 327 F, the situation resolved. However, it didn't seem to do so sensibly as the change was dramatic between 328 F and 327 F. The effect on the overall CI was also huge, going from 9.7 to 18.6 gCO2eq/MJ. 

I dug into why and it turns out that the defaults for the produced water properties for Canadian oil sands projects (340 F and 100 psia) put it in the steam region on the water phase diagram. The dramatic change in calculated enthalpy was from phase change. Is the recycled produced water supposed to be in the steam phase or is it supposed to be liquid for these oil sands projects? Please look into this as the oil sands fields are passing negative fuel uses through to the results, which clearly is not correct. I assume it's a mistake since if the produced water were already steam it wouldn't need to be run through steam generation. Perhaps just slightly lowering the temperature would solve the problem, so that the model would still be calculating the amount of latent heat added to induce phase change.

**Comment by qlangfitt** [comment]
I just looked back at OPGEE 2.0c and saw that it uses similar temperatures but a pressure of 200 psia. That solution would also work (increasing pressure rather than decreasing temperature to keep the water in liquid phase).

**Comment by arbrandt** [comment]
Fixed. Changed back produced water inlet pressure to 200 psi, which had changed to 100 psi for some reason. This resulted in steam being produced instead of water. Not clear why default inlet pressure had been changed from 200 psi to 100 psi. Don't want to be producing back steam, as the point of SAGD is to drop the enthalpy of vaporization into the reservoir, so producing steam would be highly inefficient.
