### ISSUE TITLE
Water reinjection vs water flooding

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#161]
I'm currently comparing results computed by OPGEE 2.0c to OPGEE 3.0 and noticed a discrepancy for water injection. In 2.0c, water reinjection means that some or all of the produced water is reinjected, and the calculation is done independent of the WIR (it is based on the amount of produced water and a user input fraction of produced water reinjected). In OPGEE 3.0, water reinjection and water flooding seem to be treated as essentially the same thing - no matter which of the two is turned on, the amount of water injected is based only on the WIR (in fact, the input for fraction of produced water reinjected has no effect on the results). This discrepancy is causing major problems for a couple of the fields I'm testing that have a low amount of reinjected produced water vs. the default WIR that is filling in that blank input. I think the issue is more the approach used in OPGEE 3.0.

**Comment by smasnadi** [comment]
I agree. I tracked all cells of Water Injection sheet and seems that everything depends on cell M39, which is now modified to use frac of water reinjec for water reinjec and WIR for water flooding. 

Quinn: Please double-check.

**Comment by qlangfitt** [comment]
Looks good to me.
