### ISSUE TITLE
Ethane to petrochemical not included in effective output energy stream

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#162]
The ethane removed from the NGL stream and sent to stream 89 (ethane to petrochemical) on the Demethanizer sheet, doesn't appear to get factored into the model's CI calculations. Shouldn't this be counted as part of the NGL product on the Energy Summary sheet?

**Comment by smasnadi** [comment]
Good eyes! I added an additional term in cell E77 of Energy summary sheet
