### ISSUE TITLE
No debit for fuel cycle of imported NG for gas flooding

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#164]
In OPGEE 2.0, in the Energy Consumption sheet's "Energy Exports/Imports by Fuel Type" (Table 3; Cell E37), the gas used for gas flooding is included in the required imports. However, in OPGEE 3.0 (Energy Summary Table 3; F75), only the gas tracked in "Fuel Gas Consumed" is factored in - the gas used for flooding is not included (the debits do change slightly when changing the gas flooding injection ratio, but this is due to higher fuel use by the gas flood compressor and higher fugitives). There is a stream (stream 78) used for the mass balance to account for natural gas imported for gas flooding, but then it doesn't appear that the fuel cycle emissions for that imported gas is included anywhere in the model. This results in lower debits for natural gas, and therefore, a lower CI. An example of this is Marun.

**Comment by smasnadi** [comment]
I agree, and added flooding stream to cell F75. Please double check and confirm. This would affect the results for NG considerably.

**Comment by qlangfitt** [comment]
Not sure if you were asking me to confirm or someone at Stanford, but I just checked and it looks right to me.
