### ISSUE TITLE
Midway Sunset run returns 61.8 g/MJ

### ISSUE THREAD

**Issue by dxgordon** [arbrandt/OPGEE#166]
There seems to be a problem running Midway Sunset.
I just downloaded and ran field 67 (Midway Sunset without solar steam) and got 61.8 g/MJ.  This seems much too high. There's also a #VALUE! in surface processing total energy result.

Note that in a prior Midway Sunset run (April version of OPGEE 3.0a BETA) returned 34 g/MJ. 

Can you try to diagnose the problem? 
I think the result should be somewhere in between 34-61 g/MJ.

**Comment by smasnadi** [comment]
It is now 57.2 CO2/MJ

Most of new additional emission contribution is due to production/extraction VFF because of the new OPGEE Fugitive model (The field has lots of production wells). 

Jeff is working on it to make sure that the FVV estimate is reasonable.

**Comment by dxgordon** [comment]
Please keep us posted Mohammad. 
Right now we‘ve kept Midway sunset OPGEE at 39.7 g/MJ. But I too think that it’s upstream GHGs could be higher as you are finding. 

Thanks!
Debbie

--Debbie Gordon
202-957-8849
