### ISSUE TITLE
Demethanizer not turned on for gas processing path 6

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#168]
Demethanizer sheet (M197) has an error in which it is turned on for 6 and turned off for 7 when using the textbook method. Those should be switched. There is another error in the ON/OFF tag of the demethanizer on the flow sheet (DI110). It only turns on for paths 4 and 5, but it should also turn on for path 7 (assuming the description on the inputs sheet is correct).

**Comment by smasnadi** [comment]
Fixed!
