### ISSUE TITLE
Venting emissions confusion

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#169]
The venting to oil ratio (VOR) on the Inputs sheet is not the ratio of total vented gas to produced oil as OPGEE calculates it. The VOR is used on the _Venting_ sheet to calculate purposeful venting (stream  252) based on a fraction of the gas to gathering (stream 31). However, other venting is calculated elsewhere in the model. Stream 255, 256, 279, and 286 are classified as venting emissions on the _Venting & Fugitives 3.0_ sheet, so venting emissions are routinely higher than the VOR would suggest. This is potentially confusing. If this is how the model was intended to operate, I think the VOR name should be tweaked slightly, or better explained in the documentation, to reflect that the VOR is the portion of gas vented in the separation and gathering processes or in all other undefined processes (I'm not sure myself which of these is accurate).

**Comment by smasnadi** [comment]
I agree. For now changed the input sheet VOR to "Venting-to-oil ratio (purposeful)". 

OPGEE documentation to be edited.

**Comment by arbrandt** [comment]
This is a good solution. VOR was meant to represent the purposeful bulk venting of gas as a substitute for flaring of gas. Small vents from particular process units.
