### ISSUE TITLE
When gas processing off, venting process also off

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#170]
When the associated gas processing path is set to 1 (no processing), the Venting process is turned off on the flow sheet (BF110). If the user inputs a VOR, it seems like it should be honored since there are places for venting to occur that are outside of the gas processing system. Additionally, the VOR must be >1 for the process to be turned on, but I don't see any justification for that. Shouldn't it be >0 to be on? This is somewhat related to issue 169, trying to better understand what the VOR is supposed to represent physically.

**Comment by smasnadi** [comment]
I changed the condition to:
=IF(Gas_processing_path>1,"ON",IF(VOR<>0,"ON","OFF"))
