### ISSUE TITLE
Issues for 9000 global oilfields run

### ISSUE THREAD

**Issue by smasnadi** [arbrandt/OPGEE#172]
**Note: All changes are highlighted in the attached OPGEE version (zip file).**

**Z factor:** the z factor function works well. One frequent problem is that when the zfactor function is in IF(), it oddly does not compute and the output of that cell becomes "NA". This is the source of problem for many errors. And if you select that cell and enter manually, it suddenly compute the zfactor! I suggest to compute the zfactor in a separate cell and then use that cell in IF() function. E.g. see the attached file Demethanizer sheet cell R149 and L149. The same can be done for other process units (e.g. re-injection sheets)

**Zero GOR issue:** When GOR is very low or zero (e.g. Canadian oilsands), there won't be any gas to VUR compressor (cell E28 of VUR comp sheet) but OPGEE accounts for fugitives from VUR (cell K28) and this leads to negative gas output from VUR (cell J28) causing error. I put an IF() function to address this (cell J28). The same can be done for other process units.

**Gas injection issue:** When gas injection is on and gas flooding is off, if the user does not determine the fraction of gas that is re-injected, OPGEE default will be 0. This means that no gas is re-injected. I suggest to put IF() function. See Active Field cell K104. 

**Number of water injection wells:** First, should not we call it as number of injection wells? What if gas is injected? Second, setting this parameter as 0 causes an error because this parameter is in denominator of some equations. I suggest to add a micro (at the beginning of code) that if this is the case, change it to 1 to avoid any error.  

**Fixing associated gas composition issue:** If you run a field with incomplete gas compositions, the cells compositions are not set proportionally to the default values. Lines 105 and 106 of macro should be deleted and replaced by lines 332-403. 

**Negative duty:** For few cases I saw negative duties calculated for Aspen Hysys models. Please follow up with me later to resolve this. 

**Odd issue:** Why active field final GHG result (gCO2eq/MJ) is NOT the same as Result sheet GHG result? 

**Low oil production issue:** When the field has many wells but the oil production is super low (let's say 1bbl/d), the result GHG becomes super high (>1000 CO2/MJ) due to fugitives. We need to set a cap for this issue.

**Negative zfactor:** For few fields the zfactor became negative that causes series of errors. This is most likely due to the rough correlations that are used in the zfactor macro. I suggest to set a code that if zfactor is negative, assume it as 1 (ideal gas). E.g., see Flow Sheet cell AD70. It can be expanded to other cells. 

[OPGEE_3.0a_BETA.xlsm.zip](https://github.com/arbrandt/OPGEE/files/3449464/OPGEE_3.0a_BETA.xlsm.zip)

**Comment by smasnadi** [comment]
I fixed the zfactor, zero GOR, gas injection, associated gas composition, negative zfactor and loaded a new version.

I checked the macro and could not understand why the active field GHG final result is different than final result in Results and Uncert. sheets!

**Comment by JSRuthe** [comment]
Closing this issue. Unclear which issues are still relevent to current OPGEE version (1 yr later) and @smasnadi will be running 9000 oil fields again
