### ISSUE TITLE
No defaults for some LNG transport secondary inputs

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#174]
On the Secondary Inputs sheet, for LNG transport the fraction of gas transported by each mode and the transport distance are both set to all 0s. I think there should be default assumptions in those cells since we typically don't require the user to change secondary inputs unless they want additional control. The way it is now, LNG transport will be excluded completely unless secondary inputs are user adjusted.

**Comment by smasnadi** [comment]
I added an assumption in the secondary sheet.
