### ISSUE TITLE
LNG transport sheet various equations pulling from wrong cells

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#175]
On the LNG transport sheet, there are a few places where the referenced cells in equations are incorrect including:
- Energy consumption (M86:M90): References the heaving value and specific gravity of oil, but should be for LNG.
- Energy production rate as crude oil (M99): This sheet is calculating energy to transport LNG, so this cell should be the total energy content of LNG, not crude oil. Should be easy to draw tonne/d from stream 86 and then convert to energy content.
- Outputs (row 108): All outputs cells have issues with the second two sets of secondary inputs in the SUMPRODUCT. They reference the wrong rows on the secondary inputs sheet. They should be 'Secondary inputs'!M564:M568,'Secondary inputs'!M558:M562.

**Comment by smasnadi** [comment]
- energy consumption: replaced by NG LHV, Density of water in lb/scf, and Sg_gas
- M99 fixed based on NG data
- Outputs fixed!
