### ISSUE TITLE
Gas transmission compressor and related issues

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#179]
There are two secondary inputs that determine the required compression ratio for the transmission compressors, (1) Pressure_after_boosting_separator and (2) Pressure_transmission_compressor_discharge. The required compression ratio is generally just the ratio of those inputs. The defaults for those inputs result in no need for transmission compressors at all, so the only way transmission compressors would be factored into OGPEE is for the user to change those secondary inputs. Would we really suspect that in the default scenario the gas will already have enough pressure to not require transmission compressors? This seems implausable as transmission compressors are typically needed at least every 100 miles or so.

Another issue is that when flaring is turned off, it interrupts the chain of equations that draw the pressures from the previous streams. On the Flaring sheet, the post-flare gas to vent (stream 30) should not bring the pressure to 0 if the process is turned off (L32). It should always pull from E32 regardless of the status of N1. 

Once this fix is implemented, I think an additional change can be made on the Gas Gathering sheet. The change should make it unnecessary to bring the pressure of the gathered gas (stream 34; cell L32) up to 1000 if there is no pressure from the post-vent gas to gathering (stream 31; cell E32). I assume that condition was added when someone observed the gas pressure going to 0 when the FOR was 0. Perhaps I'm wrong on this one and the condition actually is necessary to protect against something else.

Finally, I have questions about the overall approach for the transmission compressor calculations. The transmission compressor fuel use is calculated based on the pressures described above. However, once in the pipeline system, the pressure after the boosting separator seems irrelevant (unless this is supposed to be the pressure after each compressor station, in which case what does "Pressure_transmission_compressor_discharge" mean?). All subsequent compressors after the first will have to make up pressure losses from the piping (friction, maybe fugitive losses) not the bring the pressure up to pipeline pressure from the boosting separator pressure. The way the transmission compressor sheet is designed, it takes the fuel use for that first compressor and multiplies it by the number of compressors along the pipeline. OPGEE calculates friction pressure drops in pipes in many places, why not implement it here too for all subsequent compressors after the first? PetroWiki has a page that describes various methods of calculating pressure drop of natural gas in a pipeline (https://petrowiki.org/Pressure_drop_evaluation_along_pipelines). It seems reasonable to use one of these equation and simply assume a pipe diameter, use the length between compressors as Frequency_gas_transmission_compressors, and assume a straight pipeline.

**Comment by qlangfitt** [comment]
Might want to check out the following:
Di Lullo, G., Oni, A.O., Gemechu, E., Kumar, A., Developing a Greenhouse
Gas Life Cycle Assessment Framework for Natural Gas Transmission Pipelines, Journal of Natural Gas
Science & Engineering.

[https://doi.org/10.1016/j.jngse.2019.103136]()

Authors calculate emissions from a few specific gas transmission pipelines and compressor stations in Canada in a pretty involved analysis. Not suggesting we use the same approach, but just a reference to see if you end up in the same ballpark. I've also done some lit review on this topic looking at the NETL natural gas LCA and some textbooks that discuss typical transmission pressure drops between stations. The following a little snippet from the vetting report I'm compiling to track my efforts, in case it's useful to you:

![image](https://user-images.githubusercontent.com/47186327/72115988-a71c8400-32fd-11ea-8eef-21488178593d.png)
![image](https://user-images.githubusercontent.com/47186327/72115996-b1d71900-32fd-11ea-9659-67fb937c3756.png)

**Comment by arbrandt** [comment]
Issue #179 cleared by adding computations from Di Lullo 2020. Now it computes the pressure drop between stations and the number of stations required.
