### ISSUE TITLE
Compressor slip and tank fugitives mix field level data with sample data

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#183]
On the _VF method - Component_ sheet, the compressor methane slip "random draw" (cell I29) grabs the methane emissions based on the field input data, but then divides those emissions by the number of wells in the "sample set" (cell E14). Same issue for crude and condensate storage tank venting (cell I30).

**Comment by JSRuthe** [comment]
This issue was fixed with commits made on November 15
