### ISSUE TITLE
Methane slip from compression seems to already be in compressor combustion emission factor

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#184]
A new fugitives stream for slip from compression (stream 295) was added. This stream accounts for unburned methane in the combustion product of the separator compressor(s). A couple of possible issues/suggestions:

- From what I can tell, the unburned methane is already factored into the CO2e for combustion emissions.

- If this is a valid thing to add, why only do it for the separation compressor when there are many other compressors in the model?

- The stream name could be improved for clarity (to specify which compressors).

**Comment by JSRuthe** [comment]
Hi Quinn, this is a really good point. 

Although unburned methane is already factored into the CO2e emissions factor for combustion in natural gas engines, the unburned methane wasn't factored into our "total methane loss rate" calculation. This was a workaround for me to address this in our methane fugitives paper.

However, given that this workaround was to address a specific issue in our paper, I have chosen to remove this functionality in the "official" Github version of OPGEE.

See the most recent commit (Jan 27, 2020)
