### ISSUE TITLE
Issues resulting from suppression of component VBA calcs for site fugitives method

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#186]
An update was recently made to suppress the component fugitives VBA calculations when analyzing using the site method. This seems to cause issues for some fields, since some of the component method data is still used to fill in gaps in the site method (e.g., streams in the 290s). For most fields, this doesn't matter much because VFF is dominated by the site-calculated results, but for other fields, those borrowed component-method pieces are a significant portion of the overall. This can be especially true when the component calculations are skipped entirely, since those component-method processes aren't even calculated accurately for the field in that case. Unfortunately, even though it increases computation time, I don't think we should skip the component VBA calcs when using the site method.

**Comment by JSRuthe** [comment]
This issue has not surfaced in recent testing. Will close unless this comes up again
