### ISSUE TITLE
Mass balance error in uncertainty mode - Both site level and component level

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#191]
Mass balance issues arise for NGLs and gas components when OPGEE is in uncertainty mode (uncertainty runs > 1). There are no mass balance issues when OPGEE is in deterministic mode

**Comment by JSRuthe** [comment]
Mass balance error appears to be related to Glycol Dehydrator, AGR, gas gathering, transmission compressors.

**Comment by JSRuthe** [comment]
@arbrandt @qlangfitt @smasnadi  
I think I've figured out why we have mass balance issues in uncertainty mode. This is really interesting.

First, we are getting mass balance errors because on sheets that reference random draws in the fugitives calculator, the cells are being updated (in manual update mode) in the wrong order. Take the transmission compressor for example. Here gas to distribution (stream 49) is calculated as the difference between gas exported (stream 45) and fugitives (stream 261). If the cells are updated in the wrong order, then stream 49 is calculated using stream 45 and 261 from previous "updates".

I did some research on excel's order of operations. For moderately complex worksheets, excel is able to determine the correct order of calulations and form "dependency trees". See here: http://www.decisionmodels.com/calcsecretsc.htm

However, for extremely complicated worksheets (like ours), excel basically "gives up" and will calculated from left to right and top to bottom. See here: https://excelribbon.tips.net/T011653_Forcing_Stubborn_Recalculation.html

I did some experimenting and proved that on our worksheet excel is calculating based on where the cell is located in the workbook. In the attached image I show how the value of the **exact same formula** is different depending on where the formula is located.

![mass balance issue](https://user-images.githubusercontent.com/42356585/77010966-745fbf00-6930-11ea-9112-cc5429736305.jpg)

**MY SUGGESTION**

Formulas that need to be updated first need to go in the top left hand corner of the worksheet. This includes the fugitives "draw" and the values of streams 45 and 169 (fuel gas stream). See the image below. If we do this the mass balance issue disappears!

![mass balance issue_2](https://user-images.githubusercontent.com/42356585/77011269-17b0d400-6931-11ea-82a5-27ddb95636ab.jpg)

**Comment by JSRuthe** [comment]
I will discuss this issue with Adam before pushing a commit. This will involve moderate redesign of many sheets. Please post a comment if you have any thoughts

**Comment by qlangfitt** [comment]
Wow, I never knew this. Great job digging that up - it must have been very perplexing. 

Let me make sure I have this straight. You are essentially proposing to pre-calculate the values in the cells on the upper left so they calculate first and then the cell that is used by the model just pulls directly from that? I think that sounds like a good solution and the least amount of work over resdesigning whole sheets.

**Comment by arbrandt** [comment]
Closing this one because we have the newer issue #262 that contains the remaining effect after Jeff's fixes
