### ISSUE TITLE
No deterministic default for liquids unloading or tank flashing fugitives

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#192]
On the VF method - Component sheet, the liquids unloading and tank flashing calculations (rows 68-76) only have randomized calculations with no provision for a deterministic default. Please add a deterministic default.

**Comment by qlangfitt** [comment]
Also, the mean value for tank flashing (VF method - Component cell H162) is only the mean of a subset of the smallest leaks. I assume that was not intentional and it should be expanded to the mean of the full distribution before being implemented as the deterministic default?

In addition, for tank flashing, are those randomized values (row 162) in kg/day or kg/bbl? There's disagreement between the units tags.

Finally, there's a note above the tank flashing summary (row 73) saying to "check for emissions controls". Doesn't look like that's done, so I gather that the model is treating all tank emissions as uncontrolled?

**Comment by qlangfitt** [comment]
Why divide the tank flashing emissions by the number of production wells? From what I can tell, the leak measurements are in kg/bbl and this figure doesn't appear to be multiplied by the number of wells anywhere else. It feeds directly to the crude oil storage sheet and then into the flow table.

**Comment by JSRuthe** [comment]
Good catch Quinn. I am fixing this right now. Will push and close this issue once I've un OPGEE on all test fields

**Comment by JSRuthe** [comment]
For select fields it looks like deterministic defaults are working for fugitives model
