### ISSUE TITLE
Deterministic defaults wrong for oil fields (but not gas fields)

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#193]
On the VF method - Component sheet, the deterministic default emissions factor is drawn by referencing an offset (Column O, Rows 18-36), however, the offsets are all off by 1 for oil fields (GOR<100,000). The first (Cell O18) should output 18 instead of 17 for oil fields and so on down the line. This has a major impact on results.

**Comment by qlangfitt** [comment]
Also, was the GOR cutoff supposed to be 100,000 or was it intended to be 10,000? It seems like elsewhere in the model 10,000 is used.

**Comment by smasnadi** [comment]
You are completely right! I added 1 to all corresponding cells in column O, and also put the cutoff based on GOR of 10,000 (instead of 100,000).

Jeff: Just to notify you. Please double check this.

**Comment by qlangfitt** [comment]
Doesn't look like a revision was committed for this issue.

**Comment by smasnadi** [comment]
Please re-check it.

**Comment by qlangfitt** [comment]
Looks good! I do want @JSRuthe to weigh in on whether the GOR cutoff should be 100,000 or 10,000 though. I know I suggested to change it down to 10,000, but perhaps the data he used was only valid above 100,000 or something.

**Comment by smasnadi** [comment]
Different references set different cutoffs for gas fields. One EPA says 100,000 GOR. We chose 10,000 for the global Science paper and the same standard is followed for the global gas project which is in progress.

**Comment by JSRuthe** [comment]
Mohammad is correct. The reason we had 100,000 is because I was working on a project that compares to EPA inventories.

Because different users might require different cutoff values, we should consider adding this as a secondary input. I will open a new issue for this after double checking Mohammad's edits.
