### ISSUE TITLE
Check whether aspen Q flows are primary or work?

### ISSUE THREAD

**Issue by arbrandt** [arbrandt/OPGEE#194]
Aspen reports Q flows for pump work and heater. For example, see dehydrator flows RblrQ and PumpQ.  Is this heat from the reboiler into the column, or energy content of the gas? Or for the pump, is that work supplied to the fluid by the pump or electricity consumed to provide the work? Put differently, are they inclusive of the final conversion efficiency?

**Comment by smasnadi** [comment]
I don't have access to Aspen anymore, but my impression is that:
- The reboiler Q is the heat from the reboiler unit to the column
- For pump, it is the power needed to run the fluid given the pump efficiency (as far as I remember, we could determine the pump eff in the software)
