### ISSUE TITLE
Notes for AGR incinerator fuel use

### ISSUE THREAD

**Issue by arbrandt** [arbrandt/OPGEE#195]
Where does AGR cell L312 come from? Note on right should be added to explain.

**Comment by qlangfitt** [comment]
Agreed, and it seems a bit strange that L311 (precedent to L312) only takes in molar fraction of H2S and puts out fuel use in kg/day. Would think it would have some type of scaling based on the amount of gas processed.

**Comment by smasnadi** [comment]
I put a comment in Note section:
"Based on a linear fit   of the obtained data from AspenHYSYS for inc. fuel gas consumption vs the H2S   conc."

I agree that a better correlation can be developed if we re-run AspenHYSYS and incorporate other parameters in the fit.
