### ISSUE TITLE
CO2 content of raw natural gas

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#197]
I'm wondering where the assumed 6% CO2 content of raw natural gas comes from. I can't find any sources that suggest average CO2 content would be that high (unless it's set to be on the high end and only come into play for fields with AGR). This results in quite high emissions from AGR when using a gas processing path with AGR turned on. If AGR is turned off, all that CO2 is passed along to the sales gas, which is clearly too high to be realistic. This may not matter to the modeling (?), but wanted to revisit that assumption since if we stick with that 6%, the assumption of whether or not AGR is used on a given field will have a substantial impact on the results.

**Comment by JSRuthe** [comment]
@smasnadi  do you recall what the source for this was ?

**Comment by arbrandt** [comment]
I don't recall where this assumption came from originally. I have seen data for everything from purely sweet (~0% CO2) to up to 50% CO2 (Jeff's data for Kapuni field). 6% CO2 should not be passed on to sales gas, so I will create an issue to flag that as an error if gas quality bounds are exceeded (generally 2%).

**Comment by smasnadi** [comment]
That 6% CO2 was put before I enter to Stanford! It is even exists in OPGEE V.1! Here is the basis for the assumption from the user guide:
<img width="605" alt="Screen Shot 2020-03-18 at 23 12 11" src="https://user-images.githubusercontent.com/46761921/77027963-fb7f5800-696d-11ea-81c3-d7cef963b294.png">
<img width="621" alt="Screen Shot 2020-03-18 at 23 13 01" src="https://user-images.githubusercontent.com/46761921/77027984-0c2fce00-696e-11ea-9e71-f09eab3e89d5.png">
