### ISSUE TITLE
Differences in compressor inlet pressures/temperatures in OPGEE 3.0 and 2.0

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#198]
I've come back to comparing OPGEE 2.0 and 3.0 for crude oil analysis. I've rediscovered an issue with gas reinjection compression that can cause major differences between the model versions for fields with a lot of natural gas reinjection. In OPGEE 3.0, pressures and temperatures are conserved and carried through from process to process. Thus the pressure at the wellhead (1000 psi) sets the pressure after boosting separator (1000 psi) which sets the inlet to gas reinjection compressor (1000 psi). Same thing happens for temperatures. In OPGEE 2.0, the inlet and outlet pressures and temperatures are set independently for each process. Thus, in OPGEE 2.0, although the wellhead pressure is also 1000 psi, the inlet pressure to the gas reinjection compressor is only 125 psi. As could be expected this causes a wildly different energy consumption for the gas reinjection compressor. So the question is, how should we set the inlet pressure to the gas reinjection compressor in OPGEE 3.0? Is it really the same as the wellhead pressure (and if so, why was it so different in OPGEE 2.0)? This is the same chain of pressures that causes issues with the transmission compressors, which leads me to believe that perhaps the pressure isn't actually 1000 psi by the time it reaches compressors.

**Comment by smasnadi** [comment]
Adam: I think this is one of the main changes between 3.0 and 2.0 that you were mentioning before. Right?

**Comment by arbrandt** [comment]
This is one of the main differences between the two models, and was enabled by tracking the mass flows more carefully. v2.0 essentially assumed that all gas was dropped to the lowest separator pressure and then recompressed before reinjection. This would be very wasteful and avoided in practice. In a real system you would hopefully pull most of the gas off at the first separator stage, which is about wellhead pressure. Then any additional gas coming off at later separator stages would be compressed back up to the higher working pressure. That is why the v3.0 separator sheet has integrated compressors that push the gas at each stage back up to the assumed working pressure of 1000 psi. There will be some loss in piping etc between the separator and the reinjection well, but that should be small.
