### ISSUE TITLE
Thermal EOR test fields throwing error

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#201]
Test fields related to thermal EOR (44, 55, 56, 58, 59) show error

**Comment by arbrandt** [comment]
The dilution module is not meant to work with 100% diluent. It has an error check to see if the fraction of heavy oil in the diluent is less than or equal to 0.001 (0.1%). The settings on those fields was exactly 99.9% diluent, causing this error to throw. Changed the inputs to 99% which avoids the error. Did not change the code, as this was meant to occur.
