### ISSUE TITLE
CRITICAL: Results sheet does not align with Active Field sheet

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#204]
The Results sheet does not show the same results as the Active Field sheet. They are similar, but in some cases the error is fairly significant. This is a critical issue to fix since the results sheet having errors makes it hard to assess the model in general.

I tracked this issue to the VBA code. The Results sheet is written from the Active Field sheet starting at Line 606 while calculations are in manual mode. After that the calculations are returned to automatic mode (Ln 662) which results in functions recalculating and changing the results on the Active Field sheet, but those changes are never reflected on the Results sheet.

**Comment by qlangfitt** [comment]
Dug deeper and the problem is that OPGEE recalculates stabilizer column and volume fraction diluent smart default inputs after all other calculations. This is done in manual calculation mode. Those inputs then drive other calculations, such as turning crude oil stabilization ON/OFF. However, since OPGEE remains in manual calculation mode from that point to the point when results are copied in from the Active Field sheet, those recalculations only occur later when automatic calculation mode is turned back on. I'm not super familiar with the VBA code for OPGEE or really VBA in general, so maybe there's a better solution, but I simply added a command to change to automatic calculation following the stabilizer column and diluent fraction recalculations and then an additional command to place back into manual mode. This didn't seem to slow anything down. Thus the surrounding lines of code are the following (it looks funny in GitHub markup, but just ignore the formatting, the bolded text in the middle is the only thing I added). This seemed to solve the problem.

  '%%%%%%%%%%%%%%%%%%%%%%%
    
    
    'Update defaults that may be affected by the above adjustments

    Application.Calculation = xlCalculationManual
    
    
    'Stabilizer column
    If Results.Range("G71").Offset(0, i).Interior.Color = RGB(0, 155, 118) Then
    ActiveField.Range("J110").Value = ActiveField.Range("K110").Value
    Results.Range("G71").Offset(0, i).Value = ActiveField.Range("J110").Value
    End If 'Changed


    'Volume fraction of diluent
    If Results.Range("G88").Offset(0, i).Interior.Color = RGB(0, 155, 118) Or ActiveField.Range("J242") = "ERROR" Then
    ActiveField.Range("J127").Value = ActiveField.Range("K127").Value
    Results.Range("G88").Offset(0, i).Value = ActiveField.Range("J127").Value
    Results.Range("G88").Offset(0, i).Interior.Color = RGB(0, 155, 118)
    End If

 **Application.Calculation = xlCalculationAutomatic**
 
 **Application.Calculation = xlCalculationManual**

    '%%%%%%%%%%%
     
    'Set Active Field Working Sheet inputs equal to Results inputs (Final)
    'Then set Results output entries equal to Active Field Working sheet outputs
    ActiveField.Range("J48:J154").Value = Results.Range("G9:G115").Offset(0, i).Value 'Changed
    Results.Range("G127").Offset(0, i).Value = ActiveField.Range("J60").Value 'Changed
    Results.Range("G130:G193").Offset(0, i).Value = ActiveField.Range("G169:G232").Value 'Changed
    Results.Range("G195").Offset(0, i).Value = ActiveField.Range("G234").Value 'Write the fugitives loss rate summary figure
    Results.Range("G197").Offset(0, i).Value = ActiveField.Range("J158").Value 'Changed
    
    
    '%%%%%%%%%%%

**Comment by arbrandt** [comment]
Went with this solution for now. It could also be fixed perhaps with a force calculate command, but we can optimize the code for speed later. Please check Quinn with the field(s) that were behaving inconsistently.
