### ISSUE TITLE
Error flag if sales gas has too much CO2

### ISSUE THREAD

**Issue by arbrandt** [arbrandt/OPGEE#206]
Create an error flag so that if AGR is turned off and (say) 6% CO2 is passed to the consumer it does not satisfy gas quality standards. Require CO2 to the end user to be 2% or less.

**Comment by smasnadi** [comment]
see my comment on #197

**Comment by arbrandt** [comment]
Fixed. If CO2 mass fraction is above 10% at flow sheet flow to export, then error flag is passed. This amounts to ~6% by mole fraction depending on MW of the rest of the gas.
