### ISSUE TITLE
Gas transmission distance - is it too far?

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#211]
I noticed the default gas transmission distance on the secondary inputs sheet was 2000 miles. This seems a bit far, both for what we know about the out-of-state fields that supply California and also compared to national averages as determined by Argonne for GREET. Would it make sense to make the secondary input for gas transmission distance be equal to the input for oil transmission distance? Maybe or maybe not, but if not, I think the default for gas transmission should more like 1000 miles.

**Comment by qlangfitt** [comment]
Otherwise, the gas transmission compressors look good to me and results fall within the expected range from other software/studies.

**Comment by arbrandt** [comment]
I think you make a good point. 2000 was used as a conservative value, but checking some reasonable long-path transport between CA and major gas producing basins, we don't see 2000 mi come into play. Denver to SF: 1200 mi, Calgary to SF: 1300 mi, Houston to LA: 1500 mi. Will change to 1000 miles to reflect a mix of closer and farther locations.
