### ISSUE TITLE
Surface processing natural gas fuel consumption may be underestimated 

### ISSUE THREAD

**Issue by abradley60** [arbrandt/OPGEE#213]
OPGEE V3.0 estimates for natural gas consumed in surface processing activities appear to be low compared to reported data and EIA statistics. A report on the issue along with a supporting word document and OPGEE V3.0 model has been sent to JSRuthe (22 Mar 2020).

**Comment by arbrandt** [comment]
Closing for now, to be investigated in future after stabilizing 3.0
