### ISSUE TITLE
Recycled CO2 is missing?

### ISSUE THREAD

**Issue by smasnadi** [arbrandt/OPGEE#214]
I could not understand one item for CO2-EOR mode of OPGEE. I think the current version of OPGEE misses large GHG emissions associated with CO2 recycling and re-injection! Here is the issue

Assuming: 
GFIR: 10,000 scf/bbl and the perc. of newly acq. CO2=40%

This means that 40% of GFIR comes from external fresh CO2 (which is accounted in "Gas flooding comp." sheet).
There are also two other internal sources of CO2 that come out of reservoir:

1- the produced associated gas CO2 (which is fully accounted in "Separation" sheet cell L18)

2- the recycled CO2 (60% of GFIR): Where is this stream in OPGEE calculations? This stream should be added to the associated gas stream and be passed through dehydrator, membrane/R-H, and AGR units and finally get injected through "CO2 Reinjection Comp." sheet. What is happening is that in the current version, only the associated gas is getting reinjected to the reservoir. 

Another minor issue is that: for the "Gas flooding comp." sheet to account the fresh CO2 injection, we need to subtract the associated gas CO2 that comes out of reservoir from that 40% and then flood the subtracted number to the reservoir.

**Comment by smasnadi** [comment]
I talked with Adam and seems that the recycling CO2 was missed from the entire OPGEE calculations. So here are the changes I made in OPGEE: 
I added a new stream in the Flow Sheet (stream 91) to introduce the recycled CO2 to the system (that 60% in above comment example) and made appropriate modifications to accommodate this change. Here are the changes made in different sheets and corresponding cells:
**Sheet name:cell address
Flow Sheet: O100 & column CR
Separation: L18
Reservoir: H18 & S18
Reservoir: column I from row 8 to 32
Reservoir: rows 79 and 80 are added
Gas Flooding Comp: E18 (to address the "minor" issue explained above)**

@qlangfitt or @arbrandt : I run OPGEE for Lula (field 8) and seems that everything works well and the numbers make sense. But I need second eyes to double-check the CO2-EOR. Thank you!

**Comment by qlangfitt** [comment]
Flow Sheet: O100 & column CR
- Looks good. Glad you all planned extra space in the flow sheet.

Separation: L18

- So, if I understand correctly, the gas composition on this sheet (Rows 39-50) is basically the natural composition without the influence of any injected CO2? If so, then L18 looks good. If not, then things get complicated in the feedback between gas composition and amount of CO2 injected.

Reservoir: H18 & S18
- Looks good (again, if “gas in reservoir” reflects the natural composition prior to the effect of adding injected CO2).


Reservoir: column I from row 8 to 32
- Good.


Reservoir: rows 79 and 80 are added
- Good.

Gas Flooding Comp: E18 (to address the "minor" issue explained above)
- I’m having trouble completely wrapping my head around this one. I know the gas flooding compressor is only for gas above and beyond what was produced and reinjected. That’s why column E is based on only the percent of the injected CO2 that is “new” CO2. But I still don’t understand why the naturally occurring produced CO2 has to be subtracted. Is that naturally occurring produced CO2 somehow already included in the GOR * GFIR * Perc_new_CO2?


Finally, when you say the results for Lula make sense, do you mean it is in agreement with OPGEE 2.0?

**Comment by smasnadi** [comment]
Separation: L18
So the gas composition in the process units is basically a combination of the reservoir naturally occurring associated gas + recycled CO2 that is not sequestrated (L18). The new CO2 injected only affects the gas flooding compres. sheet which is somehow detached from the other process units (see the Flow Sheet).

Gas Flooding Comp: E18
My understanding is that GFIR is the total cumulative gas that is injected to the reservoir (new CO2 and recycled CO2). So if additional CO2 (naturally occurring produced CO ) is injected along with the recycled CO2 (CO2-reinjection comp. sheet), we need to subtract that additional CO2 from the fresh CO2 that is injected to keep the total CO2 injected equal to GFIR. Does that make sense?
Probably a better way to calculate E18 is to simply subtract the total co2-rinjected (from CO2 Reinj. Comps. sheet) from the total GFIR. See the updated E18. 

No, I meant the flooding numbers now makes sense and the fact that the new GHG emissions is higher than before for CO2-EOR. Didn't have a chance to compare with 2.0. In 2.0 we had the same recycling issue, but I fix it in the last version before moving to 3.0
