### ISSUE TITLE
Workover and completions #REF

### ISSUE THREAD

**Issue by arbrandt** [arbrandt/OPGEE#215]
Workover and completions VFF emissions are 0 due to a #REF error in Drilling & Development, cells M46, M47, M57, M58. Jeff, can you trace and fix?

**Comment by JSRuthe** [comment]
@smasnadi , @arbrandt We are getting an error here because someone deleted the secondary inputs "cum_prod_gas" and "cum_prod_oil". Why were these deleted?

**Comment by smasnadi** [comment]
Not any change from my side

**Comment by JSRuthe** [comment]
See commit above
