### ISSUE TITLE
Natural gas reinjection occurs before using gas on-site

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#216]
This may not actually be an issue, and if so, please just close.

On the Gas Partition B sheet, the fraction of remaining natural gas reinjected is first applied to stream 49, then any additional gas is available for use on-site or exports. I guess it comes down to what "remaining gas" means. I would have interpreted that as meaning gas remaining after on-site uses and the flow diagram suggests that most of the on-site processes are upstream of the reinjection. But perhaps, the fields that use 100% reinjection really do reinject all produced gas and import all gas needed to power on-site equipment. If not, I think it's easy enough to adjust it to allow for on-site use prior to reinjection.

**Comment by arbrandt** [comment]
Good point, that is a little confusing. Now that you mention it, I think they would prefer to use gas on site to power equipment and reinject the remainder, rather than reinject all and import gas. Will change plumbing.

**Comment by qlangfitt** [comment]
After looking at this more closely, I'm starting to have second thoughts about my original error report. This is a complicated topic and decision. It looks to me like OPGEE 2.0 treats it the way it's programmed here, and that the definition of "remaining gas" is prior to onsite use.

There are good arguments on either side of this. All of this is to say that it will take a bit of thought before we go in a replumb. 

**In favor of current treatment**
It's often the case that the user calculates the fraction reinjected based on reported injection volumes and production volumes. That's quite common in our use cases (though note that even this isn't perfect since fugitives and some gas uses like flaring or lifting are drawn off earlier).

**In favor of changing treatment**
It's not uncommon for fields be set at 100% reinjection. In those cases, the results of the current treatment means that they are injecting all onsite gas and importing all gas needed. This increases the CI by both having to run more gas through the injection compressor and having to take on the embodied emissions of the imported gas.

There might be a happy medium where the treatment is changed, but the user should be aware if they want maximum accuracy, they need to run the model once with a best guess, and then manually adjust the injection fraction accounting for the amount of gas used onsite, leaked, etc. and run again for the final result.

**Comment by arbrandt** [comment]
Good discussion, and I get the ambiguity. I think I lean toward the new treatment. To me, 100% reinjection feels like a setting that is most sensibly defined as reinjecting the remaining gas after onsite use, not all produced gas. I think your instinct to report the issue in the first place was correct.
