### ISSUE TITLE
Some compressors for pressure balance are missing 

### ISSUE THREAD

**Issue by smasnadi** [arbrandt/OPGEE#220]
In different sections, seems that additional compressors are needed to set the pressure:

- Stream 64 (Hydrocarbon rich gas to AGR) (cell F32 of AGR sheet): this stream is a low pressure line because it comes from the membrane unit. Additional compressor is needed to raise the pressure to 1000 psi. (like the one we already have for Demethanizer cellB138)

- In AGR, the feed gas pressure is between 14.7-514 psi (200 as default), so the SweetGas pressure out of AGR Absorber is not around 1000psi. We need an additional compressor to raise pressure to 1000psi before introducing it to Demethanizer unit (Stream 37)

**Comment by smasnadi** [comment]
In addition: 

- Compressor for stream 32 before introducing the Stabilizer gas to Gas Gathering sheet (cell 32 to of Gas Gathering sheet)

**Comment by smasnadi** [comment]
What is the pressure of Dry gas out of T-100 unit in Glycol Dehydrator sheet (Fig. 1). If it is not 1000 psi, again we need to add a compressor

**Comment by smasnadi** [comment]
Two compressors are added for now in AGR and membrane sheets for raising the pressure of Sweet gas and Gas from membrane to AGR to the desired pressures. For Sweet gas stream, it was assumed that the stream pressure is equal to the feed gas pressure.

**Comment by arbrandt** [comment]
Added compressors to deal with these issues, and adjusted stream pressures to line up with new line pressure of 500 psi.
