### ISSUE TITLE
Free gas volume can go negative on the pumping equations

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#222]
If the solution gas oil ratio is higher at the wellhead than at the bottomhole, the Well and Downhole Pump sheet will calculate a negative amount of free gas in the production tubing. These negative values carry through and lower the pumping power required. Lula is an example of this.

At least in the case of Lula, this can be traced back to a combination of productivity index and oil production volume which result in a bottomhole pressure (Reservoir M69) that is so much lower than the wellhead pressure that even the higher bottomhole temperature cannot compensate.

Perhaps a good solution would be to limit the crude oil solution gas ratio at the wellhead (Flow Sheet I33) to be equal to that at the bottomhole (Flow Sheet H33) if wellhead is calculated to exceed bottomhole. Could simply add it as another term in the existing MIN function in I33. This makes sense to me intuitively since more gas cannot develop inside the wellbore than was available in solution at the bottomhole (right?). 

=IF(AND(I30=1,I8>0),MIN(I29^(1 / pbub_a2) * I32 ^ (-pbub_a1 /pbub_a2)*EXP(pbub_a3 / pbub_a2 * Gas_sg* I32) /( (460 +I27)*Gas_sg),GOR_bubblepoint,**H33**),0)

**Comment by arbrandt** [comment]
This is a bit of a corner case, but I think the behavior is physical. In the case of Lula, the pressure is low at the bottom of the well, then then pump overcomes the gravitational pressure traverse, the friction pressure traverse, and the diff between wellhead flowing pressure and bottomhole flowing pressure. Thus, the pump is essentially repressurizing the crude and driving some gas back into solution. Thus, the volume should shrink somewhat during this process. Whether the field is actually operated that way or not is another question...

**Comment by arbrandt** [comment]
Another way to fix it would be to check the bottomhole pressure when adjusting PI to make sure that it always stays at or above the wellhead pressure.
