### ISSUE TITLE
SO2 contribution to molar mass of gas seems wrong

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#223]
On the Fuel Specs sheet, there is a gas MW table labeled "Fixed gas SG to avoid circular refs" (AL117). The value at the bottom of column AL (Total) is used in a couple of places to define the MW of exolved gas. I noticed at high WOR, this MW was very high and it is because the SO2 contribution (AL132) is based on the WOR. This doesn't seem right, and even if there is some correlation, the equation doesn't seem to make any sense. Wondering if this should just be 0 like it is elsewhere in the model?

**Comment by arbrandt** [comment]
Fixed. It should be 0, and not sure at all where this came from. Quite strange.
