### ISSUE TITLE
Energy to inject produced water to subsurface disposal

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#224]
I assume produced water to subsurface disposal (stream 114) means pumping the water into a reservoir. If so, should there be pumping power needed for that process? It seems like the model currently drops that stream and assumes no emissions associated with the disposal.

I guess the question is, what effectively is the difference between water reinjection and disposal of produced water to the subsurface? Is it perhaps not injected as deep?

**Comment by arbrandt** [comment]
It depends. Many places dump the water into a somewhat under-pressured aquifer, such that the pressure of the water in the layer injected into is somewhat below hydrostatic. That means: as you put water into the wellbore, the water would naturally flow into the layer from the pressure of the water column. It is like a hole that never fills up. Not sure how many are this way vs. neutrally pressured, but assumed this was the case.
