### ISSUE TITLE
Produced water treatment uses WIR for both water reinjection and water flooding

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#226]
I'm not sure this strictly an error since it can be "solved" by the analyst taking care to enter inputs (for WOR, WIR, and fraction of produced water reinjected) that agree on water injection volume. Still, I think this is a good improvement for redundancy.

On the Produced Water Treatment sheet, the total water injection demand satisfied by produced water (M87) draws on only the WIR to determine the amount of injection, regardless of whether water reinjection or flooding is used. Elsewhere (e.g., Water Injection sheet M39), the model draws on different water injection inputs depending on whether reinjection or flooding is being used. I think it would be best to adjust Produced Water Treatment M87 to draw different water injection inputs based on whether reinjection or flooding is used as on the Water Injection sheet.

**Comment by qlangfitt** [comment]
In opposition to my point above that this should ideally be on the analyst to use good inputs. It is reasonable to think that on a field not using water flooding, the analyst might leave the WIR blank rather than set it to 0. In that case, the WIR=WOR+1. This means the model will treat all produced water (and then some) as reinjected, regardless of what the fraction of produced water reinjection input states. This is surely contradictory to the intent.

Recommend using the same equation as Water Injection M39 in Produced Water Treatment M87:
=IF(Water_reinjection_01=1,Oil_prod*WOR*Fraction_water_reinjected,IF(Water_flooding_01=1,Oil_prod*WIR,0))

**Comment by arbrandt** [comment]
Fixed using Quinn's suggested code.
