### ISSUE TITLE
Site model Omara mean loss rates pull from too large a range

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#232]
The mean Omara percent loss rates on the VF method - Site sheet (row 81) use too large an area for the AVERAGE function. This results in averaging in some values that are completely unrelated to the leak rate observations and significantly affects Bin 4 (and other bins to a lesser extent).

**Comment by qlangfitt** [comment]
Also, can we double check the underlying values in Bin 2? They look a bit high compared to Omara's summary in Table 1.

**Comment by JSRuthe** [comment]
This issue is no longer relevent with the new site-level calculator
