### ISSUE TITLE
Intermittent and continuous tank EFs boil down to same equation

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#233]
On the VF method-component sheet, the intermittent and continuous deterministic tank EFs (C75:C76) are effectively the same equation. Is it just that there is no such concept as intermittent vs. continuous in deterministic mode or is there is a mistake in the intermittent equation?

**Comment by JSRuthe** [comment]
See issue #236 

Aslo, as we discussed on the call, tank flashing I believe is captured within the Omara dataset (which we will clarify on the site level tab).  Therefore, deterministic flashing values are no longer required for a deterministic site level calculation
