### ISSUE TITLE
Officially recognize that component level model cannot produce deterministic defaults

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#236]
CC: @arbrandt @qlangfitt 

Based on the attached file which Adam and I sent to CARB back in March, I would like to formally recognize in OPGEE that the component level model cannot produce deterministic outputs. Rather, users of the component-level model must run multiple realizations and converge on a mean. This will require:
1) Removing "deterministic" columns from the VF-component sheet
2) Removing "determinstic" values from the tank flashing calculation

It has also been a while since I tested the OPGEE Uncertainty calculator on the component level model. For the journal article I am writing, I have been using an external wrapper on OPGEE. This should be tested before this issue is closed

[Note on deterministic fugitives modelling.docx](https://github.com/arbrandt/OPGEE/files/4624542/Note.on.deterministic.fugitives.modelling.docx)

**Comment by qlangfitt** [comment]
Please hold off just for a bit for us to discuss at CARB.

**Comment by JSRuthe** [comment]
Based on commit bda60dc70b53fc8384ffcc4a735ab5d66a61ab92 

The component-level fugitives model has been adjusted to produce deterministic loss estimates
