### ISSUE TITLE
Some compressor sheets break when work of compression negative

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#237]
On the Gas Flooding Compressor sheet there is a failsafe for prime move fuel use that checks whether the brake horsepower is >0 before attempting an HLOOKUP for the fuel consumption of the prime mover. I was running a field with sour gas reinjection, but the conditions were such that a negative adiabatic work of compression was being calculated (compression ratio <1). This was causing the model to break when it tried to use HLOOKUP to find the prime mover fuel use (M74:M75). Please adjust to check for non-negativity before attempting to lookup. I'm not sure how this is dealt with for other compressors, but perhaps this need to be implemented on more compressor sheets as well.

**Comment by arbrandt** [comment]
Fixed
