### ISSUE TITLE
CO2-EOR fields can leak CO2 at very high rate using Site fugitive model

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#238]
Fields with CO2-EOR can see very high fugitive emissions if they also have low gas production. Using the site model, if gas production is very low, the fugitive rate will be set to 21%. In a field that is also using CO2-EOR, the CO2 is then leaked off at 21% as well. This seems unlikely since the premise of the Omara leak rate trend is that with less gas flowing through infrastructure smaller absolute leaks (e.g., kg/hr) can be much larger when production normalized. In this case, there is a lot of gas (natural gas+CO2) flowing through the system and I think it would be very noticable if such a high loss rate of CO2 were occuring. Do you think it would be appropriate for CO2-EOR fields to have the Omara correlation applied to the total volume of gas production (natural gas + CO2)?

**Comment by JSRuthe** [comment]
@qlangfitt can you please provide a specific field example which I can use to dig into this question? Also, can you please check if this question is still relevent based on recent changes to fugitives from secondary/tertiary production methods?

**Comment by qlangfitt** [comment]
This is issue is somewhat mitigated by the fact that we now use production distributions in the site model. However, it still exists to a certain extent. For example, if you take Field 99 and give it a low GOR (like 100), then you'll see how fugitive emissions of CO2 will dominate total VFF. The reason is that the CO2 is assumed to leak at the same rate as the natural gas (good assumption, but bad then to base the leak rate on CH4 alone). In the case of a field with low gas production but very high CO2 production (because flooding is being used and the CO2 is recycled) OPGEE models CO2 as leaking at a very high rate. This seems wrong because probably the CO2 leaks would be detected if they were that large.

What I was proposing was that for fields using CO2-EOR, perhaps the site model's gas flow rate that it uses to calculate leak rate should also include the CO2 portion (since those fields will presumably have a high rate of CO2 production relative to natural gas production).

**Comment by JSRuthe** [comment]
Ok, this makes sense now and I can see why this is a problem. However, I would prefer a solution with less "if" statements. Here is my suggestion:
- Right now the the site level and component level calculators are based upon: oil prod * (GOR + GLIR)
- What this calculation is supposed to represent is gas at the wellhead. However, like you have pointed out there still exists the possibility that CO2 will break through at the wellhead during CO2 EOR 

Fortunately, this calculation is already done for us in OPGEE on the separator sheet. See below. I propose linking fugitives to this cell

![image](https://user-images.githubusercontent.com/42356585/95487956-379df880-0952-11eb-8020-e4f213c867be.png)

**Comment by JSRuthe** [comment]
This fix seems to work. CI is reduced for CO2 EOR fields (Compared to before fix) and there is no impact on fields which don't use CO2 EOR

**Comment by JSRuthe** [comment]
this issue is addressed with e6e5dcf

**Comment by JSRuthe** [comment]
OK, total gas production now calculated with the following formula

=(Oil_prod*(GOR+Gas_lifting_01*GLIR)+IF('Active Field'!J90=3,(Oil_prod*GFIR*((Perc_CO2_breakthrough)/100))))/1000

Going to make the commit then do testing

**Comment by JSRuthe** [comment]
@qlangfitt can you please confirm if my changes have addressed your original comment (I understand this was a long time ago now ...)

**Comment by qlangfitt** [comment]
Yes, this looks good. Closing now.
