### ISSUE TITLE
Reset secondary inputs to defaults

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#239]
A handful of the secondary inputs are currently not set as the default values (for example textbooks approaches for AGR and dehydration, instead of process sim). I think we need to go back through and set all of the secondary inputs to the sensible defaults so that if a user downloads OPGEE it is ready to go with only adjusting primary inputs.

Also on secondary inputs sheet, the range of valid flaring years should be adjusted.

**Comment by arbrandt** [comment]
Made all secondary inputs refer to the default for that row. Did not adjust any of the defaults.

**Comment by qlangfitt** [comment]
CO2 membrane effectiveness erroneously had the HC stream effectiveness replaced with the CO2 stream effectiveness during this process. Set HC stream effectiveness back to the old values as seen below.

![image](https://user-images.githubusercontent.com/47186327/92014929-dd7f9700-ed04-11ea-8aa3-b39230deab1d.png)

**Comment by arbrandt** [comment]
Fixed. Thanks for the catch. Was causing strangeness with Lula
