### ISSUE TITLE
Exploration excluded from Active Field sheet

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#240]
On the Active Field sheet, the exploration emissions are set to 0. There are calculated values on the exploration sheet and on the GHG summary sheet, so it seems those should carry over to the Active Field sheet. Otherwise, they are excluded from the CI calculation.

**Comment by arbrandt** [comment]
Fixed. Very strange that this was set to 0.

**Comment by qlangfitt** [comment]
Combustion/land use emissions added correctly, but the "total GHG emissions" from Exploration on Active Field sheet (G170) is still set at 0. Should be sum of combustion/land use and VFF.

**Comment by arbrandt** [comment]
Oops! Fixed.
