### ISSUE TITLE
Claus unit exhaust can duplicate flows to gas to demethanizer

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#241]
While testing out-of-state fields (ANS from LCFS) I found that gas balance could throw an error for N2. Traced it to the AGR sheet. The Claus unit exhaust (stream 286) and Gas to demethanizer (stream 37) can duplicate each other for some gases when AGR is OFF. Suggest adding IF logic to stream 286 to set to 0 if AGR is OFF.

**Comment by arbrandt** [comment]
Fixed as suggested.
