### ISSUE TITLE
Default well count trips up component level model

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#242]
If the user doesn't specify a well count, the smart default will sometimes draw a non-integer well count (e.g., 0.5). This trips up the component level calculator

**Comment by arbrandt** [comment]
Fixed by using "roundup(x,0)" function to round number of computed production and injection wells to next highest integer. Avoided round so we don't get 0 wells in some cases, always get at least one. Also, pressure drop and other aspects work better with larger number of wells.
