### ISSUE TITLE
Productivity index increment size

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#245]
The productivity index is checked and adjusted in VBA to ensure it complies with physical constraints (checks bottomhole flowing pressure). The increment size for adjustments is 1. Given the default PI is 3.0, an increment of 1 seems very large. Could that increment be reduced? Perhaps 0.1 or 0.25? This doesn't seem like it should be computationally intensive. Note there are two places in the OPGEE 3.0 code where PI is adjusted - not sure if this was intentional, but the change would probably need to be made to both.

**Comment by arbrandt** [comment]
Fixed issue #245 by changing increment for PI adjustment to 0.25. Fixed in commit of Aug 27 2020 at 11:21 am.

**Comment by arbrandt** [comment]
BTW, changed both places were PI was incremented in response to excessive pressure drawdown.
