### ISSUE TITLE
AGR gas composition based on wellhead, not AGR inflow

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#246]
The composition of gas entering AGR factors into the reboiler calculations (%CO2 and %H2S). For the textbook method, the composition is determined by the flows of gases into the AGR in the flow table on that sheet. However, the process simulation approach uses the wellhead composition from the inputs (Acid Gas Removal sheet E67:E68). This can lead to wildly different results between the two methods when gas processing paths 7 or 8 are used and thus the input composition to the AGR is very different than the wellhead composition. When implementing the fix, make sure to use mol fraction, not mass fraction.

Also on this, the maximum composition of CO2 allowable in the process simulation method is 20% by volume. Fields that use CO2 flooding could have CO2 concentrations much higher than this (?) as Lula (Field 8) does in the sample field set. I'm assuming the cap is because the correlations equations were only run up to 20%, but that's problematic when CO2 is coming in at much higher fractions. Perhaps should add an error check to flag that the user should switch to using textbook approach on such fields.

**Comment by arbrandt** [comment]
Fixed in version committed Aug 27 2020, 11:08 am.

**Comment by qlangfitt** [comment]
I see that you added an error message to the AGR sheet natural gas use if the 20% threshold is exceeded and process simulation is chosen, but it was actually hard for me to figure out why the model had failed until I started digging. Would be best if the model still calculated some value there (preferably, just have it calculate with the textbook method if over 20% CO2), but then throw an error in the Active Field error checking area saying the software automatically changed to the textbook method. Or I'd even be fine with no error code and just switching to the textbook for those cases.

**Comment by arbrandt** [comment]
Fixed. Instituted new code to remove value error when this occurs and just use textbook model. Instituted new warnings section in bottom of active field sheet.
