### ISSUE TITLE
Heavy oil dilution NGL consumption broken

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#248]
NGL consumption the Heavy Oil Dilution sheet (D87) points to a blank cell. I gather from earlier versions of the model that this should be the mmbtu/d of diluent used (=LHV_diluent_mmbtu_per_bbl*diluent_bbl_per_day), but honestly I'm not sure I understand why. Is the diluent being combusted?

**Comment by qlangfitt** [comment]
As for the last question (is diluent being combusted?), I see now that this is actually already treated correctly in OPGEE 3.0. I understand now that the accounting on that page is to ensure that the correct amount of NGLs are imported for upstream accounting, but on the energy summary sheet, the NGL combustion cell for Heavy Oil Dilution is set to 0. Maybe add a gray note below the combustion calculation on the Heavy Oil Dilution sheet stating that the NGL is accounted there for import purposes, but it not combusted on the energy summary sheet.

**Comment by arbrandt** [comment]
Fixed. You were right in your skepticism at first. The NGLs are used, and need to be counted as a process stream flow as they must be imported. But they are not consumed as such. The term was zero'd out in the energy summary sheet regardless, so was not distorting emissions calculations. Simplified it by removing this term and making the energy summary sheet row for heavy oil dilution more consistent. Also fixed a number of strange small things on this sheet, which were not working.
