### ISSUE TITLE
Fuel gas consumed/imports missing stream

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#251]
On the Fuel Gas Consumed sheet there an entry for "Fuel gas - electricity generation" (row 55) that is not captured on Fuel Gas Imports sheet (M57) that is supposed to calculate the total imports. I think the entry for electricity gen fuel was probably added later and never got back-added to the import calculation, unless I'm interpreting that entry wrong and it is already accounted for in electricity calculations elsewhere.

**Comment by arbrandt** [comment]
Fixed. Row is added to fuel gas imports sheet, and column of inputs for flow 174 is added, computed congruently to other rows. Flow sheet is plumbed to take this value on. Tested against default field, setting fraction of electricity generated onsite to 1. This fixes all of the relevant cells that I can tell.
