### ISSUE TITLE
CO2 gas flooding volume wrong when using gas proc path 6

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#252]
CO2 injection flows are separated by new CO2 and recycled CO2. When using gas processing paths 7 and 8, the recycled CO2 is run through the CO2 reinjection compressor. Accordingly, stream 77 on the Gas Flooding Compressor sheet subtracts the amount of CO2 injected by the reinjection compressor from the total CO2 injected (Gas Flooding Compressor E18).

When using gas processing path 6, the recycled CO2 is run through the sour gas reinjection compressor instead of the CO2 reinjection compressor. However, the amount of CO2 going through the sour gas reinjection compressor is not subtracted on the Gas Flooding Compressor sheet. Should adjust Gas Flooding Compressor E18 to also subtract Sour Gas Reinjection Compressor J18.

Although the gas flooding compressor corrects for this issue in its calculations of compressor work, this issue carries through to the indirect credits/debits for acquisition and sequestration of CO2.

**Comment by smasnadi** [comment]
Thank you! 

If the user choses path 6 (sour gas reinjection) for CO2-EOR:

Gas Flooding Compressor sheet cell E18 is modified to account for path 6 CO2 recycling.
