### ISSUE TITLE
Drilling and development land use diluent adjustment

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#253]
On the Drilling & Development sheet, the land use emissions are divided by the SCO/bitumen ratio to adjust down the emissions based on dilution (B74). Subsequently, on the Active Field sheet, these same emissions are multiplied by the diluent adjustment factor (G177). I believe this is double dipping on the diluent adjustment and should be removed from the Drilling & Development sheet.

**Comment by arbrandt** [comment]
Correct. Good catch. Fixed in commit on Aug 27th 11:14 am in drilling and development emissions were adjusted for dilution twice. Removed dilution adjustment on the drilling sheet.
