### ISSUE TITLE
Active Field results - surface processing addition

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#254]
Updating of the Active field sheet results in incorrect addition of surface processing emissions

![image](https://user-images.githubusercontent.com/42356585/84177680-6b1e5400-aa40-11ea-9436-4ab106c4af8f.png)

**Comment by arbrandt** [comment]
Unable to replicate this Jeff. Please add more details or send me a sheet where the error occurs. I ran a case, then went to active field sheet and hit recalculate. I don't see any incorrect addition appearing.
