### ISSUE TITLE
Unable to match the total GHG emissions from the results sheet with the Summary GHG emissions table on Active Field

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#255]
Dear all,

I am running CO2 EOR module and not able to match the GHG emissions from the results sheet to the active field.

The field cases run are from field 400 to field 420.

For the active field 420, following are the results from the Results sheet:

Total GHG emissions Drilling and Development            1.2 gCO2eq/MJ
Total GHG emissions Crude production and extraction 8.4 gCO2eq/MJ
Total GHG emissions Surface Processing                       7.1 gCO2eq/MJ
Total GHG emissions Crude Transport                           0.8 gCO2eq/MJ
Other small sources                                                       0.5 gCO2eq/MJ
Offsite Emission credits                                                 10.1 gCO2eq/MJ

Total GHG emissions                                                     28.1 gCO2eq/MJ

From the active fields, the total is (without sequestration credits) is 24.41 gCO2eq/MJ.

Also it would be nice to see also the total GHG emissions only on results sheet without sequestration credit when running for multiple fields.

Thanks,

**Comment by arbrandt** [comment]
Unable to recreate this on Sep 7 build. Please re-test and perhaps it has been fixed?
