### ISSUE TITLE
Completion and flowback VF emissions broken

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#256]
VF emissions from completion and workover flowback are both broken.

On the Drilling & development sheet, the calculations for CO2 and CH4 apportioned over the well life (M46:M47,M57:M58) both have broken references resulting in 0 emissions.

Further, while it does not factor into the model results, there are entries for flowback and completion on the VF method - Ccomponent sheet, section (iii) (rows 118 and 119) that reference the wrong cells for the EFs. If a user were on that sheet looking for the component level calculations, they might be confused when they see very high emissions.

**Comment by JSRuthe** [comment]
I think I may have fixed this with commit /297cfc9 (June 8)

Can you make sure your local OPGEE copy is up-to-date and double check this?

**Comment by qlangfitt** [comment]
Yep, I must have been working off an older copy. I see now that the cells in Drilling & Development are fixed.

However, the EFs on VF method - Component (H118:I119) are still not pulling from the right cells. Looks like the Completions EF is drawing the per event fractured workovers CO2 emissions and the Workovers EF is drawing a blank cell.

**Comment by JSRuthe** [comment]
References should now be correct based on above commit
