### ISSUE TITLE
Storage and injection well fugitives mostly broken or missing

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#259]
Fugitive emissions from various storage and injection well sheets are either missing or clearly reference incorrect cells from the VF method - Component sheet. I would imagine there needs to be some way of estimating the number of these wells (perhaps secondary input on the average assumed throughput per well?) and then the well EF could be borrowed in some way.

**Comment by JSRuthe** [comment]
see commit 1d010f6 and further explanation in issue #267
