### ISSUE TITLE
Loss fraction at end use appliance/equipment data source

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#260]
The end use loss rate (Losses_enduse) on the Secondary Inputs sheet (M737) is set at 0.1% with a note that little to no data is available. It would only be applicable for residential gas use, but at least for that application I would point you to an LBNL study sponsored by the CEC ([Fisher et al. 2018. "Natural Gas Methane Emissions from California Homes"](https://ww2.energy.ca.gov/2018publications/CEC-500-2018-021/CEC-500-2018-021.pdf)) that is being used in the CARB inventory for residential post-meter emissions. If you do the math, it comes out to about a 0.475% loss rate for residential buildings in California.

As another note, the number entered into the Secondary Inputs is labeled as a % loss rate, but is treated as a fractional loss rate.

**Comment by qlangfitt** [comment]
CARB also has a residential customer meter leak study that has wrapped up measurements and the final report is forthcoming for potential inclusion in Losses_customermeter.

**Comment by qlangfitt** [comment]
Here's a recent CEC-sponsored commercial buildings emissions measurement study (performed by ICF and GTI) also for potential inclusion for end-use emissions: ICF. 2020 "[Characterization of Fugitive Methane Emissions from Commercial Buildings in California](https://ww2.energy.ca.gov/2020publications/CEC-500-2020-048/CEC-500-2020-048.pdf)"

**Comment by arbrandt** [comment]
Added. We will default to the consumer meter, with thoughts that a person could change it to the commercial value (or another custom value) if desired.

**Comment by qlangfitt** [comment]
The 0.00475 default loss fraction and reference should have gone under Losses_enduse, not losses_customer meter. The Fischer study was only **post**-meter emissions (from appliances/piping in the house).

**Comment by arbrandt** [comment]
Fixed, placed in proper cell. Retained residential value. Pending publication of customer meter study, meter is set to 0 leakage.
