### ISSUE TITLE
Gas transmission fugitive emissions - scale by distance

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#261]
My observation in other models (e.g., GREET, NETL) is that the rate of fugitive emissions from gas transmission is generally tied to the distance of transmission. OPGEE uses a static percent loss that doesn't account for transmission distance. It makes sense that the further the gas travels, the more connections, valves, etc. it must pass through, and thus the higher the total loss rate. I think the transmission distance should be worked into transmission fugitives, even if it's just as simple as taking the average total loss rate, dividing it by the average transmission distance, and multiplying it by the field-specific transmission distance.

**Comment by qlangfitt** [comment]
Reflecting on how transmission compressor energy consumption is done, it would make sense to just tie this to the secondary input for gas transmission distance that defaults at 1000 miles. Then at least in advanced use cases it could be changed on the secondary inputs sheet and cause a change in the fugitive emissions.

**Comment by JSRuthe** [comment]
Will wait to close until this has been tested for a few cases

**Comment by qlangfitt** [comment]
I've done some testing and looks like it is working well.
