### ISSUE TITLE
Some fields still have CH4 loss rate >100%

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#269]
Some fields with very low gas production still have loss rates >100%, even with the new version of the component fugitives tool. The reason is that the tank flashing emits CH4 that is not counted at the wellhead (I think - correct me if I'm wrong here) because it is dissolved or entrained in the oil. Suggest adding the mass of CH4 exolved and emitted during flashing to the denominator of the CH4 % loss equation on the Active Field sheet (G234).

**Comment by arbrandt** [comment]
Yes, any CO2 dissolved in crude and flashed at separator, stabilizer, or tank will not appear in the wellhead flow. Jeff, can you please fix this one.

**Comment by arbrandt** [comment]
I mean CH4, sorry.
