### ISSUE TITLE
Claus Unit exhaust set to permanently 0

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#276]
In previous versions of OPGEE, the CO2 removed from the gas stream would be vented out of the Claus Unit (unless reinjected). In the latest version that I'm testing, this functionality has been removed and the CO2 passing through the Claus Unit does not get exhausted. I'm assuming this was simply a mistake and the old functionality should be returned.

This is the Acid Gas Removal sheet, stream 286.

**Comment by JSRuthe** [comment]
Hi @qlangfitt , @arbrandt and I have elected to short circuit the Claus Unit for now. Its been causing significant problems in mass balance and will need some time from Mohammad, which we don't have right now since he's busy starting up his lab.

Our short term fix is to redirect 95% of CO2 to the AGR vent, remaining 5% to demethanizer.

**Comment by JSRuthe** [comment]
claus unit processes will also be deleted from the flow sheet to prevent mass balance errors from showing up

**Comment by JSRuthe** [comment]
I will set this issue as "Tabled" - @arbrandt and @smasnadi and I will need to discuss after the workshop meeting

**Comment by arbrandt** [comment]
Claus unit deleted. Flows kept in as 0 for now, will re-add claus unit in future version. Too problematic to add for now, and a very small energy consumption source so not a priority.

**Comment by qlangfitt** [comment]
Reopening this just for a quick fix for a new error that was introduced in the commit reference here.

When Claus unit was removed, stream 73 was adjusted on the AGR sheet, but the entry for SO2 was overlooked (Cell L27). It contains a #REF! error that causes the model to break when gas processing path =7. Presumably, that should just be set to 0 since Claus Unit is removed now (?).

**Comment by arbrandt** [comment]
Good catch. Just fixed and pushed new version.
