### ISSUE TITLE
Sheet "GHG Summary - NEW" has #REF! errors

### ISSUE THREAD

**Issue by zicheng777** [arbrandt/OPGEE#279]
Sheet "GHG Summary - NEW" has six #REF! errors for columns J and M. This is due to the #REF! errors in Crude Oil Storage sheet.

**Comment by arbrandt** [comment]
I am still working on this sheet and it is not yet final and wired in. Let me work on it now and try to finalize it.

**Comment by arbrandt** [comment]
Fixed. Now there is only one GHG summary sheet and it is the new and improved GHG summary sheet that shares its structure with the Energy summary sheet.
