### ISSUE TITLE
Combustion emissions in gCO2e/d (rather than tCO2e/d) for some processes

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#280]
On the water injection, makeup water treatment, and produced water treatment sheets, the combustion emissions are not divided by 10^6, such that the results are in gCO2e/d rather than t/CO2e/d. I did not check all sheets, so it could be present elsewhere.

EDIT: Also present on CO2 membrane sheet

**Comment by JSRuthe** [comment]
@arbrandt I think this is related to the email that I sent you about high CI for water injection. Since the "GHG Summary New" superceded the old GHG summary sheet, this unit conversion error now translates into very high CI

**Comment by JSRuthe** [comment]
Fixed on co2 membrane, water injection, makeup water treatment, produced water treatment
