### ISSUE TITLE
Post-storage compressor double counted on new GHG summary sheet

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#282]
On the new GHG summary sheet, the post-storage compressor is included both under its own line item (row 70) and as a component of the storage compressor line (row 69) for land use and VFF emissions. Need to remove post-storage compressor from the storage compressor line.

**Comment by arbrandt** [comment]
Fixed! Good catch. It was also doing the same for the storage separator. Each one has its own line now, so the earlier logic of including them all on storage compressor line is not needed.
