### ISSUE TITLE
A few VF streams missing from new GHG summary sheet

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#283]
I found three injection well streams on the Venting & Fugitives 3.0 sheet that were not reflected in the new GHG summary sheet, including:

- Stream 260: HC gas injection wells
- Stream 275: Sour gas injection wells
- Stream 277: CO2 injection wells

**Comment by JSRuthe** [comment]
Fixed in commit 3a9cdbde860af368c089e156b61821c9264fae41
