### ISSUE TITLE
Run-Time Error 13 for Gas Well Analysis

### ISSUE THREAD

**Issue by jyuan03** [arbrandt/OPGEE#284]
The run time error 13 is presented when I run OPGEE with the parameters shown in the attached file (under Inputs). I've tried manipulating the oil production, GOR, and gas composition to fix the error without success.
[OPGEE_3.0a_BETA_testfile.xlsx](https://github.com/arbrandt/OPGEE/files/5425621/OPGEE_3.0a_BETA_testfile.xlsx)

 What could be the reason for this error?

I'm currently using OPGEE 3 downloaded October 22, 2020. 

Thank you.

**Comment by qlangfitt** [comment]
The issue is that the input for ocean tanker size has been set to 0. Most parameters can handle an input of 0, but this particular one cannot. If you simply leave that input cell blank rather than setting to 0 the model should run.
