### ISSUE TITLE
Ensure correct default steam injection type is set on Secondary Inputs

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#285]
I've noticed that the default steam injection type on the Secondary Inputs sheet (N258) has changed over time. Please ensure that is set to the intended default.

**Comment by arbrandt** [comment]
Checked and clarified the documentation off to the right. The options are correct. If Canada, the default option is SAGD. If not Canada, default option is steam flood. These don't control much, but are there for consistency and future options.
