### ISSUE TITLE
CO2 gas flooding injection rate changed

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#286]
On the Gas Flooding Compressor sheet, older versions of the model calculated an "adjusted volumetric flood gas injection rate" that was reduced by the amount of recycled CO2 when using CO2 flooding. This was removed in more recent versions, but I'm having trouble understanding why.

My understanding is that the model treats the reinjected stream and the "new" stream (specifically for purposes of flooding) differently. The reinjected portion is handled on the CO2 reinjection compressor sheet while the new portion is handled on the gas flooding compressor sheet. The reason for this is that the two streams have different state properties. Thus, when the amount of CO2 injected is calculated on the Gas Flooding Compressor sheet, it must be reduced by the amount of CO2 that was obtained by recycle if starting with oil_prod*GFIR. This was the purpose of the adjusted injection rate, which was removed. I believe this is resulting in an overestimation of the energy required for CO2 flooding. 

I think the most straightforward solution is to treat the flooding compressor like the reinjection compressor and draw the volume of new CO2 (whole stream) from the flow table MMSCFTOT row. This ensures that the injection energy calcs are consistent with the flow sheet, which is already controlled for mass balance. In fact, I think the same problem exists for natural gas flooding and this would simultaneously solve that problem. Here's the equation I propose for Gas Flooding Compressor cell M74:

=IF(N1="ON",M73*SUM(INDEX(FlowTable,TOTMMSCF,77),INDEX(FlowTable,TOTMMSCF,78),INDEX(FlowTable,TOTMMSCF,79)),0)

On the issue of natural gas flooding and reinjection, I think there's also an additional error there. The Gas Reinjection Compressor sheet handles the portion of natural gas that is extracted and reinjected while the Gas Flooding Compressor sheet handles the remaining gas needed for flooding. However, stream 78 on the Gas Flooding Compressor sheet is not reduced by the amount of reinjected gas. Note that this last paragraph is moot if the GFIR is supposed to only represent the additional gas needed for flooding beyond that reinjected.

**Comment by myjabbar** [comment]
@qlangfitt 
Just to clarify for modelling a CO2-EOR flood on a yearly time series basis with no gas processing (path 6 in OPGEE)

The GFIR is the (total gas injection rate/oil rate) so for the first year its mainly purchased gas injection assuming there is no little breakthrough

**For the Following years** GFIR= (purchased CO2 gas+Produced CO2+Produced HC gas)/oil rate
Is this what you mean?

**Comment by smasnadi** [comment]
@qlangfitt : Regarding CO2 injection comment: I don't know why the adjusted rate is removed, and you are right that there are two sheets taking care of CO2 flooding. But have you seen cell E18 of Gas Flooding Compressor sheet? There, I subtracted the recycled amount from the total GFIR. Does it make sense?

**Comment by qlangfitt** [comment]
@smasnadi Yes, I see that the CO2 flowrate is properly reduced for Stream 77 (column E), but just was commenting on the fact that the flooding compressor is modeled to inject the full amount of gas indicated by the GFIR (cell M53), not the amount indicated in Stream 77. 

That said, @myjabbar points out in Issue #287 that the purchased CO2 comes in at injection pressure already so no gas flooding compressor is needed for that quantity of gas. If we implement that, then this whole discussion is moot as there will no be energy use associated with compression.

**Comment by qlangfitt** [comment]
@myjabbar that's an interesting point about the difference between the start of the time series and later. I don't think OPGEE has any way to model different emissions at different points in the well life - it's more of a steady state model.

**Comment by myjabbar** [comment]
@qlangfitt If we use annual averages of production (oil, water, gas, and CO2) and injection (water and CO2) from simulation profiles or real historical field data, then we could use OPGEE to model the same field on a time series basis. This give us important information on how the CI evolves with time.

**Comment by myjabbar** [comment]
@JSRuthe The comment from @qlangfitt to incorporate the recycle gas compression is updated in the model. Can you please confirm this? If yes maybe, we can close this issue?

**Comment by smasnadi** [comment]
@qlangfitt @myjabbar 
- Cell M75 (in new version) is modified to account for only the amount of gas that is fresh
- I also returned back "Adjusted volumetric flood gas injection rate" cell (B54) for any future need. 
- My impression is that GFIR is the TOTAL amount of gas (fresh+recycled) that is supposed to be injected for any operation (instructed by reservoir engineers)
- Regarding natural gas flooding: as well stated by qlangfitt, for CO2-EOR that I developed, gas flooding comp only takes care the part of fresh CO2 injection, and the recycled CO2 is taken care by CO2 injection compressor. But seems that things are NOT the same for natural gas injection. If you run field 23 (Marun) which is gas flooded field, you can see that Gas Reinjection compressor sheet is off and therefore, the entire gas flooded in modeled in Gas Flooding Compressor sheet.

**Comment by qlangfitt** [comment]
Edits look good for CO2.

For NG flooding, I'm still not seeing what you are. I ran Marun and the gas reinjection compressor sheet was turned "on" (and should be by the equation controlling that tag). Because of the low GOR, and onsite gas use, there was no gas remaining for reinjection and that's why the amount handled by the NG reinjection compressor was 0.

In fact, if you increase the GOR to 1000 or more such that there is gas remaining available for reinjection, the amount available will be reinjected on the Gas Reinjection Compressor sheet. Then, in addition, the total GFIR will be injected on the Gas Flooding Compressor sheet. I think that the adjusted volumetric flood rate still needs to be changed for NG flooding since this will control stream 78 and thus the amount of gas handled for cell M75. Suggest changing adjusted rate (cell M54) to the following (purpose of MAX is to avoid negative flows for bad user input where gas available for reinjection exceeds GFIR):

=IF(Flood_gas_type=1,MAX(M53-INDEX(FlowTable,TOTMMSCF,46),0), IF(Flood_gas_type=2,M53, IF(Flood_gas_type=3,M53*Perc_CO2_breakthrough/100,"ERROR")))

**Comment by smasnadi** [comment]
@qlangfitt I see, yes when I increased the GOR I could see what is going on. I fixed cell M54 as you suggested. Thank you!
