### ISSUE TITLE
Offsite Emissions are 0 (Cell AK19) in Oct 23 download in the Active Field

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#289]
With the new GHG summary, offsite emissions are zero in the Active field (Cell AK19)

In cell G225 in Active Field Sheet

@smasnadi @JSRuthe Suggestion please replace with 
=('GHG Summary'!G117+'GHG Summary'!H117)/'Energy Summary'!F128*1000000

**Comment by smasnadi** [comment]
@JSRuthe @myjabbar 

Addressed as suggested by Muhammad
