### ISSUE TITLE
Wellhead pressure assumption

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#290]
I'm wondering where the 1000 psi wellhead pressure default in OPGEE comes from? I read a [paper](https://doi.org/10.1038/s41467-020-14606-4) recently out of Argonne and Aramco (published in Nature Communications) that used 50 psi as the wellhead pressure. Is 1000 psi supposed to represent a pressure after boosting, and if so, is OPGEE missing boosting? This is a more general question since the pressures are just so far apart.

**Comment by qlangfitt** [comment]
Note that this is related to issue #11, so perhaps you've already thought deeply about it.

**Comment by arbrandt** [comment]
It all depends.

Yes, 1000 psi is the default wellhead pressure. The wellhead pressure is choked at this, even if it would be higher coming from formation etc. A typical formation will sit at hydrostatic gradient pressure when found, which is 0.43 psi per foot (weight of a column of water). Thus, a field about 2300 ft deep will typically be found at 1000 psi.  We default reservoir pressure to 1/2 of hydrostatic, to account for pressure drawdown during field operation. As depletion progresses, the reservoir pressure, and following from that wellbore and wellhead pressure, will drop.

We do have boosting after separation if low pressure fluids come into the separator. I have in the last few days fixed a number of bugs with the 3 stage separation boosting compressors. Each compressor takes the gas from the pressure of that stage to the processing/transport pressure of 1000 psi.

50 psi is quite depleted. OPGEE can run this low, but the z-factor calc seems to crash a lot when it drops below 100 psi or so. I think we are handling low pressure fields reasonably well now with the bug fixes of the last few days.
