### ISSUE TITLE
Energy Summary Table 3 Electricity Imports not including sour gas reinjection compressor

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#291]
This showed me a lot of errors in the following sheet's respective cells.

First I fixed,

Sour Gas reinjection compressor cell M78 and M79 changed to M77 and M78.

A similar fix needs to be done for **CO2 reinjection compressor**, M66, and M67 changed to M65 and M66.
  **VRU compressor** M63, and M64 changed to M62 and M63.
**Storage Compressor** M62, and M63 changed to M61 and M62.
**Post-Storage Compressor** M62, and M63 changed to M61 and M62.

Then in Electricity Gen and Imports sheet,

Cell M45, please change to 
='Sour Gas Reinjection Compressor'!I91

After making this all changes, the CI for CO2-EOR looks more representative compared to literature.

@JSRuthe @smasnadi . Can you please confirm these changes?

**Comment by smasnadi** [comment]
@myjabbar I am gonna check thin tonight

**Comment by smasnadi** [comment]
@myjabbar @JSRuthe Thank you Muhammad to find those items. All of them are checked and fixed in the updated version.
