### ISSUE TITLE
VFF (only Venting and Fugitives) CO2 sour gas injection using component fugitives model

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#292]
VFF only Venting and Fugitives for CO2 sour gas injection (with more than 2% and up to 15% H2S) looks overestimated.

**Flaring** 
Almost zero once the CO2 breakthroughs with >80% CO2 content. This is also confirmed by looking at Joffre CO2 flood Flaring volumes
https://www.petrinex.ca/PD/Pages/APD.aspx - 

**Venting**
The Venting in OPGEE shows around 1.8% of gas injection volumes which looks higher for CO2 flood (sour gas injection and high H2S content). This is also confirmed by some literature for a closed-loop system venting is almost zero. 
For Joffre floods, it's almost 0.14%. The data for venting is available at https://www.petrinex.ca/PD/Pages/APD.aspx - 

**Fugitives** 
The literature for Weyburn CO2-EOR flood reported shows 0.5m3/d (Mackay et al. 2019). The OPGEE model fugitives for the case I am running (CO2 and sour gas injection path 6 with no injection for fresh CO2 so gas flooding compressor is made 0 ) is coming from pumps, sour gas compressor, and mainly from gas gathering system (67%). Is this the difference is because the study is mainly for Weyburn study is for well-head only and not for OPGEE is taking into account all the components?

**Comment by JSRuthe** [comment]
@myjabbar I'm closing this issue since I'm addressing comments on gas injection in issue #300.
