### ISSUE TITLE
On-site tanks - vents not accounted for on well and downhole pump

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#293]
On the Well and Downhole Pump sheet, the type of emissions represented by each VF stream is designated in a table starting at Row 90. The last entry (On-site tanks - vents) has a 0 for "fugitive?" and "vent?". Should have a 1 for "vent?" in cell O93.

**Comment by JSRuthe** [comment]
Commit 906918759616a1e2876b86df5176265b8247f81e is supposed to reference this issue
