### ISSUE TITLE
Gas flooding compressor Cell E18

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#294]
Gas Flooding compressor cell E18 although it doesn't make any difference in the results. Do you think we can replace with the following equation 

@smasnadi @JSRuthe 

=IF(Flood_gas_type=3,IF(Gas_processing_path=6,(M53*'Fuel Specs'!H123)-'Sour Gas Reinjection Compressor'!J18-'CO2 Reinjection Compressor'!L18),0)

**Comment by smasnadi** [comment]
@myjabbar @JSRuthe 

When we do sour gas re-injection, CO2 reinjection compressor block is basically OFF and subtracting with {'CO2 Reinjection Compressor'!L18} might be confusing for developers.
