### ISSUE TITLE
VFF in Active Field Cell AK16 missing drilling and development and Exploration VFF

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#295]
Suggestion @smasnadi 

Please include the following equation in Cell **G172**
='GHG Summary'!G113*('GHG Summary'!J8+'GHG Summary'!K8+'GHG Summary'!L8)/'Energy Summary'!F128*1000000

in cell **G178**

='GHG Summary'!G113*('GHG Summary'!J8+'GHG Summary'!K8+'GHG Summary'!L8)/'Energy Summary'!F128*1000000

**Comment by smasnadi** [comment]
@myjabbar 
Thanks! Fixed. For G178 I guess you meant:

='GHG Summary'!G113*('GHG Summary'!J9+'GHG Summary'!K9+'GHG Summary'!L9)/'Energy Summary'!F128*1000000
