### ISSUE TITLE
Active Field Surface Processing (Cell G189)

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#297]
Cell **G 189**

Can we replace it with the following:

='GHG Summary'!G113*(('GHG Summary'!H11+'GHG Summary'!I11+'GHG Summary'!H18+'GHG Summary'!I18)/'Energy Summary'!F128*1000000

@smasnadi

**Comment by smasnadi** [comment]
@myjabbar 
We are essentially calculating what you are suggesting (since GHG Summary'!H16 is 0). But I think we prefer to keep it this way in case if other combustion emissions got modified later.
