### ISSUE TITLE
Default fraction of tanks w/ VRU

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#298]
I'm wondering what the default fraction of tanks w/ VRU should be on the secondary inputs sheet. It used to be 70%. Now the sheet says the default is 100% and the value in the "user" cell is 44%. I assume that either new data came out suggesting 44% to be more accurate or it was changed for some specific application and never changed back. Either way, should fix the 100% default to whatever the actual default should be.

**Comment by JSRuthe** [comment]
Yes, this is based upon new analysis of GHGRP data which I did for my paper.

This is a population-level fraction for the United States, so I think it is safe to use as a default value. I'll make a note of the source

**Comment by JSRuthe** [comment]
Corrected with 0bf6fb1ebb1839cc7968832b971872df74c28a75

**Comment by qlangfitt** [comment]
I see you added the note that it should be 44%, but the default box is set at 5%. Most users won't even look at the secondary inputs, so I think it's important for it to come out-of-the-box with the right defaults.

**Comment by JSRuthe** [comment]
Hi Quinn, sorry I should have been clearer. With the latest commit, I divided the 44% control fraction between VRUs and small flares. All equations have been adjusted accordingly. See below:

![image](https://user-images.githubusercontent.com/42356585/101385101-8eec1680-3878-11eb-9c7a-e9b4aa9b16a1.png)

**Comment by qlangfitt** [comment]
Oh makes sense! Closing.
