### ISSUE TITLE
Circular reference for AGR injection and venting when gas processing path=7

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#299]
On the Acid Gas Removal sheet, the amount of CO2 vented (Stream 256) and the amount of CO2 to reinjection (Stream 73) are calculated based on one another when the gas processing path=7. This causes the model to sometimes fail, or if not to fail, to generate non-deterministic outcomes. One of these streams should be calculated independently, though I'm not sure which. Probably the tail gas CO2 to reinjection.

**Comment by arbrandt** [comment]
Fixed in change that also removed the claus unit, which was error prone and will be added in a future version.
