### ISSUE TITLE
Gas Flooding Compressor

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#30]
When running Sleipner Vest, the fuel consumed from the gas flooding compressor wreaking havoc on the "Fuel Gas Imports". 

It appears that the compression ratio, N_comp_GFC, was modified such that if there is no gas flooding, "NA" is returned. However, the rest of the workbook does not know how to handle an "NA" N_comp_GFC, and the output natural gas consumption is "#VALUE"... leading to problems in the fuel gas workbooks.

**Comment by JSRuthe** [comment]
This is a general issue for all CCS fields: inc. Sleipner, Gorgon, Jansz Io

**Comment by arbrandt** [comment]
I am not seeing this issue. I am thinking this was fixed and not closed.
