### ISSUE TITLE
Cause of high methane emissions from injection wells

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#300]
CC: @myjabbar, this may be related to problems described in your issue 

Currently, gas injection and compression equipment are handled using a method similar to the component-level approach for on-site equipment. We take the same emissions vectors from Rutherford et al 2020 for production wellheads and reciprocating compressors and use these for injection wellheads and compressors. 
 
The important detail here is that the loss rate fractions are calculated as averages for the US population and are not disaggregated based on well productivity tranches. Because the loss rate fractions aren’t disaggregated by productivity tranche, we see a bias towards the higher loss rate fraction of low productivity wells. The reason we are seeing high CI contributions from injection equipment is that it is possible to combine a high average loss rate (based on this bias towards high loss rates of low productivity wells) with some very high gas injection volumes (e.g., Alaska North Slope).

The following fix is proposed:
- The loss rate fraction for gas injection equipment should not be based on the average for the US population. It should be based on the rate of gas injection per well.
- Gas injection throughput per well is unlikely to display the same variability as production wells. So rather than calculating gas injection per well based on some smart default of injection wells counts, it is suggested that the gas injection throughput per well be set as a constant based on reported volumes.

We are currently searching for a dataset to determine a reasonable smart default for gas injection per well.

**Comment by JSRuthe** [comment]
Based on difficulties with finding datasets reporting gas injection throughput, we make the following assumptions:
- counts of injection wells are related to count of production wells based on an inverted five-spot pattern (1 injection well for every four production wells.
- injection volume per well is calculated based on the throughput at the injection well sheet (calculated in OPGEE) divided by the number of wells assumed above.

As we describe in the previous post, this injection throughput per well is used to assign fraction loss rate by tranche

**Comment by qlangfitt** [comment]
I think think the loss rates shouldn't check if GOR>GOR_VF_cutoff (Secondary Production Column G and randomized EF table), , they should just use the gas well loss rates because we are modeling the gas injection wells like gas production wells regardless of the production GOR.

**Comment by JSRuthe** [comment]
This issue should be fully addressed based on the above commits
