### ISSUE TITLE
Fuel cycle offsite emission for CO2-EOR

### ISSUE THREAD

**Issue by smasnadi** [arbrandt/OPGEE#301]
The fuel cycle emission for CO2 used in CO2-EOR should only be account when natural CO2 for injection is selected by the user. However, currently OPGEE accounts for offsite CO2 emissions for both natural and anthropogenic CO2-EOR (GHG Summary cell G101).

**Comment by smasnadi** [comment]
GHG Summary G101 is modified: 

=IF(Source_CO2=1,G96/44/mol_per_scf*'Fuel Specs'!B223/1000000*'Fuel Cycle'!D79,0)

**Comment by myjabbar** [comment]
@smasnadi

Do you think CO2 source and transport emissions to be included in the Gate-to-Gate emissions estimate by OPGEE. 

Similar to anthropogenic CO2 source fixed above, CO2 source and transport emissions to be **excluded** in my opinion for the gate-to-gate emissions. Also the estimates of CO2 source and transport assumes 8.3% of CO2 emissions lost from extraction, production and transport compared to CO2 injection. The estimate is assuming the same CO2 emissions for all the CO2 extraction natural sources (McElmo Dome, Sheep Mountain and Bravo Dome) and respective transport distance (>100- ~ 500 miles). How about if we can have a range of estimate for CO2 extraction and transport from the different CO2 sources.

![image](https://user-images.githubusercontent.com/56744404/130681770-f7815bb6-2b3c-4f4f-b45d-6459e72fa51b.png)
R. W. Matthew Wallace; Lessly Goudarzi; Kara Callahan, “A Review of the CO2 Pipeline Infrastructure in the U.S.,” 1990.
