### ISSUE TITLE
Small Sources Emissions (0.50 gCO2eq/MJ)

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#302]
@smasnadi @JSRuthe 

Do you think instead of default **0.5** gCO2eq/MJ, we can further define the value.

In particular for a CO2 flood 
- **Low** value of **1** kWh/bbl oil- compression-only and sour gas injection (path 6) and naturally flowing wells (no AL)
- **Mid-range** value of **5** kWh/bbl oil -compression-only and sour gas injection (path 6) and AL wells (ESP's)
- **High-range** value of **8** kWh/bbl oil - compression, NGL separation (path 7 and path 8) and AL wells (ESPs)

The values are from other sources from US DOE NETL (2009). (Table 3-6)

The idea is to proportionate to the gate-to-gate GHG emissions. Otherwise, it would add 0.5 gCO2eq/MJ for a field with gate-to-gate of 5 and 10 gCO2eq/MJ.

**Comment by smasnadi** [comment]
@myjabbar I think for the small source of emissions that 0.5 gCO2/MJ is just a very rough estimate and we do encourage a user to alternate this number based on his special case study (like the one you describe above).

Adam and I had an idea to change this 0.5 gCO2/MJ to % of total GHG emissions (e.g., 5% of total GHG).
