### ISSUE TITLE
Sour Gas Injection Wells and Gas Dehydration Sheet

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#304]
@smasnadi @JSRuthe 

**Sour Gas Injection Wells sheet**

Cell **M39** _0.001186_ fractional loss rate and calculates the Fugitive Loss rate. Although Fugitives calculated are not taking into account in calculations, may just make it zero to be consistent with the note in **Cell Y39**

**Well and downhole pump sheet**

For the Well-head Fugitives in Cell **M98**, to be consistent with injectors above for Sour Gas injection (with H2S), can we make a fractional loss rate =0% for produces as well?

**Gas Dehydration sheet**
In cell F196, I think we mean hear **Venting** (labeled as Fugitives) emissions as calculated in the flow out of process table at the top of the sheet.

**Comment by JSRuthe** [comment]
1) I think it is reasonable to assume 0% fractional loss rate at sour gas injection wells. This was my mistake, based on the note we have always assumed that but I made an error in my modifications last month.

2) We will not modify the fractional loss rate of wellheads for the main OPGEE version. You'll need to make that assumption based on the best available information for your case study.

3) Emissions from gas dehydration units are based upon site level surveys which could involve any number of emissions (both venting and fugitives). I will label appropriately.

I'll make the modifications for (1) and (3) and then close this issue

**Comment by JSRuthe** [comment]
see 62668a595bec56e952e2ded9bcc7185ece5c7134

**Comment by JSRuthe** [comment]
@myjabbar Closing this issue since I'm addressing comments on injection wells in issue #300
