### ISSUE TITLE
(BUG) Mismatch between gas capacity at given pressure and working pressure (Separation Tab)

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#307]
Hi, I find a mismatch in the calculation of the number of separators required under the Separation Tab. For the high-pressure separator, the working pressure has 720, 1000, 1200 and 1440 psi. Total four different levels. However, the pressure to calculate gas capacity has 600, 800, 1000, 1200 and 1440 psi. If the field's nearest working pressure choose 720 psi,  the gas capacity per separator shown an error.

Additionally, the following link no longer exists.
![separator working pressure](https://user-images.githubusercontent.com/44585380/103397449-51804f00-4aed-11eb-9b35-f4850439a20e.png)
http://www.surfaceequip.com/two-three-phase-vertical-horizontal-separators-gas-scrubbers.html

**Comment by arbrandt** [comment]
It appears that this website is down or no longer exists. The original data table can be accessed on archived versions of the website on the internet archive. I have adjusted the table by making the number of rows and columns equal in terms of sizes. the 800 psi column is removed from the gas capacity table, and we apply the values at 600 psi to the working pressure at 720 psi. This is a conservative estimate, as separator gas capacity for that volume of separator should be larger at 720 psi working pressure than at 600 psi. So we will not under-estimate number of separators needed. Code should now avoid the error.
