### ISSUE TITLE
Misaligned Results Tab outputs for Fugitive Methane

### ISSUE THREAD

**Issue by dxgordon** [arbrandt/OPGEE#309]
In Results Tab: Fugitive Venting and Methane Emissions outputs are misaligned in Rows 202-253.

**Comment by arbrandt** [comment]
@JSRuthe , did you fix this in your commit? If so, please close this issue

**Comment by JSRuthe** [comment]
addressed via d14704730b4a2dc6ca027f2aa5b135fa6178f16a
