### ISSUE TITLE
Heavy time load on vf - components sheet

### ISSUE THREAD

**Issue by arbrandt** [arbrandt/OPGEE#313]
Used excel profiler to find speed issues. The following issue appears on vf-components sheet:

Cells I86:SN86, I101:SN101 etc. have many (1000s) of =RANDBETWEEN(1,1000). These are volatile, and thus recalculated at each worksheet recalc. 

We need to think about how often those need to be re-shuffled? Each uncertainty iteration? Each worksheet re-open? Each field in a set of fields?

After that we can move it into the macro and only recompute when we actually need to.

**Comment by JSRuthe** [comment]
Revisions made in commit 4fe34c61e6ca65cd34ed394931eefcef04a55510

However, removing the volatile functions has not significantly affected overall speed of uncertainty calculations. 

For one uncertainty realization, the largest time loads apprear to occur during smart default draws

![image](https://user-images.githubusercontent.com/42356585/108779524-3e559280-7524-11eb-87e3-c78a31129a88.png)
