### ISSUE TITLE
Two small errors in pressures along gas stream with no impact on CI calculations

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#315]
There are two small errors/inconsistencies in pressures along the gas pathway. Low priority issue since no effect on fuel use calculations.

1.  Stream 32 (Crude Oil Stabilization sheet) has a compressor prior to it that brings it up from 100 psi (the Stream 8 pressure) to the line pressure (500 psi by default). However, the outlet pressure in stream 32 doesn't reflect this and still shows the 100 psi figure.
2. On the Flow Sheet CP29 (Stream 89) references the cell that says "computed" rather the actual pressure cell (should reference Demethanizer L32). Also, the pressure in that cell (Demethanizer L32) should be changed to reflect the line pressure (make it equal to the feed pressure in Stream 37).

**Comment by arbrandt** [comment]
Fixed. Great catch!
