### ISSUE TITLE
Transmission compressors initial compression

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#316]
The Gas transmission compressors sheet has compressors to handle bringing the pressure back up periodically throughout the line. However, I assume the gas needs to be up to pressure at the point of injection as well, so seems that this initial compressor needs to be added.  For example, in the default scenario, the assumed outlet pressure from each compressor is ~1750 psi, so need a compressor to initially bring the 500 psi stream out of processing up to the 1750 psi for injection to the pipeline.

**Comment by arbrandt** [comment]
Fixed. Added an initial compressor that takes it from the gas system pressure in field to the transmission outlet pressure. Then the boosters are added with the transmission inlet and outlet pressures.
