### ISSUE TITLE
Model breaks if no flaring data for specified country

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#317]
LCFS dataset has a field in Belize, which is not in the flaring lookup table. Suggest adding a global default for countries not in the lookup table in Active Field K125 (maybe equal to the uncertainty mean of 143.1). Could use IFERROR function.

**Comment by arbrandt** [comment]
Fixed. Now K125 pulls the mean of the uncertainty distribution, 143.1, if no country matches and the vlookup fails. This will also catch spelling errors in country name, which has been a persistent annoyance.
