### ISSUE TITLE
CO2 mass balance check error

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#319]
Slight mass balance error occurs w/ CO2 flooding because the outputs on the Flow Sheet references cell CG14 (stream 80) under the "reinjected" total when it should reference CS14 (stream 92). This is because the fugitives that are removed to get from stream 80 to stream 92 are already counted in the VF portion of the mass balance, so those are double counted. Causes enough imbalance to make the model throw an error on some CO2 flooding fields.

**Comment by arbrandt** [comment]
Fixed!
