### ISSUE TITLE
Storage vapors to VRU and flaring can go negative

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#321]
If stage 3 separation is turned off, the Crude Oil Storage sheet will calculate an inlet GOR of 0 (since it's based on the conditions at stage 3 separation). This results in a higher GOR at the outlet than inlet, which OPGEE passes along to Streams 81 and 82 as negative flows.

**Comment by arbrandt** [comment]
Fixed. Now there is a "meta parameter" on the separation sheet. It pulls the last stage solution GOR, from sep stage 3 if it is a 3-stage separator, from sep stage 2 if 2-stage, etc. Now the storage tank inlet pulls from that or the stabilizer solution GOR. It should always find a nonzero value.
