### ISSUE TITLE
Diluent supply transport emissions double counted

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#322]
Diluent transport emissions have always been accounted for on the GHG summary sheet in the Indirect GHG Emissions table under the row "GHG emissions from diluent supply." At some point, it must have been noticed that diluent transport emissions were missing from the energy summary and process-level GHG summary tables and were added in. The current treatment therefore double counts these emissions as a fuel cycle debit and normal combustion emissions.

**Comment by arbrandt** [comment]
Fixed. Removed diluent transport from the indirect emissions section, as there is now a sheet for diluent transport. Changed the note to the right of the table to say that diluent imports only includes embodied emissions associated with producing diluent, and that transporting diluent is now handled on main GHG table.
