### ISSUE TITLE
Productivity Index Macro calculations

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#323]
The user inputs of oil rate, WOR, # of producers is used to calculate the average liquid rate along the input PI is used to calculate the **Pwf**. If Pwf is **negative** (which is not possible for a producer), the OPGEE macro calculates the PI until a **_positive_** Pwf is obtained. 
This calculated Pwf for the modeled fields is in the range of **50-150** psi for a reservoir pressure of around **1,500-2,000 psi** which translates into a drawdown of over **1,500 psi**. This drawdown is extremely large compared to the actual field cases.

Do you think we can revise the macro based on the well architecture (horizontal and vertical), pay thickness, permeability, and liquid rates (low (for eg. 50 psi), medium (for eg. 100 psi), and high drawdown)?

Also, the current macro takes longer than expected (**90 mins** to run 500 fields because for each field the loop runs until positive PWf is obtained). It may also be time-efficient.

Thanks,

@smasnadi

**Comment by arbrandt** [comment]
This is an excellent observation. Certainly too large a drop. 

Ideally in the long run we need to switch to a radial inflow model with thickness, permeability, etc. PI is too coarse a measure.

Is there a maximum practical pressure drawdown seen in practice? Perhaps we could shortcut that way to avoid the iteration.

**Comment by arbrandt** [comment]
Partial fix right now to increment PI by much larger value to at least get it to converge more quickly.

**Comment by myjabbar** [comment]
I am waiting on more data to present correlations on Pwf with respect to the reservoir and geological attributes.

Based on reservoir eng. experience, the drawdown for a single-phase flow regime (which is the case for most of the region) to be around 100-200 psi. 

Even if we increment by +1, the problem is the loop would still stop as soon as the **positive Pwf** is obtained. I tried with a drawdown of 100 psi to calculate revise PI as user inputs but since there are other inputs at play as well (Pr, number of producers, liquid rate) requires some more QC (currently on going), it was still going in PI macro loop.

**Comment by arbrandt** [comment]
Re-open if this is still an issue
