### ISSUE TITLE
Fraction of gas reinjection -1 switch no longer necessary

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#325]
With the change in the definition of "fraction of remaining gas reinjected" (see Issue #216), the VBA logic that deals with a -1 reinjection input is no longer needed. Now, if 1 is input, it will do exactly the thing that the -1 switch was previously doing. This is true both in theory and application, as any field that you enter -1 into will iterate to 1 using the VBA.

**Comment by arbrandt** [comment]
Fixed. Good catch.
