### ISSUE TITLE
Venting-to-oil ratio vents too much gas when gas lifting is used

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#326]
VOR is ostensibly the ratio of vented gas emissions to oil production. The way it's actually implemented is to calculate the fraction of produced gas that is vented based on VOR/GOR and then apply that fraction to the post-flare gas volume. Problem is, when using gas lifting the post-flare gas volume is huge compared to the GOR so way more gas is leaked off than the VOR would suggest. Suggested fix is to change stream 252 (on Venting sheet) to subtract the mass of recycled gas from stream 30 (i.e., subtract stream 42 from stream 30) before multiplying the VOR/GOR fraction.

**Comment by arbrandt** [comment]
Fixed. Stream 252 is now computed as fraction of gas net of re-injection, to prevent perverse behavior. Perhaps a cleaner approach would be useful in a future implementation, but this is fine and sensible for now.
