### ISSUE TITLE
Default 0 wells for oil sands breaking VBA

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#334]
Oil sands fields use a default of 0 production wells if there is no entry. The model does not like fields with 0 wells since some of the calculations are based on dividing production by well counts. Specifically, I found that the VBA breaks in response to the VF - Site - onsite productivity per site being #DIV/0!.

**Comment by arbrandt** [comment]
VF site onsite sheet now fixed to give NA in these cases and fail gracefully. If oil sands are used, we need to pull fugitives from another place, as these studies are based on driving by wellsites.
