### ISSUE TITLE
Uncertainty randomization occurring based on previous field's data

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#335]
It's a little beyond my grasp currently, but there is new VBA code near the start of the BulkAssessment that is generating arrays with random values for use in the uncertainty realizations. Some of this is based on the current field properties (e.g., site_rand_array is based on the current field site-level tranches). However, this code is run before the current field's inputs are copied to the Active Field sheet, so it is using the previous field's data instead.

Continuing on the VF - Site - onsite case, the result is that the random draw array (I61:SN70) is not sampling in the correct range as defined by the tranche high (G61:G70).

**Comment by arbrandt** [comment]
Fixed. Now the VBA code should be drawing uncertainty realizations after the active field column is cleared and reset with the new field's data. This was the wrong place to be drawing uncertainty realizations before.
