### ISSUE TITLE
Uncertainty runs >1 broken due to array issue in VBA

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#336]
On any field, if I try to run with uncertainty runs >1, the code breaks immediately. I traced this back to the Fugitives_Loop, specifically, comp_array. The array is defined with two dimensions (albeit one of them is 0), but then when it is being filled out with random values is only passed a single dimension. It seems to work to simply add a second dimension of 0 in the randomization loop as follows (though maybe there's a better solution):

ReDim comp_array(24 - 1, 0) As Variant

For i = 0 To (24 - 1)
    comp_array(i, 0) = Rnd()
Next i

**Comment by arbrandt** [comment]
Fixed.
