### ISSUE TITLE
Lack of calculation inside smart default loop leads to some wrong smart defaults

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#338]
The smart defaults now work by first filling the generic field column into the active field sheet, then calculating, then copying over all non-blank inputs from the current field, then going through each blank input one by one in a loop to pull in the corresponding smart default.

It used to be that the script would "calculate" with every iteration of that loop so that if a smart default value from above is used in a subsequent smart default, the change is captured. It looks like that feature was commented out - I assume to speed up the script. However, this causes incorrect behavior. I propose the compromise below, where I added in the highlighted ActiveField.Calculate. This causes just the active field sheet to recalculate and does not seem to add a noticeable amount of time to the run speed. This block of code is just before Time4.

![image](https://user-images.githubusercontent.com/47186327/112392044-0faf1100-8cb6-11eb-8c68-c564296592d8.png)

**Comment by arbrandt** [comment]
Good catch! That is almost certainly what happened. Implemented your fix, and like the approach to only calculate the active field sheet. I seen vitually no slow down with this approach.
