### ISSUE TITLE
Productivity index skipped in uncertainty draws

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#339]
Uncertainty draws on the Active Field sheet are done in VBA and are specified by the object "RowsToProcess". The row that corresponds to the productivity index (28) is simply skipped. I assume this was just an oversight (or perhaps does it have to do with the fact that VBA can adjust the PI elsewhere?). Either way, this means that a new random number is not drawn in Column T of the Active Field sheet for PI and thus the existing number in that column (0.20) is static and always draws a PI of 5.7 in uncertainty mode.

Need to add 28 to the list of numbers in "RowsToProcess".

**Comment by arbrandt** [comment]
Fixed in push just now. I can't see why this would have been done purposely, so it seems likely to be an oversight? Perhaps the PI fix was not robust before so it was disabled to prevent errors?
