### ISSUE TITLE
Flare of H2S vs vent

### ISSUE THREAD

**Issue by arbrandt** [arbrandt/OPGEE#34]
Right now, the AGR unit is venting the associated sour CO2. This is fine if there is no H2S but is likely to be dangerous if H2S in gas. Should include destructive flare for H2S oxidation instead of venting

**Comment by wennanlong** [comment]
Hi Adam,

I was think of the possibility and feasibility of doing this type of research.

Assume if we could obtain global SO2 concentration data (x, y,z, t, DU) from other sources say NASA, then based on what we have, the location of oil/gas field (x, y, z), we might be able to monitoring above the oil/gas field, i.e. how does SO2 emissions change with time?

Thus, we could (1) know the oil/gas field is faring or not, (2) estimate how much scf of sour gas flaring by using the model.

please review the following reference material about sour gas flaring.

I will start working on the TEOR modeling tomorrow

Regards,

Wennan


[Sour gas flaring project (README FIRST).pdf](https://github.com/arbrandt/OPGEE/files/2527367/Sour.gas.flaring.project.README.FIRST.pdf)
[IEA Outlook for Natural Gas 2017.pdf](https://github.com/arbrandt/OPGEE/files/2527383/IEA.Outlook.for.Natural.Gas.2017.pdf)
[Sour gas mega projects SPE 175361.pdf](https://github.com/arbrandt/OPGEE/files/2527384/Sour.gas.mega.projects.SPE.175361.pdf)
[A global catalogue of large SO2 sources and emissions.pdf](https://github.com/arbrandt/OPGEE/files/2527385/A.global.catalogue.of.large.SO2.sources.and.emissions.pdf)
[WEO2017Excerpt_Outlook_for_Natural_Gas.pdf](https://github.com/arbrandt/OPGEE/files/2527386/WEO2017Excerpt_Outlook_for_Natural_Gas.pdf)
[Gas flaring emissions estimation.pdf](https://github.com/arbrandt/OPGEE/files/2527387/Gas.flaring.emissions.estimation.pdf)
[basics of gas flaring EPA Ohio.pdf](https://github.com/arbrandt/OPGEE/files/2527388/basics.of.gas.flaring.EPA.Ohio.pdf)

**Comment by arbrandt** [comment]
Fixed, as Mohammad includes combustion flaring emissions from the claus unit for the destructive H2S incineration flare.
