### ISSUE TITLE
Uncertainty means vs. deterministic defaults

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#340]
The gas lifting injection deterministic default is very different than the uncertainty mean.

Why is there no range on the VOR uncertainty?

The flaring deterministic default is based on the country-level data. Should the uncertainty distribution follow the country selection as well?

**Comment by arbrandt** [comment]
Good catches. Fixes applied as follows:

1. GLIR deterministic default set to the uncertainty mean. We need more data on this parameter.
2. VOR uncertainty range was there but small. Made the following changes: Mean 10, SD = 5, max = 100, distribution = lognormal. We need more data on this parameter. Maybe with satellites launching we will get a better estimate for this in mid 2020s. Currently no jurisdiction reports venting as a substitute for flaring, though we do know that it can occur in some cases.
3. Good call. Flaring uncertainty mean is now country average. Flaring uncertainty SD is now 1/3 of the mean. Thus, 95% of fields will fall between 0.33 and 1.66 the country mean. As we get more data worked out, we can give a better range than this.
