### ISSUE TITLE
water reinjection turn on and num_of_injector = 0 will crush the excel

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#341]
When the water reinjection = 1 (under the section of production methods), and the Number of water injecting wells = 0, then the excel will have an attached error message.
[https://drive.google.com/file/d/1sNovG5swFjvMzIjbff0MNEHErIdu36ZG/view?usp=sharing](url)

**Comment by arbrandt** [comment]
Fixed with wennan's new data consistency checking code. See fields 304 for example implementation that triggers it.
