### ISSUE TITLE
OPGEE instability issue

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#343]
First time download OPGEE from Github and run works. But if the user saves the spreadsheet, close it and reopen it and run it again it will generate this error.

Please check [https://drive.google.com/file/d/1JWoDfJZ0FBd0aa1dRGB4dviKpxbA6LJn/view?usp=sharing](url).

**Comment by arbrandt** [comment]
Wennan, is this issue still happening. I cannot reproduce this on my machine. Please check to see if it is still doing it.

**Comment by wennanlong** [comment]
The current version has no such issue
