### ISSUE TITLE
Gas coming out stabilization at 1000 psi

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#346]
At some point back, the pressure along the gas processing chain was changed from 1000 psi to 500 psi. I assume that change was intended to apply to any gas stream, but it seems that if the only gas is coming off the stabilizer, then later parts of the gas processing chain end up at 1000 psi. This is controlled on the Gas Gathering sheet, cell M32.

I assume this was just an oversight when changing the default pressures and should be set to 500 psi.

**Comment by arbrandt** [comment]
Fixed. Was an oversight as you note.
