### ISSUE TITLE
Demethanizer inlet boosting compressor calculations based on outlet compressor's compression ratio

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#347]
On the Demethanizer sheet there is both an inlet boosting compressor and outlet boosting compressor. The inlet compressor's adiabatic W Comp. (M51) and Outlet Temp (O51) both erroneously refer to the compression ratio for the outlet compressor. Change to reference inlet compression ratio.

**Comment by arbrandt** [comment]
Fixed. Great catch, must have been a copy paste issue.
