### ISSUE TITLE
Primary input checks fail when input left blank, not just 0

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#348]
Primary input checks were added to ensure that water injection and steam injection are not used with 0 injectors. Since VBA treats blank cells as 0s, this code kicks out the error and exits the run when number of injectors is left blank. This is not desirable behavior because it would preferable to let it run and draw a smart default for the number of injectors.

Easy solution is to add to the If statements in the VBA check an additional term checking "And Not IfEmpty(...)". See below for example on water injection. Same needs to be done for steam injection.

 If (Worksheets("Inputs").Range("G10").Offset(0, i) = 1) And (Worksheets("Inputs").Range("G26").Offset(0, i) = 0) **And Not IsEmpty(Worksheets("Inputs").Range("G26").Offset(0, i))** Then

**Comment by arbrandt** [comment]
Fixed in commit just now.
