### ISSUE TITLE
Default gas composition

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#349]
KeyLogic has done the work of organizing a dataset of natural gas composition samples. Using the data presented in the study, found [here](https://www.osti.gov/biblio/1529553-life-cycle-analysis-natural-gas-extraction-power-generation), we can developed a weighted average gas composition which should make more sense for OPGEE Defaults.

**Comment by arbrandt** [comment]
Added 0.01% H2S to make sure it sums exactly to 100%. Was causing a error window to pop up.

**Comment by arbrandt** [comment]
Is this uncertainty treatmentsufficient Jeff @JSRuthe? If so, please close issue.
