### ISSUE TITLE
Gas flooding compressor uses CO2 pressure even if injecting NG or N2

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#350]
The gas flooding compressor checks which type of gas has a positive flow rate when calculating the required compression ratio (Gas Flooding Compressor M60) and uses the pressure of that stream. However, the first check is whether the CO2 flow rate is >=0. Because of the "=", OPGEE will always select this pressure, even if NG or N2 is the flood gas. Change to simply >0.

**Comment by arbrandt** [comment]
Fixed. Good catch!
