### ISSUE TITLE
Updating flaring calculator in OPGEE

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#354]
Calculations for flare efficiency rely on a model which requires several difficult-to-find parameters (e.g., wind velocity and flare diameter) for accurate calculations. These are rarely available.

A simpler calculator for flare efficiency is probably more useful.

Suggest the following model:
- Flare combustion efficiency: Based upon the probability distribution of Gvakharia et al (mean efficiency = 96%)
- Fraction of flares unlit: A default value of 5% should be used based on PermianMAP
- Overall flare efficiency: Weighted average of above two value using GHGRP formula:
![image](https://user-images.githubusercontent.com/42356585/116940364-1886f100-ac2b-11eb-975f-c24fe7871e06.png)

A separate stream of "Fugitive CH4 from flare" can be created which should be connected to VFF outputs.

**Comment by arbrandt** [comment]
Updated Th may 6th 2021. Collected field-measured flaring measurements from 4 sources (Nigeria, US, Canada, etc.). The model now generates the mean for use in deterministic cases and draws one flare measurement for uncertainty cases.
