### ISSUE TITLE
Diluent transport based on crude oil volume, not diluent volume

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#356]
For diluent transport calculations, the energy production rate is based on the crude oil production volume (Diluent Transport M111). Crude oil transport is covered on a separate sheet. Instead, it should only be the daily energy rate of diluent here. 

Propose to change M111 to: =INDEX(FlowTable,E_LHV_O_btu,16)

**Comment by arbrandt** [comment]
Agreed, and fixed.
