### ISSUE TITLE
What's the purpose of the diluent adjustment factor if the diluent energy content is part of the CI denominator?

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#357]
I was digging into some diluent questions and noticed that the energy content of diluent is included in the energy export and therefore the CI denominator in OPGEE 3.0. This is different than OPGEE 2.0 which does not include the diluent energy in the CI denominator.

My understanding is that the diluent adjustment factor is intended to take the CI calculated by OPGEE and reduce it in the case of dilution to account for the additional energy in the final product (i.e., the added energy from the diluent). So should the dilution adjustment factor be removed in OPGEE 3.0? Would like to hear your thoughts.

**Comment by arbrandt** [comment]
This was a hold over from 2.0 that does not make sense given the current implementation. Including BOTH the DAF and the diluent in the denominator results in inconsistent and confusing results when running cases that scale diluent for simple pahtways from 0% to 100% in increments. I have removed it in favor of keeping diluent in the denominator, as that seems the more clear and consistent approach.
