### ISSUE TITLE
The gas specific gravity in Fuel Specs Tab is calculated wrong

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#365]
In the Fuel Specs tab, the gas_SG is calculated using the sum-product of gas density @ STP (tonne/mmscf) and mole fraction and divided by the wet air molecular weight (g/mol). It does not have unit conversion factor to make unit consistant

**Comment by arbrandt** [comment]
Fixed! Good catch. Now use CRC standard air molecular weight:

Molar mass standard air |   | 28.96 | g/mol | CRC, 1983, cited from https://www.lmnoeng.com/idealgas.php
-- | -- | -- | -- | --
