### ISSUE TITLE
Old tank flashing data

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#366]
Tank flashing was cleaned up and adjusted to match with the paper, which I presume changed because of COM checks being incorporated. Wondering if the old tank flashing data should be removed to avoid confusion or if it still serves a purpose? (VF - Component rows 339-347)

**Comment by JSRuthe** [comment]
Yes, this is a good point. It is no longer required. I will go ahead and remove with a commit later today
