### ISSUE TITLE
Change fraction of tanks with controls to match the default

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#370]
On the secondary inputs sheet, the fraction of tanks with controls in the user column is different than the default column. Should update that to align. Otherwise, I checked all other secondary inputs and they align with the defaults.

**Comment by JSRuthe** [comment]
OK, the fraction of tanks with controls wasn't aligned with my latest #'s, so needed to adjust accordingly (changed by ~5%)
