### ISSUE TITLE
Fields with FOR entered but not GOR fail input screening

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#371]
If a field has a FOR entered, but the GOR is left blank, the inputs screening will error it out. Just need an And Not statement to check GOR (currently only has it for FOR). Also should probably allow the model to run if GOR=FOR (especially the case of the user entering 0 for both). The following code works for the first line of the IF statement:

If (Worksheets("Inputs").Range("G86").Offset(0, i) > Worksheets("Inputs").Range("G46").Offset(0, i) And Not IsEmpty(Worksheets("Inputs").Range("G86").Offset(0, i)) And Not IsEmpty(Worksheets("Inputs").Range("G46").Offset(0, i))) Then

**Comment by JSRuthe** [comment]
Hi Quinn, I'm not able to replicate this. Can you try again on the latest version and let me know what column you're running?

**Comment by qlangfitt** [comment]
Just downloaded the most recent version and can make the first thing happen with field 1 (generic). Simply delete the GOR so that it is blank. Then run the model and you'll see if fails the input screening check (the results sheet shows nothing in the outputs section and just produces an error message). This is done in the VBA input screening and doesn't cause the model to crash or anything, just to skip the field.

For the second one, instead of deleting the GOR set it to 143 (equal to the FOR). You'll see the same thing happens.

The code I provided that would solve these problems goes into the VBA module "Primary Input Screening" at line 46. These seem like small things, but some of these cases come up in our modeling and it would be helpful if it didn't error out.

**Comment by JSRuthe** [comment]
Got it, this makes sense.

**Comment by qlangfitt** [comment]
The fix implemented only addressed the first problem (by adding the And Not), but not the second (which needs >= changed to >). Would be very helpful if the model didn't fail when GOR=FOR. We have a few fields (e.g., oil sands fields) with both GOR=0 and FOR=0, which should clearly be allowable, but OPGEE throws out.

**Comment by arbrandt** [comment]
Fixed with > logic rather than >=
