### ISSUE TITLE
Methane slip at flare not plumbed into calculations at bottom of sheet

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#372]
Methane slip from flaring was added as a separate stream recently. The stream was added on the Flaring sheet, on Venting & Fugitives 3.0, and on the Flow Sheet. However, the GHG Summary sheet (and eventually Active Field) draw from the emissions calculations at the bottom of each process sheet. Need to add the methane slip from flaring to the fugitive emissions at the bottom of the flaring sheet (F89) in order for OPGEE to ingest it.

**Comment by JSRuthe** [comment]
This is an accounting question, which is somewhat subjective. Currently, the methane slip is being counted but it is being counted under the flaring category. Notice that the "Flaring" category at the bottom of the process sheet includes the sum of both the combusted gas CO2eq and the non-combuted gas CO2eq. Whether or not the non-combusted gas should instead be counted as "Fugitives" is up for debate

**Comment by qlangfitt** [comment]
Ah yes I see. I think it's fine to leave it categorized as "flaring" then.

Really small thing while we're on this, but it looks like the CH4 in the methane slip stream is slightly different than the amount in the calculation on the sheet. Reason being that the calculation on the sheet is based on the gas to flare stream (from which the fugitives have already been subtracted). Numbers would align more perfectly if the calculation on the sheet either was based on the sum of streams 28 and 84 or if the non-combustion emissions in the calculations section just referred to the methane slip stream values.

**Comment by JSRuthe** [comment]
I like the second solution you've offered here
