### ISSUE TITLE
the stream 28 (gas after separator): using wrong density to calculate gas mass rate

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#376]
The stream 28 under the Separation tab has the separator outlet temperature and separator outlet pressure. However, when calculating the density, stream 28 uses density (I121 to I132) under the Fuel Specs tab @ standard condition.

**Comment by arbrandt** [comment]
This is correct because GOR is at standard conditions, so represents moles per bbl, not volume. no need for fix.
