### ISSUE TITLE
M119 & M127 under Separation tab

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#377]
The expression to calculate the Crude oil FVF is wrong. Use this one: 
IF(C113="ON",IF($N$1="ON", AB110+ AB111 * M116 * (M114- 60) + AB112 * M116 / Oil_sg + AB113 * (M114- 60) / Oil_sg+ AB114 * M116 * M87/ Oil_sg,"NA"),"NA")

**Comment by arbrandt** [comment]
OK, fixed! thanks!
