### ISSUE TITLE
Incorrect indices in UltraBulk_assessment macro?

### ISSUE THREAD

**Issue by tachyus-ryan** [arbrandt/OPGEE#379]
I think I found an index issue in the UltraBulk_assessment macro:
![image](https://user-images.githubusercontent.com/79724437/119906039-0c810d00-bf13-11eb-8208-969b7e71117e.png)

The circled indices do not match the indices used to the right and below within the same condition block but _do_ match the indices used above. This appears to have been a copy/paste error.

**Comment by arbrandt** [comment]
Yes, this does appear to be a copy-paste error. Great catch. Fixed.
