### ISSUE TITLE
inconsistency of calculating gas specific gravity

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#381]
The expression of Gas_sg (cell AL135, under Fuel Specs tab) is TotalMW/ dry_air_MW.
However, the Gas_sg is calculated using TotalMW/wet_air_MW (row61 starting from column AD, under Flow_sheet tab)

**Comment by arbrandt** [comment]
According to petrowiki, dry air should be used: https://petrowiki.spe.org/Gas_properties 

Changed!
