### ISSUE TITLE
Gas density in the gas viscosity calculation in the reservoir tab

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#383]
Cell M62 in the Reservoir Tab should use gas density in the gas stream. Using the following expression
INDEX(FlowTable,RHO_G,25)
Reference : https://reader.elsevier.com/reader/sd/pii/B9780128158173000010?token=655DA5F659A95E7BC1053093AEFA93291F0EEFB07F1089D7C1831AE1C43CC8C2078C0352EBF4AE4EA664B4EEE0740DB4&originRegion=us-east-1&originCreation=20210604034402

**Comment by arbrandt** [comment]
Fixed! We already compute that on the flow sheet, so no need to implement in the reservoir sheet again.
