### ISSUE TITLE
Friction component pressure drop

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#387]
Cell M69 under well and downhole pump tab. 

The expression to calculate friction pressure drop uses gravitational constant in-unit lbm-ft/lbf-s2. Change gravitational constant to gravitational acceleration instead.

**Comment by arbrandt** [comment]
I just checked this and it looks like the units are correct. The left-hand section of the formula gives head in ft. Then the density / 144 converts to psi.
