### ISSUE TITLE
Produced water treatment

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#388]
Cell L31, Cell O31, Cell N31 are using the min temperature of input streams.
We should use the mixture liquid temperature equation as follows:
T = ( m1c1T1 + m2c2T2 ) / ( m1c1 + m2c2 )
where c1 and c2 are heat capacity (unit = Kj/(kg*K))
m1,m2 are mass (kg), T1 and T2 are temperature(K)
Since two input stream are both water stream, c1 = c2
So T = (m1T1 + m2T2)/(m1+m2)
Then the water density should consider the rho_w @ T and P

**Comment by arbrandt** [comment]
Fixed. Do not adjust rho for water, given relatively small change in water density. This can be fixed in later versions.
