### ISSUE TITLE
Exhaust from GT temperature

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#389]
The Cell J204 under Steam generation tab should use the following expression:

=CONVERT(IF(Turbine_type_HRSG="A",Constants!G2322,IF(Turbine_type_HRSG="B",Constants!H2322,IF(Turbine_type_HRSG="C",Constants!I2322,IF(Turbine_type_HRSG="D",Constants!J2322,"ERROR")))),"F","C")

**Comment by arbrandt** [comment]
Wow, good catch. Not sure how that made it in, but was shifted to an incorrect region. Fixed.
