### ISSUE TITLE
Fields with GOR=FOR get screened out

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#391]
It would be useful to allow fields with FOR=GOR to pass screening check, especially because of fields with no gas production and no flaring. VBA should be adjusted to allow FOR=GOR to advance (can still screen out when FOR>GOR).

**Comment by arbrandt** [comment]
Not clear exactly why that was happening as it was set in the code to ">" rather than ">=". To break the tie, I added that it needs to be > than GOR + 1.

**Comment by arbrandt** [comment]
Please check, not sure if this will work.

**Comment by qlangfitt** [comment]
Oops, this was my bad. You fixed had fixed this issue already on May 27 and I had simply forgotten that I had already asked you to do so. You can roll back the GOR+1 (unnecessary change).

**Comment by arbrandt** [comment]
Fixed again (rolled back that is)
