### ISSUE TITLE
Review the OTSG shell loss rate 

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#393]
Need to review the OTSG shell loss rate (Secondary Tab Line 279)

**Comment by arbrandt** [comment]
Found two references for OTSG radiative shell losses. COSIA SAGD template by Jacobs Engineering (see PFD p. 21 of report) suggests radiative shell loss of 35.3 GJ/h compared to total HHV fuel input of = 1758 GJ/h HHV. Converting to LHV basis, this is 1588.1 GJ/h LHV using OPGEE LHV/HHV ratio. Thus, loss on LHV basis amounts to 2.2%.  Herman 2019 thesis from U calgary assumes 2% loss. Changed default loss rate to 2% to account for these new references.

**Comment by arbrandt** [comment]
COSIA template also has HRSG case, which also has losses of ~2.2%. Updated HRSG shell loss as well.
