### ISSUE TITLE
Petcoke transport diesel fuel calculation bug

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#394]
On the Petcoke transport sheet, there's a mistake in the diesel fuel use equation. A set of parentheses are missing such that the energy production rate is not multiplied by all of the terms that it is supposed to be multiplied by.

**Comment by arbrandt** [comment]
Fixed. Good catch. Checking the other transport sheets now to see if that was copy-pasted from the crude oil transport sheet.

**Comment by arbrandt** [comment]
OK, checked the other sheets. All of the others use a cleaner array-based calculation.
