### ISSUE TITLE
LCFS-specific gas composition not aligned with documentation

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#395]
In documentation, the CO2 fraction increase was balanced by proportional reductions to all other species, but in model was balanced by only reduction in CH4 fraction. Documentation has the following composition:

![image](https://user-images.githubusercontent.com/47186327/124178993-0678d180-da67-11eb-896e-11ab87e26a0e.png)

**Comment by arbrandt** [comment]
Fixed.
