### ISSUE TITLE
heavy oil upgrading logic error

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#396]
In the Heavy Oil Upgrading tab, Cell B129, the formula is IF(M63=1,IF(Oil_sands_mine_nonint_01=1,B128/bbl_per_m3*M61,F12),B128*M61*liters_per_bbl/1000)

M63 is upgrading insitu oil or offsite. It is 1 if the upgrader type is not None and the oil sand mine integrated with upgrader is 0. However, if the upgrader is not None, how can oil sands mine (non-integrated with upgrader ) be 1?

======================================
B128 the formula is IF(M63=1,IF(Oil_sands_mine_nonint_01=1,Oil_prod,B129/M61*bbl_per_m3),K128/M106)

M61 is API_bitumen, should use API instead

**Comment by arbrandt** [comment]
I think the cell in B129 is correct. M63 asks if the oil sand is upgraded after being produced offsite at another mine or in situ facility. Oil sands can be mined at a separate facility than they are upgraded at. This occurs at the syncrude complex, where there is an old mine and new mine that both feed into one upgrader.

I believe in B128 it should be using the API of the bitumen, as that is counting an incoming bitumen stream going into the upgrader via another mine or a SAGD project.
