### ISSUE TITLE
the unit conversion error in the diluent transport

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#400]
Under diluent transport tab, cell98 to cell102, the unit conversion from tonne to lb is 2204.62 ([https://www.google.com/search?q=tonne+to+lb&rlz=1C1GCEU_enUS821US821&oq=tonne+to+lb&aqs=chrome..69i57j6j0l3.3304j0j7&sourceid=chrome&ie=UTF-8])

**Comment by qlangfitt** [comment]
I believe ship size is intended to be in short tons (not metric "tonnes"). If that's the case, the 2000 lb/ton conversion factor is accurate. Maybe that should be clarified on the inputs ("short tons" rather than just "tons").

**Comment by arbrandt** [comment]
Yes, Quinn is correct. Those factors are from the GREET model which uses american short tons, which are 2000 lbs. Unfortunately! Let's leave this for now. Eventually it would be better to convert all of the barbaric american units to standard units.
