### ISSUE TITLE
Separation electricity does not include in the electricity gen and imports tab

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#403]
The separation has an option to use electricity. However, the electricity gen and imports tab does not have this stream.

**Comment by arbrandt** [comment]
Fixed. Added a new electricity stream to the set of electricity streams. It is now stream 201: "Electricity - Separator". This now gets summed into the set of all electricity demands when needed to compute imports on the sheet, and is added to the flow sheet.
