### ISSUE TITLE
Bitumen mining fugitive calculation error

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#405]
In the Bitumen mining tab, the Cell L16 uses M54 which is the volume rate and conversion factor to get the molecular rate. Should use mol fraction instead of weight fraction to calculate mass rate instead.

See the following example:
N2_mass_rate = Mine_offgas_rate (scf/day) * conversion_factor (mol_total/scf) * mol_frac (mol_N2/mol_total) * molecula_weight (g/mol_N2)

**Comment by arbrandt** [comment]
Fixed Nov 22nd 2021 when I fixed errors noted by Quinn in another issue. We didn't ever have gas composition for the mine offgas or tailings leakage gas. So I now assume that it is all methane for simplicity.
