### ISSUE TITLE
Error in results when enabling embodied emissions 

### ISSUE THREAD

**Issue by jyuan03** [arbrandt/OPGEE#410]
Results show reference error when embodied emissions calculations are enabled. I could not attach the macro excel document to provide context but the error can be seen in the Embodied Emissions sheet of the latest beta version of OPGEE 3.

**Comment by qlangfitt** [comment]
Note for Adam/Jeff: I traced this to some calculations that draw on cumulative oil production per field from the drilling & development sheet, but the reference is broken. Embodied emissions cells M556, M652, and M664 should reference Drilling & development cell M15.

That said, I have other questions about the various estimates of EUR on the drilling and development sheet as the total cumulative energy production calculation is not reliant upon the cumulative oil production calculation.

**Comment by arbrandt** [comment]
Fixed. Now reference M15. Other issues with EUR raised by quinn here and in issue 414 will be handled in separate push.
