### ISSUE TITLE
steam injection (CWE) is wrong under produced water treatment

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#411]
In Cell M91, the equation to calculate the amount of steam required is 

Oil_prod*SOR/Quality_generator_outlet

we should use 

Oil_prod*SOR

Because the cold water equivalent defines SOR.

**Comment by arbrandt** [comment]
Good catch. You are correct. Steam oil ratio is defined as bbl of cold water turned to steam (of some quality) and injected. Therefore, the requirement on the water processing side should be the cold water barrels and not account for steam quality at all.
