### ISSUE TITLE
Circular reference in oil stabilization sheet

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#413]
Circular reference error (attached image) in the Crude oil stabilization sheet.

![image](https://user-images.githubusercontent.com/56744404/130536455-ae029224-7b53-4d68-a8f2-8e56f21f6892.png)

**Comment by arbrandt** [comment]
It is not showing that on my computer. circular refs is greyed out. Perhaps it is a excel setting? The model should have some iterative aspects, so will require circular references and convergence. This is because of the recycle loops. But I am not sure if those are valid or mistakes.
