### ISSUE TITLE
Screening macro screens out fields with a VOR but not a GOR

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#416]
If one enters a field with a specified VOR, but not a specified GOR, the screening macro skips the field. Need to adjust the macro to allow those fields to run

**Comment by arbrandt** [comment]
Fixed. It now checks to make sure there is a VOR and GOR before it applies the check.

**Comment by qlangfitt** [comment]
Now that you changed the definition of VOR, this check doesn't make sense on any level. Shouldn't any check with VOR just be thrown out?

**Comment by arbrandt** [comment]
Yikes, you are right. Neglected to think through implications of yesterdays change. Removed it completely as by definition it can;t be violated now.
