### ISSUE TITLE
Demethanizer light stream fraction condensed not used by the model

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#417]
On the Secondary Inputs sheet, the demethanizer light stream fraction condensed is not used by the model (Secondary Inputs rows 403-414). Consider removing.

**Comment by arbrandt** [comment]
Correct. Light fraction is just 1 - heavy fraction and so is not useful. We can just use the heavy fraction in calculations. Removed to simplify inputs sheet.
