### ISSUE TITLE
Active field sheet emissions summary issues

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#418]
Emissions summary at the top of active field sheet has a couple of issues. 

First is allocation of transport emissions. In the main output, the model assigns all transport emissions to the primary product. However, in the emissions summary, it allocates between the energy products. Can fix this by separately reporting process emissions and transport emissions in the emissions boxes and then dividing by the correct denominators. 

Second is how small sources are added for displacement vs. allocation. This causes the secondary co-product treatment (whichever is not selected on the Inputs sheet) to be slightly inaccurate. This can be fixed by adjusting the not-selected CI calculation to change the amount of emissions from the small sources adder.

**Comment by arbrandt** [comment]
Fixed. The small sources issue was a bit tricky to figure out.
