### ISSUE TITLE
OTSG air blower, HRSG air blower, Solar thermal HTF pumping

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#420]
Steam generation tab, Cell M259, M260, M261 should not multiply the fraction of steam that goes to OTSG, HRSG, and Solar Thermal. Because Cell G95, Cell B199, Cell M61 are the fuel consumption for OTSG, HRSG, solar thermal respectively.

**Comment by arbrandt** [comment]
I think the rows have changed in OPGEE since you posted this, because I fixed another issue. Can you please look at it and suggest what cells need to be fixed. I am not sure what you are referring to.

**Comment by arbrandt** [comment]
Figured it out. Now fixed. Great catch.
