### ISSUE TITLE
Electricity emission factor for CO2 emitted from work of seperation and injection

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#421]
Although the below change doesn't affect the CI , still to be consistent for the usage of electricity CI (similar to Cell **H92** where electricity CI is used from the fuel cycle spreadsheet)

Sheet **GHG Summary**
Cell **G105**
_Current version_

=IF(AND(Gas_flooding_01=1, Flood_gas_type=3), (('Gas Flooding Compressor'!B98+'CO2 Reinjection Compressor'!B149+'Sour Gas Reinjection Compressor'!B91)*'Emissions Factors'!$H$15+('Gas Flooding Compressor'!I98+'CO2 Reinjection Compressor'!I149+'Sour Gas Reinjection Compressor'!I91)*mmbtu_per_MWh*(1/1000)*'**Electricity Gen and Imports'!M126**), 0)/1000000

**Proposed** (in bold to replace the electricity emission factor with the one use from the fuel cycle sheet)

=IF(AND(Gas_flooding_01=1, Flood_gas_type=3), (('Gas Flooding Compressor'!B98+'CO2 Reinjection Compressor'!B149+'Sour Gas Reinjection Compressor'!B91)*'Emissions Factors'!$H$15+('Gas Flooding Compressor'!I98+'CO2 Reinjection Compressor'!I149+'Sour Gas Reinjection Compressor'!I91)*mmbtu_per_MWh*(1/1000)*'**Fuel Cycle'!D75**), 0)/1000000

**Comment by arbrandt** [comment]
Good catch. Fixed.
