### ISSUE TITLE
Purchased aka (new/fesh) CO2 is assumed 100% CO2 

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#427]
CO2 purchased from natural CO2 sources (is around 95-98% purity) and same range for industrial captured CO2. The model assumes 100% CO2 which makes higher gas flooding volumes through gas flooding compressor.

Can we include the composition of the CO2 same as NG import for gas flooding?

**Comment by arbrandt** [comment]
Good catch. I have added a new feature. Depending on the source of CO2, an impurity stream is added, defaulted to 3%. In the case of CO2 from natural CO2 sources the impurity is assumed to be 3% CH4. In the case of industrial captured CO2 from a power plant etc., the impurity is assumed to be 3% N2. These are new parameters added to secondary inputs that can be adjusted at will.
