### ISSUE TITLE
overall compression ratio issue in CO2 membrane

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#429]
It seems that the overall compressor ratio in the CO2 membrane tab is always equal to 1 (M61). 

overall compressor ratio = hydrocarbon-rich gas exit press (M60) / desired outlet line press (M58) 
while 
hydrocarbon-rich gas exit press (M60) = J32
J32 = desired outlet line press (M58)

**Comment by arbrandt** [comment]
This was clearly circular and strange. Added a feature to create assumed pressure drop of 150 psi across membrane. This could be calculated in much more detail of course, but this should suffice for now.
