### ISSUE TITLE
CO2 reinjection compressor

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#430]
I cannot see it is still necessary to have three parts of the compressor calculation section for each stream (input stream).

The compressor work calculation section for Ryan-Holmes F117 to O124 has the wrong reference for number of stages (for example, check G121)

**Comment by arbrandt** [comment]
Fixed. We want the three compressor calculations because the streams may be coming in from the different processing units at different pressures. So I just did the calculation 3 times to get the compression requirement from each steam.

**Comment by arbrandt** [comment]
Also, fixed the refernece for number of stages
