### ISSUE TITLE
Bitumen broken references and equations due to sheet reorganization

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#436]
The Bitumen mining and Flaring sheets were reconfigured when fixing Issue #423. This introduced some errors as follows:

- On Bitumen mining: The composition of the gas was removed, which was referenced by stream 84 (Mine offgas to flare). Now that stream has reference errors and breaks the model for oil sands fields. Could either re-add the gas composition or assume that all offgas to flare is CH4.
- On Bitumen mining: Stream 281 (mine face fugitives) is missing the conversion factor from grams to tonnes
- On Flaring: Streams 29 and 298 check whether there is any gas after the separator, however, for oil sands fields there can be mine offgas without any gas after separator. Need to change the check on streams 29 and 298 to see if there any gas in streams 28, 84, or 81, rather than just checking 28 (check the sum of 28, 84, and 81).

**Comment by arbrandt** [comment]
All issues addressed.
