### ISSUE TITLE
VOR does not accurately represent venting/oil_prod as FOR is increased

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#438]
Weird interplay between flaring and venting can cause untrue VOR (the oil prod * VOR does not equal the amount of vented gas).

This is because the VOR is applied post-flaring. The inner workings are such that VOR is applied by multiplying post-flare gas by the loss rate calculated as VOR/GOR. This means that fields with high rates of flaring will have very low purposeful venting (not in line with the input venting-to-oil ratio). Maybe that was intended to avoid model errors and/or recognize that flaring is a replacement for the type of venting signified by the VOR, but then the title of the input is a bit misleading. Perhaps just need clarification on the inputs sheet and/or documentation.

**Comment by arbrandt** [comment]
Changed the label on VOR. It is now called fraction of venting of post-flare gas. This is a much more accurate description of what it does. Equation on "venting" sheet is now changed to reference this fraction directly, which it applies to the post-flare gas stream.
