### ISSUE TITLE
small fixes

### ISSUE THREAD

**Issue by yuliachen** [arbrandt/OPGEE#44]
---  [secondary input] fix data validation of cell M214. Select AC214:AE214 as range of valid data.
---  [secondary input] add "fraction of water lost to reservoir" in "reservoir" section with default set to 0.1
---  [separation] change cell N14 to be "=IF($N$1="ON",Oil_prod*(1-Oil_sands_mine_int_01)*(1-Oil_sands_mine_nonint_01)*IF(Steam_flooding_01,SOR,WOR)*liters_per_bbl/1000-M14,0)*(1-'Secondary  inputs'!M36)" to account for steam flooding water mass and water loss to reservoir
---  [reservoir] add another stream 118 'water lost to reservoir' to 'flows out of process'. Water liquid in tonne/d is "=O14/(1-'Secondary inputs'!M36)-O14". Change liquid flow into the process accordingly as the sum of two water streams out of the process
--- [energy summary] cell O22 should be a sum of O23:O40
--- [separation] If the separation process is driven by electricity, the total electricity consumption in cell I221 is "=M202+M173+M145." For cell M173, include an "if error =0" logic similar to M172
--- [produced water treatment] change cell M92 to be "=1-Fraction_water_reinjected" for our purpose here
--- [steam generation] cell M79 should include "N1" not "N14"

**Comment by arbrandt** [comment]
Yulia, can you check and see which of these are still issues?

Also, if you re-post ones that need fixing, please break the list up into single issue items so that we can clear each one-by-one.
