### ISSUE TITLE
Typo in range of non-stratified deterministic component loss rates

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#440]
In the table on VF-Component for non-stratified loss rates (rows 247-260), the range that column E can pull from is not quite wide enough. This only impacts LU - no plunger (since it can't reach its value for tranche 10), but ideally would be adjusted in all of the entries on that column for consistency. Only affects very specific use cases, but in those cases the model breaks.

At a minimum, expand the range that can be drawn from in cell E260 (LU-no plunger deterministic loss rate) from FD375 to FE376.
i.e.: =IF(GOR>GOR_VF_cutoff,INDEX($C$376:$FE$376,1,$C$267+$B260),0)

**Comment by arbrandt** [comment]
Fixed. Thanks for catching that.
