### ISSUE TITLE
Crude oil density from upstream source

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#444]
On the Crude Oil Storage sheet, the crude oil density from upstream source is calculated in cell M62. However, this only covers cases where the inflow is from stream 10, 11, or 12 (stabilized crude, upgraded, or diluted), and the model thus breaks if the inflow is from stream 9 ("crude oil to storage") and the oil system boundary is "refinery."

**Comment by arbrandt** [comment]
Not sure why that was left out. Now there is a new row in that section: 
"Separated crude oil density (not stabilized)"

So we can choose from the crude density depending on the stream that is coming in.
