### ISSUE TITLE
Heavy oil / oil sands API gravity issues with circular logic

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#446]
There are at least a few places where the calculation of crude oil mass flow rate is based on the API gravity on the sheet, but the API gravity only pulls data if the mass flow rate is >0. This leads the model to break because the cells are relying on one another for calculation. In general, I don't see any reason why the API gravity boxes on the sheet would need to check for flow rates since they all just reference API_grav anyway. A couple of places where I have noted this issue so far:

- Heavy Oil Dilution: F56 (maybe just use API_grav for F56?)
- Heavy Oil Upgrading: M61 and M62 (maybe just use API_grav for M61 and the equation to calculate sg in M62?)

**Comment by arbrandt** [comment]
Fixed those instances. Let me know if there are others.
