### ISSUE TITLE
Gas flooding compressor mol fraction error

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#447]
Stream 78 uses mol fraction which is not correct. Please use mass fraction instead.

**Comment by arbrandt** [comment]
I think that is correct. It takes flow of gas in M54 which is measured in mmscf/d. mmscf/d is essentially a mole count. then it multiples that by the mole fraction or volume fraction from M39 (in the case of N2 in stream 78). That gives us mmscf of N2 per day. Then Fuel specs I122 is the tonnes per mmscf for N2.
