### ISSUE TITLE
Flaring from tank for fields without flaring otherwise

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#448]
For fields with a FOR of 0, the flaring sheet will be completely turned off. However, in cases where there is tank flaring for emissions control and FOR is 0, the quantity of flared gas from the tank (stream 81) will not make it into the mass balance on the Flow Sheet. Need to adjust the logic on the flaring sheet for stream 29 to always include the quantities of gas from streams 81 and 84, regardless of what the FOR is.

**Comment by arbrandt** [comment]
Fixed, now the sheet computes regardless of the status of FOR. Also, fixed the mass balance check on the RHS.
