### ISSUE TITLE
Steam Generation Secondary Inputs

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#45]
Clean up secondary inputs for steam generation

**Comment by yuliachen** [comment]
Jeff- 
I'm working on the steam generation sheet. There will be even more secondary inputs for the new steam generation sheet to enable the added features of steam generators. Do you have specific suggestions/thoughts on how to clean up the secondary inputs?

**Comment by yuliachen** [comment]
steam gen secondary inputs cleaned up with Feb 28, 2019 steam sheet updates
