### ISSUE TITLE
Another circular reference for bitumen

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#451]
Found another circular reference causing issues for bitumen API gravity. Stream 5 crude oil mass is calculated on Heavy Oil Upgrading (cell E12) and relies on the specific gravity calculated on the Flow Sheet (cell J32), but the flow sheet sg only calculates if the mass is positive. 

Suggest solving by having Heavy Oil Upgrading E12 reference Heavy Oil Upgrading M62 rather than the flow table for sg. That way, the flow sheet still shows a blank if heavy oil upgrading is not used, but there's no circular reference issue.

**Comment by arbrandt** [comment]
Fixed. I am perhaps imaging this, but it seems that the model is more responsive now that we are removing circular refs.
