### ISSUE TITLE
Add entry for emission reductions not modeled

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#452]
Add secondary input for generic emissions reductions from projects/practices not modeled in OPGEE. Allows user-entry of specified mass of CO2e/d reduced and then subtracts from the total modeled emissions in the CI calculation. Can probably factor this into the offsite emissions credit/debit line on the active field/results sheet, or if needed a new line.

**Comment by arbrandt** [comment]
Fixed on GHG summary page. Has optional new section on rows 117 to 120 where user can add in tonnes per day of emissions reductions from other sources. This adds to the credit that the field gets, for example, from exporting co-products or sequestering CO2.
