### ISSUE TITLE
Update uncertainty parameters for fraction vented after flaring

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#453]
VOR was changed to fraction of gas vented after flaring, but the uncertainty parameters were never adjusted on the Active Field sheet. Thus, when trying to model in uncertainty mode it breaks as the fraction of vented gas is generally >1.

**Comment by arbrandt** [comment]
Fixed, good catch. Mean is now 0.2% of post-flare gas vented. SD is 0.05%. Max is 10%, min is 0%.
