### ISSUE TITLE
Adjusted volumetric flood gas rate for CO2

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#455]
It does not currently factor into any calculations, but I believe there's an error in the calculation for the "Adjusted volumetric flood gas injection rate" for CO2 flooding (on the Gas Flooding Compressor sheet). The gas flooding compressor looks at the total volume of flood gas called for by the inputs (oil_prod*GFIR) and then takes on only the portion of that which is not already supplied by reinjection of produced gas.

In the case of CO2, the higher the breakthrough percentage, the lower the amount of gas that goes through the gas flooding compressor (since more of the total GFIR is supplied by reinjection of the gas that breaks through). This is reflected properly when stream 77 is calculated on the Gas Flooding Compressor sheet (it draws just from other streams), but I believe is not correctly calculated in cell M54. I think cell M54 does the inverse.

All that said, cell M54 only supplies data to other cells when the flood gas is not CO2, still, in case it is ever purposed for CO2 in the future it seems like it should be fixed.

If you agree, I think the last term should simply be IF(Flood_gas_type=3,M53*(1-Perc_CO2_breakthrough/100),...

**Comment by arbrandt** [comment]
I think this is an issue more with labeling. The CO2 imported from offsite column in the top of the sheet references other calculations to estimate CO2 requirements. M54 only drives HC and N2 flooding mass flow rates. I have re-labeled the label for M54 to account for this ("non-CO2"), and removed the section of the if statements that looks at CO2.
