### ISSUE TITLE
Activity factor adjustment tweaks

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#459]
- Add note to Secondary Inputs table that the AF adjustments only apply to deterministic calculations (won't apply in uncertainty mode).
- Make it so that if a user enters "0" for any equipment AF, the resulting emissions from that equipment type are hard set to 0. Suggesting implementing this in rows 13-22 of "VF - Activity Factors."
- Make it so that the regression cannot calculate negative leakage factor ratios. Implement on "VF - Activity Factors" rows 13-22, perhaps using MAX function to select the max of the regression calculated value or 0.
- Remove the 0s from the “other” equipment AFRs for equipment types not used in the gas and oil systems, respectively. Suggest to implement on "VF - Activity Factors" by just deleting the 0 values on Row 37 for equipment types not used in each the oil and gas system. For gas systems this is Header only. For oil systems this is Meter, Compressor, and Dehydrator.

**Comment by arbrandt** [comment]
All fixed. Please test!
