### ISSUE TITLE
OPGEE 3.0 runs--update GWPs, heavy oil runs are low, oil+gas switch

### ISSUE THREAD

**Issue by francesreu** [arbrandt/OPGEE#46]
1) The default GWP values should be set to AR5 with CCF (currently AR4). In Constants tab D73, value should be 34 for methane. This change is needed to be consistent with most recent PRELIM. 

2) Runs for these three fields yielded abnormally low results: Midway Sunset, South Belridge, and Lula. 

Note from Mohammad on the origin of the issue:
“I tracked the differences between Midway Sunset 2.0 and 3.0 runs. The difference originates from: production and extraction energy consumption>> crude oil mmbtu/d in Energy Consumption sheets are different between 2.0 and 3.0. Seems that the conversion in 3.0 from bbl/d to tonnes/d is a problem (see Separation sheet cell M12).”

3)  Addition of “Oil+gas” switch is needed for ClimateWorks grant

**Comment by francesreu** [comment]
After re-running the model yesterday, Midway Sunset values had improved. However, South Belridge still was 1.5X lower than its OCI 2.5 value, and Lula was nearly 5X lower.

**Comment by arbrandt** [comment]
GWPs updated.
