### ISSUE TITLE
Error in the fraction of gas flaring and LHV of gas flared in Flaring Tab - Field 5435

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#462]
Formulars in fraction of gas flared (M69) and LHV of gas flared (M70) can have 0 denominators. Please use if statement check 0 denominators.

**Comment by arbrandt** [comment]
Fixed both of these issues. See new fixed sheet. Also fixed the equation for gas heating value, which was missing one of the input columns.
