### ISSUE TITLE
Wellhead energy production per field in the Drilling & Development Tab

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#467]
Cell (M18) in the Drilling & Development Tab uses 'Flow Sheet'!I46 (oil LHV at wellhead) & 'Flow Sheet'!AF82 (gas LHV at wellhead). Both units are in the mmbtu/day not MMBtu

**Comment by wennanlong** [comment]
Should also consider the oil sand mining option.

**Comment by qlangfitt** [comment]
To be clear, I think the clarification is to change the units label, not to change the calculation, right? I looked at it and it seems like the calculations are all accurate, but as Wennan points out the units are mislabeled.

**Comment by arbrandt** [comment]
EIA seems to favor MMBtu as the spelling. The initial capital in Btu is very consistently applied rather than full capital BTU. They most often write out "million" but when they do use the abbreviation it is written as MMBtu. so I changed all worksheet refs to MMBtu using find and replace.
