### ISSUE TITLE
Heavy oil upgrading and diluent error

### ISSUE THREAD

**Issue by KyleMcGaughy** [arbrandt/OPGEE#478]
Using both heavy oil dilution and upgrading at the same time takes the liquid stream from the dilution sheet, but the solid stream from the upgrading sheet. This does not set off a mass balance error even though it should. Ideally if both diluent and upgrading are enabled the oil would first go to diluent then to upgrading, which reflects actual processing in oil sands operations. Attached is a step by step guide to fix this error, add a new error flag to identify if a mine is using neither diluent nor upgrading, and to remove diluent and upgrading dependency on mining status in the input sheet.

[3.0a diluent upgrading bugfix log.xlsx](https://github.com/arbrandt/OPGEE/files/9215765/3.0a.diluent.upgrading.bugfix.log.xlsx)

**Comment by KyleMcGaughy** [comment]
Small mistake when I was correcting 'Heavy Oil Dilution' cell E12; should be '=IF($N$1="ON",B128*m3_per_bbl*@INDEX(FlowTable,GAMMA_O,5)*(Oil_sands_mine_int_01),0)'
The listed fix in the original comment does not properly turn off crude flow from the mine source if mining is turned off.

**Comment by KyleMcGaughy** [comment]
For my proposed changes, Heavy Oil Dilution cell E12 should be '=IF($N$1="ON",IF(M38=0,Oil_prod*F57*m3_per_bbl*Oil_sands_mine_nonint_01,0),0)' If dilution is on, and mining is not, the mining stream gets set to zero. If dilution and mining are on, but there is offsite upgrading then mining stream is set to 0, but with onsite upgrading mining stream will be the normal production value. This is not an elegant solution, but it works.

**Comment by wennanlong** [comment]
The design doc is https://docs.google.com/document/d/1g5Pom2RpwfcO3VIHmrYoopaIe0iPXd3dvVeLVMdZCOE/edit?usp=sharing
