### ISSUE TITLE
Results changed by secondary product system boundary

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#49]
The GHG emissions for the primary product (i.e., row 193 of Results) change when the system boundary of the secondary product is changed. I think this is an error. If it is not, then we need to be careful about guidance for how to select the secondary product’s system boundary.

**Comment by arbrandt** [comment]
See comment to #51. I need to noodle on this. I think the math is working "correctly" in the narrow sense. But as you note, I think we need to think carefully about suggesting commensurate boundaries for analysis on the two sides.

**Comment by qlangfitt** [comment]
I think it would be a good solution to suggest (require?) that the secondary product's system boundary always be set to "field". The reason is that all of the additional processes that occur when gas boundary is increased act only on the gas system, so why allocate those back to the oil when analyzing oil? Same is true for the reverse - all processes turned on when the oil boundary is increased from field to refinery act only on the oil product system, so why allocate those back to gas when analyzing gas? Such a condition could easily be added as an error check if we wanted to essentially force that selection. This would go a good way toward reducing the improper allocation of processes that act only on one product system.

**Comment by arbrandt** [comment]
Agree that a flag is the right way to do it. Added an error check. Fixed on Feb 10th.
