### ISSUE TITLE
Mass balance error when gas boundary not distribution

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#50]
The model outputs an error for the check “Gas composition (II)” any time the gas system boundary is not distribution. I’ve tracked this back to the Flow Sheet (Column LM). This seems to occur because the product stream of CH4 is excluded from total outputs (column LK) when the boundary is less than distribution. This leads an imbalance since the total amount of gas is still produced and included in the inputs. This leads an ERROR being displayed under the results.

**Comment by arbrandt** [comment]
Fixed in version pushed Feb 21 12:05 PM. Logic in "Transport to market" column of flow sheet mass balance now refers to the newly defined parameter "Gas_boundary_setting" to make sure that the bulk of gas leaving the boundary is counted.
