### ISSUE TITLE
Upstream emissions change when system boundary extended

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#51]
When the gas system boundary is changed, the emissions from the upstream life cycle stages change. This may or may not be an error (The question is, does the model calculate emissions per MJ of primary product produced, or per MJ delivered?).

**Comment by arbrandt** [comment]
Was checking it with debug field 400. Part of the difference (small) comes from offsite and differences in the amount of gas counted in the denominator. More of the difference comes from VFF beyond the field. So a "field" gas boundary avoids VFF from the trans and distribution sectors.

It only counts emissions (and outputs) up to the boundary selected, which I think is right. What I am unsure about is whether the user should have the option of selecting inconsistent boundaries (i.e., field for one and distribution for the other).

Keeping this issue active for future noodling.

**Comment by arbrandt** [comment]
Fixed, I believe, with error check added in fix to issue #49 when suggesting to user that secondary product boundary is always set to field.
