### ISSUE TITLE
Effective output energy stream drawing diluent co-product treatment instead of NG

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#52]
On the Energy Summary sheet, the effective output energy stream (E117) references Table 3 above to draw allocation/displacement treatment. The formula pairs the secondary product output with an on/off factor for displacement for each product. The on/off factor multiplied by the natural gas output stream references the allocation/displacement treatment for diluent rather than natural gas. I believe the formula should read: =E111+E113*(1-G79)+E114*(1-G75)+E115*(1-G77)+E116*(1-G83)

Making the fix on my end significantly improves the correlation between OPGEE 2.0 and 3.0 (see plots below; line represents 1:1 relationship).

![olrds-op3-points](https://user-images.githubusercontent.com/47186327/52141895-f9dcbe80-260b-11e9-9963-b8b7329fd1f0.png)

![olrds-op3-points_v2](https://user-images.githubusercontent.com/47186327/52141487-c0578380-260a-11e9-95bb-bedc61c32aa6.png)

**Comment by arbrandt** [comment]
Found and fixed independently! Good catch. I found this this morning when debugging issues between 2.0 and 3.0. That is what I get for falling behind on github issues!
