### ISSUE TITLE
VRU Compressor can have higher than 100% leak rate

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#53]
When testing the inputs used to develop the LCFS oil baseline, the gas composition II error check would break for some fields with a #NUM. When the VBA code tries to check whether that box contains the word "ERROR" (Ln 439), it cannot make the comparison (Error 13: Type mismatch). I tracked this back to very low oil production. The VRU Compressor sheet references emissions from the fugitive sheets, which provide a fugitive mass loss rate (kg/d). When the VRU is pulling less than that loss rate off of the oil tank (because of very low oil production rate), it leads to a negative amount of gas being captured (stream 33). OPGEE seems to permit that being negative, but breaks if the total gas gathered (stream 34) is negative. I think a good solution would be to require that the fugitive rate from the VRU compressor (stream 280) cannot exceed vapors to the VRU (stream 82). Can be done with an IF statement on the VRU Compressor sheet at the chosen fractional loss rate (row 69).

Code for VRU Compressor M69 that fixes issue: =IF(IF(Settings_Fugitives="Component",M66,IF(Settings_Fugitives="Site",M68,0))>1,1,IF(Settings_Fugitives="Component",M66,IF(Settings_Fugitives="Site",M68,0)))

This issue is unusual to see because very low oil production would typically suggest high gas production (i.e., it's a gas field), in which case the gathered gas would far outweigh the negative from VRU fugitives and not really affect results. However, in the LCFS data it does come into play because some fields are simply very small.

**Comment by arbrandt** [comment]
Fixed. Broke the formula suggested into two cells to make it a bit easier to read. Also, set a threshold to 95%. If the computed leakage rate would exceed 95% of the throughput gas, force it max leak 95%.
