### ISSUE TITLE
Drilling & development significantly underestimates emissions for dry gas

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#54]
The drilling and development sheet relies on spreading well drilling & development emissions over the life of the well based on its total lifetime assumed production of oil (from the secondary inputs) and the daily production rate (from the inputs). Therefore, with dry gas fields that have a very low oil production rate, this approach will spread the impacts of drilling & development over an incredibly long time period (resulting in very small daily D&D emissions). An example of this scenario is Field 137 (Sulige). There are a few remedies I can think of and have outlined below. Maybe you all have a better idea.

-Option 1: Base calculations on the drilling and development sheet on the barrels of oil equivalent (sum of oil and gas energy content).

-Option 2: Base calculations on the drilling and development sheet on either oil or gas (in bbl oil-eq) based on the GOR of the well being analyzed.

-Option 3: Base calculations on the selected functional unit (I have concerns about this one since changing the unit would cause field development intensity to change).

-Option 4: Include a "dry gas" lifetime oil production option on the secondary inputs sheet that is much lower than any option currently there. Provide specific guidance for what to put for oil production of dry gas fields to ensure compatibility.

**Comment by arbrandt** [comment]
Went with option 1. Before it was doing option 3 effectively, which I agree is a bit strange. Now the total energy production is mmbtu of total oil + gas energy. This also pointed to a small fix on the active field sheet in the denominator of the MJ/MJ energy intensities.
