### ISSUE TITLE
Well and Downhole Pump sheet fixes

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#55]
A couple of small things:

- The pressure traverse friction component (row 69) is calculated in ft of head (by dimensional analysis and eqn 7.28 in documentation). The units on the sheet show psi, and psi is needed to be consistent with subsequent calculations. Should be multiplied by 0.433*specific gravity.
- The prime mover fuel use (rows 76-69) are simply pulling the efficiency numbers over from the Drivers sheet. Therefore, they fuel efficiencies and should not be in mmbtu/d or kWh/d. The math works because these are multiplied by bhp of the prime mover in the subsequent rows. Units just need to be labeled correctly.

**Comment by smasnadi** [comment]
- multiplied by 0.433. By specific gravity, which cell you are referring to?
- All units are removed.

**Comment by smasnadi** [comment]
If these are efficiencies, why in cell M77 we have unit conversion (btu_per_kWh)?

**Comment by qlangfitt** [comment]
Comment 1:
Specific gravity is multiplied in that equation because the 0.433 factor is based on the density of water: (62.4 lb/ft^3) / (144 in^2/ft^2).

However, since there isn't a cell with specific gravity on the sheet, perhaps the more elegant solution is to nix the 0.433 and instead go straight to the density of oil:
(_M63_ lb/ft^3) / (144 in^2/ft^2)

Then the equation in cell M69 would be:
=((Friction_factor*Field_depth*M62^2)/(2*Well_diam/12*32.2))*M63/144

Comment 2:
As for the "efficiencies", they should not be unitless, and that's not what I intended in the original comment, though I can see it wasn't clear. On the drivers sheet, the efficiencies are all in btu/bhp-hr. I was simply asking that the units for cells N76, N78, and N79 be changed to btu/bhp-hr and for cell N77 to be changed to kWh/bhp-hr. The conversion in M77 is proper.

**Comment by smasnadi** [comment]
Thanks for clarification. All are now fixed!
