### ISSUE TITLE
add another stream as water lost to reservoir when water/steam flooding is used

### ISSUE THREAD

**Issue by yuliachen** [arbrandt/OPGEE#58]
add "fraction of water lost to reservoir" in "reservoir" section of secondary input sheet with default set to 0
In the Feb 22 version of OPGEE, the preferred cell to add this input is 'secondary inputs' M89

**Comment by yuliachen** [comment]
add another stream 118 'water lost to reservoir' to 'flows out of process' on 'reservoir' sheet. Water liquid in tonne/d is "=O14/(1-'Secondary inputs'!M36)-O14". Change liquid flow into the process accordingly as the sum of two water streams out of the process

**Comment by arbrandt** [comment]
We don't do a full mass balance on the reservoir, and only model flows at the reservoir-well interface. In future versions of the model we might want to add this, but not for 3.0.
