### ISSUE TITLE
VF-Site "draws with replacement" fixes

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#64]
On the VF-Site sheet, the "selected bin means across number of sites" (M115) has two issues.

- For the N sites calculation the fomula draws on one too many cells. The formula ends with 13+M88, and even though the first site is in the 13th cell across 13+M88 is inclusive. Should be 12+M88 instead. 
- For the 5 and 1000 sites calculations (N116:O116), the averaging range is vertical, but the random draws are horizontal.

**Comment by smasnadi** [comment]
Fixed!
