### ISSUE TITLE
Chiller energy consumption has extra conversion term

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#70]
On the _Chiller_ sheet, the chiller energy consumption (M44) matches the equation in the documentation (Eqn 7.99), except that in the Excel sheet it has an additional *24 factor. Presumably this is to convert from /hr to /d, but the units in the documentation are already /d. The units in the documentation also don't seem work out, since Ec is supposedly in in kWh/d, but the dimensional analysis reveals MWh/d. That said, in Excel, tonne/d is used for Qc so those units do work (excluding the factor of 24).

**Comment by smasnadi** [comment]
Adam: I agree with CARB. I removed 24. But the documentation equation (7.104) unit is not clear to me.

**Comment by qlangfitt** [comment]
I've looked back at it again and I was wrong in my original error report. I now think the equation as originally written in OPGEE was correct. I also went back to the original source to ensure all of the units are correct. 

The equation as written in the documentation calculates in MW (so please do change the Ec unit in the text of the documentation from kWh/d to MW). Then the 24 hour/day factor is proper since that converts MW to MWh/d. Finally, to get the result in kWh/d as stated on the Chiller sheet (M44), an implicit unit conversion is done within the cell: 

(1000 kWh/MWh) / (1000 t/mmkg)

Perhaps Adam's eyes should still go on it, but I think it should be reverted to the prior equation by multiplying by 24 once again.

**Comment by smasnadi** [comment]
Ok, I now got access to the source, and agree. 
- The 24 factor is back.
- Documentation text unit is changed to MW
