### ISSUE TITLE
14.7 psi added to absolute pressure on some compressor sheets

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#71]
On compressor sheets where the compressor discharges into the reservoir (list follows), the absolute discharge pressure is calculated as reservoir pressure+delta pressure+14.7. The reservoir pressure is already in absolute pressure, so I think the addition of the 14.7 term is erroneous.

- Gas reinjection compressor
- Gas flooding compressor
- CO2 reinjection compressor
- Sour gas reinjection compressor

**Comment by smasnadi** [comment]
Fixed!
