### ISSUE TITLE
Gas fraction to storage, distribution, and liquefaction definitions

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#73]
On the _Transmission Compressor_ sheet, the gas split to the different pathways is confusing to me. The model treats the gas to liquefaction input as the percent of gas not going to storage that is liquefied. That isn't clear on the secondary inputs sheet. If we are going to retain that treatment, it needs to be explained on the secondary inputs sheet. If instead both the frac_gas_storage and frac_liquefaction are supposed to represent the fraction of stream 45 that goes to each path, then we need to adjust the calculations for streams 50 and 85 (for 50, add the last two terms rather than multiply; for 85, remove the   (1-frac_gas_storage) factor). Finally, we would need to add an error check to ensure that we don't go over 100% with the sum of gas to storage and gas to liquefaction.

**Comment by JSRuthe** [comment]
@qlangfitt  Can you please specify how exactly you propose what stream 50 should look like ("add the last two terms rather than multiply")?

**Comment by qlangfitt** [comment]
My apologies, I wrote the wrong stream number. When I said stream 50, I should have said stream 49. That is change it to the following, to calculate the gas to distribution as the sum of the fractions of gas not going to storage and not going to liquefaction.

=IF(AND($N$1="ON",$E$28>0),(E16-M16-N16)*(1-Frac_gas_storage_01)+(1-Frac_liquefaction_01),0)

**Comment by JSRuthe** [comment]
Hi Quinn, I'm still confused about your suggested fix.

In a typical case Frac_gas_storage_01 = 0, and Frac_liquefaction <1

In this case, [(1 - Frac_gas_storage_01) + (1 - Frac_liquefaction)] > 1

This will cause mass balance issues in our model. Am I missing something here?

**Comment by qlangfitt** [comment]
You're right. I should have suggested (1 - Frac_gas_storage - Frac_liquefaction).

> If instead both the frac_gas_storage and frac_liquefaction are supposed to represent the fraction of stream 45 that goes to each path

All of this is based on the assumption that you're using the definition above. Is that what you plan to do?

**Comment by JSRuthe** [comment]
Thanks Quinn, this makes sense. Fixed accordingly
