### ISSUE TITLE
CO reference doesn't track stream in VF CO2e aggregation

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#75]
On the _Venting and Fugitives 3.0_ sheet, the CO term in the tables aggregating the CO2e by life cycle stage (rows 58-83) doesn't track across the columns. Remove the dollar sign before the E and apply across all cells.

**Comment by smasnadi** [comment]
Seems that it is already fixed. Right?

**Comment by qlangfitt** [comment]
This is probably all moot since we wouldn't expect fugitive CO, but see the image below. For the screenshot I have clicked in H58. Notice how the selection for CO remains the flow from stream 250, even though it is a different stream that is being calculated in H58. This is a problem for every selection in these two tables (except of course for column E).

![image](https://user-images.githubusercontent.com/47186327/57320565-09105400-70b4-11e9-9d45-8b832436305d.png)

**Comment by smasnadi** [comment]
Thanks for clarification. Fixed!
