### ISSUE TITLE
definition of fraction of remaining NG reinjected

### ISSUE THREAD

**Issue by yuliachen** [arbrandt/OPGEE#78]
On [Gas Partition B], the calulations of stream 43 and 49 have an extra factor of "/100". I believe this is errornous because the default value of "fraction of remaining NG reinjected" is 1

**Comment by qlangfitt** [comment]
Agreed. This may stem from the fact that the _Inputs_ sheet asks for "Percent of remaining natural gas reinjected". The _Active Field_ sheet has the same input labeled as "Fraction of remaining natural gas reinjection". To be consistent with the other inputs around it, I think it should be fraction, and the /100 should be removed as suggested.

**Comment by yuliachen** [comment]
fixed with updates on 10/20/2019 AM 
also changed field 417-420 inputs from percentage into fraction; other inputs seem to already recognize this quantity as a fraction
