### ISSUE TITLE
Some gas streams treat t/d fugitive rate as percent rate

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#80]
On the _Gas Storage Wells_ sheet, the gas to reservoir stream (52) calculates flow rate as if it's drawing on a leak percentage. It is actually drawing on a leak flow rate. Easiest way to solve this is to simply make it: IF($N$1="ON",(E16-J16),0). This is also happening on the _Storage Separator_ sheet for the gas to storage boosting compressor stream (53).

**Comment by JSRuthe** [comment]
fixed
