### ISSUE TITLE
Work of compressor can go negative on Transmission Compression

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#82]
On the _Transmission Compressor_ sheet, the work of compression can be negative if the outlet pressure is lower than the inlet pressure. Unless that compressor can generate electricity back to the grid, it should be capped at a minimum work rate of 0. I don't know how often lower discharge than inlet pressure happens in the real world or in the OPGEE world, but at least to keep OPGEE from doing things are obviously wrong, maybe a cap at 0 should be set for the work of all OPGEE compressors.

**Comment by smasnadi** [comment]
Fixed! Please check cell M50.

**Comment by qlangfitt** [comment]
It looks good to me except for one small mistake. The last IF is written IIF. Technically, the case of 5 stages isn't covered by the 0 minimum, but I don't think that matters since I think the conditions that could create a negative value would result in only 1 stage.

**Comment by smasnadi** [comment]
Good eyes. Thank you. Fixed.
