### ISSUE TITLE
Surface piping leakage points to an equipment count

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#84]
On the _Venting_ sheet, the default surface piping leakage (N39) references the count of Headers in the component approach.

**Comment by smasnadi** [comment]
Adam: I changed it to Header Value used. Does it make sense?

**Comment by qlangfitt** [comment]
With the new fugitives module this now refers to a blank cell.

**Comment by JSRuthe** [comment]
See connected commit
