### ISSUE TITLE
Inconsistency in fugitives denominator

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#85]
I've just finished going through the compressors, glycol dehydrator, and AGR sheets and am noticing a lot of inconsistency with how the fugitive streams are calculated. I realize that it will make little difference in most cases, but I think there should be a consistent treatment. In cases where natural gas is the gas being compressed, the fugitive calculation usually divides the CH4 leak rate (from VF Component or VF Site sheets) by the incoming CH4 mass flow rate. Then the other constituents of inflow gas are leaked off at the CH4-based fractional rate. However, sometimes the CH4 mass leak rate is divided by the total gas volume and that fractional leak rate is then multiplied by all constituents (see Glycol Dehydrator for one example). To add to the confusion, some of the streams have little to no CH4 (e.g., for CO2 reinjection) and the leak rate is then interpreted as a CO2 leak rate on the compressor sheet, despite pulling a "CH4" leak rate from the fugitives sheets. I propose to standardize this treatment by doing one of the following:

1. Use the main constituent (CH4 or N2 or CO2) flow rate as the denominator to calculate a fractional leak rate and assume that the "CH4" leak rate from the fugitives sheets simply means the leak rate of the main constituent.

2. Use the total gas flow rate as the denominator in all cases and assume that the "CH4" leak rate from the fugitives sheet means the total gas leak rate.

3. For compressors compressing natural gas, use CH4 flow rate as denominator to calculate fractional leak rate, and compressors compressing any other gases assume the "CH4" mass leak rate is the leak rate of total gas.

**Comment by JSRuthe** [comment]
Based on the recent update to the VF model (both component and site-level), our treatment is mostly consistent. Most streams (if not all) are now handled on a fractional loss rate basis. @qlangfitt in the interests of clarity, I'm going to close this and propose that all issues in this regard get handled on a case-by-case basis (if any still exist)
