### ISSUE TITLE
Energy intensity of on-site electrical generation missing unit conversion

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#88]
On the _Electricity Gen and Imports_ sheet, the energy intensity of on-site electricity generation (M100) is missing a conversion of 1/0.75 to adjust units from /hp to /kW, as in Eqn 7.119 in the documentation.

**Comment by smasnadi** [comment]
Adam: I agree with the 0.75 missing factor (based on eq. 7.134), and fixed it. But still this does not make it as eq. 7.134.

Eq. 7.134: e_GS=e_D/(0.75*eta_G)

**Comment by qlangfitt** [comment]
I don't see any issue remaining. My view on it is that the 1/0.75 that was added fixed the whole issue and it's now the equation as you wrote it here.
