### ISSUE TITLE
Crude oil FVF for separation

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#91]
On the _Separation_ sheet, the Crude oil FVF is calculated for each of the three stages (first time at row 106). These cells correlate to equation 5.4 in the documentation. I think there are two mistakes in the equations based on comparing them to the documentation. The same issues are present all three times FVF is calculated, but the cells here refer to the first time (row 106). First, M91 should be M104. Second, M85 that is divided by (wellhead_temperature-60) about 2/3 of the way through the   equation should be oil_sg. The new equation would read: =IF($N$1="ON",AB106+ AB107 * M104 * (Wellhead_temperature- 60) +   AB108 * M104 / Oil_sg + AB109 * (Wellhead_temperature- 60) / Oil_sg+ AB110 *   M104 * M85/ Oil_sg,"NA").

**Comment by smasnadi** [comment]
Fixed!
