### ISSUE TITLE
Crude oil specific gravity for separation

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#92]
On the _Separation_ sheet, the crude oil specific gravity (calculated three times, starting row 107) seems to have an issue. I'm not absolutely sure, but it doesn't seem to align with the documentation (eqn 5.8). Instead of using the crude oil solution gas ratio in the numerator, instead the ratio of the MW of gas to moist air is used. Maybe I'm misinterpreting and this MW ratio is part of accounting for something, but the crude oil solution gas ratio still seems to be missing.

**Comment by smasnadi** [comment]
Adam: I don't understand the equation neither.

**Comment by arbrandt** [comment]
Fixed. Not sure why the equation was like it was. Notes:
- Adopted the correct equation from the flow sheet and documentation.
- Should be computed 3 times, as the separator has 3 stages
- Each time we should compute the gas in solution, specific gravity, density etc. at those conditions
- Temperature should drop between wellhead temperature and temperature of crude leaving the  separator (in this case 150F and 90F).
- SG should approach that of cold gas-less crude in the storage tank, which it now does.
