### ISSUE TITLE
Gas distribution fugitives not set up correctly

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#93]
On the Gas Distribution sheet, the fugitive losses have a lot of issues. I think the calculations section used to break out the fugitive losses more, and then some some of them were moved to secondary inputs. The way it is now, the fugitive losses calculated in the calculations section are either loss fractions or blank cells divided by 1000. That said, most of the flow table is accurate, drawing on the secondary inputs, just a few spots try to pull from the bad cells.

**Comment by JSRuthe** [comment]
Quinn, I don't see any issues here. There are outdated, unreferenced cells but they weren't referencing anything. I have deleted the unreferenced cells (see the latest commit). Please comment if there are any remaining issues

**Comment by JSRuthe** [comment]
@qlangfitt  can you please double check the Gas Distribution sheet and check for any remaining issues. Like I mention above, I have done by best to delete unreferenced cells. If you see anything, please specify the exact cells

**Comment by qlangfitt** [comment]
It looks good to me. I think everything is calculating correctly now. Only thing I would still change is to fix the #REF! errors in the solids and liquids for outflows (just set the cells to 0s) (P11:U15), just because they look bad.

**Comment by JSRuthe** [comment]
done
