### ISSUE TITLE
Total predicted fuel gas product from demethanizer

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#99]
On the Demethanizer sheet, the total predicted fuel gas product is calculated (M126). There is at least 1 problem with this calculation. Cell M1196 is referenced, but that is clearly a typo. I'm not sure if it was supposed to be M119, M116, etc. The numerator of this equation makes sense to me - it's the CH4 in the inflow gas minus the CH4 that leaves through the NGL stream, and therefore represents the CH4 out of the demethanizer in the fuel gas stream. I believe the denominator is to correct for the fact that the fuel gas stream still contains some NGLs, by dividing the CH4 flow rate by the fraction of that stream that is CH4. However, it also includes a term (-M1196*M122)/M118 that I can't make sense of. I assume this has something to do with accounting for ethane, since ethane still makes up a non-negligible percentage of sales gas. Maybe some clarity on what -M1196 should actually be would help me understand.

**Comment by smasnadi** [comment]
Jeff: I understand that you combined two mole balance equations (for C1 and C2) to get the total fuel gas, but cannot follow your equation. Also M1196 is miss-referenced. Please double check it.

It would be helpful to also add what you exactly did in the Notes section of row 126.

**Comment by JSRuthe** [comment]
Fixed cell reference and added a note about the mass balance equation
